**Rearrange data**

In [1]:
import numpy as np
import scipy as sp
import seaborn as sns
import pandas as pd
import scipy
import sklearn
import os
import mne
import networkx as nx
# import pycircstat as ps
from matplotlib import pyplot as plt
from scipy.io import loadmat

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
folder            = '/Users/ren/Projects-NeuroCode/MyExperiment/Aging-SeqMemTask' #'/Users/renxiangjuan/Nextcloud/MATLAB/MyExperiment/Aging-SeqMemTask'
data_behv         = folder + '/AgingReplay-OnlineData/' 
data_behv_inHouse = folder + '/AgingReplay-InHouseData/' 
statSaveDir       = folder + '/AgingReplay-StatAnal/' 
modelSaveDir      = folder + '/ModelFitting_Results/'

FBdata_folder     = data_behv + 'FlexibleBindingPaper-Data/'

# Experiment 1: memory gradation across content, position and reconstruction report in both younger (18-30 ys) and older (>75 ys) adults

<div class="alert alert-success">
<b>(Columns) variables</b>:
    
{0: 'groupNo', 1: 'subjNo', 2: 'trialNo', 3: 'measNo', 4: 'accuracy', 5: 'fullyCor'}

groupNo: younger or older
    
measNo: content, position, and reconstruction
</div>

## Figure 2A and 2B-left panel: mixture comparison –– within age group comparison with trial numbers and response types as regressor & between age group comparsion

coding each response per slot as 1 (correct) or 0 (incorrect)

The data wass originally saved in seqMemTask_v1_anal_summary.m

In [4]:
respMat = loadmat(data_behv + 'resp_glmm_group_exp1.mat') # 'resp_glmm_group'
resp_glmm_group = respMat['resp_glmm_group']
resp_glmm_pd    = pd.DataFrame(resp_glmm_group)
resp_glmm_pd

       0   1   2  3  4  5
0      0   0   1  1  0  1
1      0   0   1  2  0  1
2      0   0   1  3  0  1
3      0   0   1  4  0  1
4      0   0   1  5  0  1
...   ..  ..  .. .. .. ..
63355  1  26  64  1  2  0
63356  1  26  64  2  2  0
63357  1  26  64  3  2  0
63358  1  26  64  4  2  0
63359  1  26  64  5  2  0

[63360 rows x 6 columns]

In [5]:
column_name = {0: 'groupNo', 1: 'subjNo', 2: 'trialNo', 3: 'transNo', 4: 'measNo', 5: 'resp'} 
resp_glmm_pd = resp_glmm_pd.rename(columns = column_name) 
resp_glmm_pd.groupNo = resp_glmm_pd.groupNo.astype('int64')
resp_glmm_pd.subjNo  = resp_glmm_pd.subjNo.astype('int64')
resp_glmm_pd.trialNo = resp_glmm_pd.trialNo.astype('int64')
resp_glmm_pd.transNo = resp_glmm_pd.transNo.astype('int64')
resp_glmm_pd.measNo  = resp_glmm_pd.measNo.astype('int64')
resp_glmm_pd.resp    = resp_glmm_pd.resp.astype('int64')
resp_glmm_pd

       groupNo  subjNo  trialNo  transNo  measNo  resp
0            0       0        1        1       0     1
1            0       0        1        2       0     1
2            0       0        1        3       0     1
3            0       0        1        4       0     1
4            0       0        1        5       0     1
...        ...     ...      ...      ...     ...   ...
63355        1      26       64        1       2     0
63356        1      26       64        2       2     0
63357        1      26       64        3       2     0
63358        1      26       64        4       2     0
63359        1      26       64        5       2     0

[63360 rows x 6 columns]

In [6]:
nGroup = 2 # younger and older groups
nMeas  = 3 # three measures: content, position and reconstruction
groupList = ['0younger', '1older']
measList  = ['0content', '1position', '2both']
for iM in range(0, nMeas):
    resp_glmm_pd.loc[(resp_glmm_pd["measNo"] == iM), "measNo"] = measList[iM]
for iGrp in range(0, nGroup):
    resp_glmm_pd.loc[(resp_glmm_pd["groupNo"] == iGrp), "groupNo"] = groupList[iGrp]  
resp_glmm_pd

        groupNo  subjNo  trialNo  transNo    measNo  resp
0      0younger       0        1        1  0content     1
1      0younger       0        1        2  0content     1
2      0younger       0        1        3  0content     1
3      0younger       0        1        4  0content     1
4      0younger       0        1        5  0content     1
...         ...     ...      ...      ...       ...   ...
63355    1older      26       64        1     2both     0
63356    1older      26       64        2     2both     0
63357    1older      26       64        3     2both     0
63358    1older      26       64        4     2both     0
63359    1older      26       64        5     2both     0

[63360 rows x 6 columns]

In [7]:
# normalize the trial numbers for YAs and OAs separately and then concatenate 
resp_glmm_pd_YA = resp_glmm_pd[resp_glmm_pd['groupNo'] == '0younger'].copy()
resp_glmm_pd_YA['trialNo'] = np.log(resp_glmm_pd_YA['trialNo'])

resp_glmm_pd_OA = resp_glmm_pd[resp_glmm_pd['groupNo'] == '1older'].copy()
resp_glmm_pd_OA['trialNo'] = np.log(resp_glmm_pd_OA['trialNo'])

In [8]:
resp_glmm_pd = pd.concat([resp_glmm_pd_YA, resp_glmm_pd_OA], ignore_index=True)
resp_glmm_pd

        groupNo  subjNo   trialNo  transNo    measNo  resp
0      0younger       0  0.000000        1  0content     1
1      0younger       0  0.000000        2  0content     1
2      0younger       0  0.000000        3  0content     1
3      0younger       0  0.000000        4  0content     1
4      0younger       0  0.000000        5  0content     1
...         ...     ...       ...      ...       ...   ...
63355    1older      26  4.158883        1     2both     0
63356    1older      26  4.158883        2     2both     0
63357    1older      26  4.158883        3     2both     0
63358    1older      26  4.158883        4     2both     0
63359    1older      26  4.158883        5     2both     0

[63360 rows x 6 columns]

In [9]:
path_or_buf = data_behv + 'resp_glmm_group_exp1.csv' # save in the folder of online data
resp_glmm_pd.to_csv(path_or_buf = path_or_buf)

## Figure 2B-right panel: Comparison between the accuracy changes (acc in older minus mean of younger)

The data was originally saved in seqMemTask_v1_anal_summary.m

In [4]:
acc_change_Mat = loadmat(data_behv + 'acc_change_lmm_subj_exp1.mat') # 'acc_change_lmm_subj'
acc_lmm_change = acc_change_Mat['acc_change_lmm_subj']
acc_lmm_pd    = pd.DataFrame(acc_lmm_change) 
acc_lmm_pd

        0     1     2    3         4    5
0     1.0   0.0   1.0  0.0  0.079772  0.0
1     1.0   0.0   2.0  0.0 -0.352137  0.0
2     1.0   0.0   3.0  0.0 -0.784046  0.0
3     1.0   0.0   4.0  0.0  0.079772  0.0
4     1.0   0.0   5.0  0.0 -0.136183  0.0
...   ...   ...   ...  ...       ...  ...
5179  1.0  26.0  60.0  2.0 -1.000000  0.0
5180  1.0  26.0  61.0  2.0 -0.209459  0.0
5181  1.0  26.0  62.0  2.0 -0.736486  0.0
5182  1.0  26.0  63.0  2.0 -0.736486  0.0
5183  1.0  26.0  64.0  2.0 -1.000000  0.0

[5184 rows x 6 columns]

In [5]:
column_name = {0: 'groupNo', 1: 'subjNo', 2: 'trialNo', 3: 'measNo', 4: 'acc_change', 5: 'fullyCor'} 
acc_lmm_pd = acc_lmm_pd.rename(columns = column_name) 
acc_lmm_pd.groupNo = acc_lmm_pd.groupNo.astype('int64')
acc_lmm_pd.subjNo  = acc_lmm_pd.subjNo.astype('int64')
acc_lmm_pd.trialNo = acc_lmm_pd.trialNo.astype('int64')
acc_lmm_pd.measNo  = acc_lmm_pd.measNo.astype('int64')
acc_lmm_pd.fullyCor = acc_lmm_pd.fullyCor.astype('int64')
acc_lmm_pd

      groupNo  subjNo  trialNo  measNo  acc_change  fullyCor
0           1       0        1       0    0.079772         0
1           1       0        2       0   -0.352137         0
2           1       0        3       0   -0.784046         0
3           1       0        4       0    0.079772         0
4           1       0        5       0   -0.136183         0
...       ...     ...      ...     ...         ...       ...
5179        1      26       60       2   -1.000000         0
5180        1      26       61       2   -0.209459         0
5181        1      26       62       2   -0.736486         0
5182        1      26       63       2   -0.736486         0
5183        1      26       64       2   -1.000000         0

[5184 rows x 6 columns]

In [6]:
nGroup = 1 # older relative to younger
nMeas  = 3 # three measures: content, position and reconstruction
groupList = ['older-younger']
measList  = ['0content', '1position', '2both']
for iM in range(0, nMeas):
    acc_lmm_pd.loc[(acc_lmm_pd["measNo"] == iM), "measNo"] = measList[iM]
for iGrp in range(0, nGroup):
    acc_lmm_pd.loc[(acc_lmm_pd["groupNo"] == iGrp), "groupNo"] = groupList[iGrp]  
acc_lmm_pd

     groupNo  subjNo  trialNo    measNo  acc_change  fullyCor
0          1       0        1  0content    0.079772         0
1          1       0        2  0content   -0.352137         0
2          1       0        3  0content   -0.784046         0
3          1       0        4  0content    0.079772         0
4          1       0        5  0content   -0.136183         0
...      ...     ...      ...       ...         ...       ...
5179       1      26       60     2both   -1.000000         0
5180       1      26       61     2both   -0.209459         0
5181       1      26       62     2both   -0.736486         0
5182       1      26       63     2both   -0.736486         0
5183       1      26       64     2both   -1.000000         0

[5184 rows x 6 columns]

In [7]:
path_or_buf = data_behv + 'acc_change_lmm_subj_exp1.csv' # save in the folder of online data
acc_lmm_pd.to_csv(path_or_buf = path_or_buf)

## Fasle alarm (FA) rates (new Figure 2D and its corresponding SI in Experiment 1)

The data was originally saved in seqMemTask_BehvPaper_Figure2Exp1.m (the same data also in: seqMemTask_v1_lureEffect.m)

In [4]:
FAmat = loadmat(FBdata_folder + 'Fig2D_FA_lure_overall_YAOA_stats_Exp1.mat') # FAmat = loadmat(statSaveDir + 'FA_lure_overall_YAOA_exp1.mat') # FA_lure_overall_YAOA
FA_lmm_group = FAmat['FA_lure_overall_YAOA']
FA_lmm_pd    = pd.DataFrame(FA_lmm_group) 
FA_lmm_pd
# 5 columns
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) dimension: 0-item, 1-pos
# (5) False alarm (FA) rates due to the lure stimuli: continuous variable between 0 and 1

       0     1    2    3         4
0    0.0   0.0  0.0  0.0  0.078125
1    0.0   1.0  0.0  0.0  0.015625
2    0.0   2.0  0.0  0.0  0.015625
3    0.0   3.0  0.0  0.0  0.000000
4    0.0   4.0  0.0  0.0  0.015625
..   ...   ...  ...  ...       ...
259  1.0  22.0  1.0  1.0  0.312500
260  1.0  23.0  1.0  1.0  0.546875
261  1.0  24.0  1.0  1.0  0.796875
262  1.0  25.0  1.0  1.0  0.484375
263  1.0  26.0  1.0  1.0  0.531250

[264 rows x 5 columns]

In [5]:
column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'reportDim', 4: 'FArates'} 
FA_lmm_pd   = FA_lmm_pd.rename(columns = column_name) 
FA_lmm_pd.groupNo    = FA_lmm_pd.groupNo.astype('int64')
FA_lmm_pd.subjNo     = FA_lmm_pd.subjNo.astype('int64')
FA_lmm_pd.reportType = FA_lmm_pd.reportType.astype('int64')
FA_lmm_pd.reportDim  = FA_lmm_pd.reportDim.astype('int64')
FA_lmm_pd

     groupNo  subjNo  reportType  reportDim   FArates
0          0       0           0          0  0.078125
1          0       1           0          0  0.015625
2          0       2           0          0  0.015625
3          0       3           0          0  0.000000
4          0       4           0          0  0.015625
..       ...     ...         ...        ...       ...
259        1      22           1          1  0.312500
260        1      23           1          1  0.546875
261        1      24           1          1  0.796875
262        1      25           1          1  0.484375
263        1      26           1          1  0.531250

[264 rows x 5 columns]

In [6]:
# 5 columns
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) dimension: 0-item, 1-pos
# (5) False alarm (FA) rates due to the lure stimuli: continuous variable between 0 and 1

nGroup = 2 # YA and OA
nReps  = 2 # marginal and reconstruction report
nBrec  = 2 # 2 transition dimension: item & pos
groupList  = ['0younger', '1older']
reportList = ['0marg', '1recons']
bindDirecList = ['0Item', '1Pos']
# column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'reportDim', 4: 'FArates'} 
for iGrp in range(0, nGroup):
    FA_lmm_pd.loc[(FA_lmm_pd["groupNo"] == iGrp), "groupNo"] = groupList[iGrp] 
    
for iRep in range(0, nReps):
    FA_lmm_pd.loc[(FA_lmm_pd["reportType"] == iRep), "reportType"] = reportList[iRep]
    
for iBd in range(0, nBrec):
    FA_lmm_pd.loc[(FA_lmm_pd["reportDim"] == iBd), "reportDim"] = bindDirecList[iBd]

FA_lmm_pd

      groupNo  subjNo reportType reportDim   FArates
0    0younger       0      0marg     0Item  0.078125
1    0younger       1      0marg     0Item  0.015625
2    0younger       2      0marg     0Item  0.015625
3    0younger       3      0marg     0Item  0.000000
4    0younger       4      0marg     0Item  0.015625
..        ...     ...        ...       ...       ...
259    1older      22    1recons      1Pos  0.312500
260    1older      23    1recons      1Pos  0.546875
261    1older      24    1recons      1Pos  0.796875
262    1older      25    1recons      1Pos  0.484375
263    1older      26    1recons      1Pos  0.531250

[264 rows x 5 columns]

In [7]:
path_or_buf = FBdata_folder + 'Fig2D_FA_lure_overall_YAOA_stats_Exp1.csv' 
FA_lmm_pd.to_csv(path_or_buf = path_or_buf)

## Transition related measures (new Figure 2E and its corresponding SI in Experiment 1)

The data was originally saved in seqMemTask_BehvPaper_Figure2Exp1.m (same data was also saved in seqMemTask_v1_anal_summary.m)

In [8]:
transAccMat = loadmat(FBdata_folder + 'Fig2E_transAcc_overall_group_stats_Exp1.mat') # transAccMat = loadmat(statSaveDir + 'transAcc_overall_group_exp1.mat') # 'transAcc_overall_group'
transAcc_lmm_group = transAccMat['transAcc_overall_group']
transAcc_lmm_pd    = pd.DataFrame(transAcc_lmm_group) 
transAcc_lmm_pd
# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) transition dimension: 0-item, 1-pos
# (5) transition conditions: 0-preceding response is incorrect, 1-preceding response is correct
# (6) transtion accuracy: a value ranging from 0 to 1

       0     1    2    3    4         5
0    0.0   0.0  0.0  0.0  1.0  0.979839
1    0.0   1.0  0.0  0.0  1.0  0.996078
2    0.0   2.0  0.0  0.0  1.0  0.984127
3    0.0   3.0  0.0  0.0  1.0  0.983806
4    0.0   4.0  0.0  0.0  1.0  0.984000
..   ...   ...  ...  ...  ...       ...
523  1.0  22.0  1.0  1.0  0.0  0.317647
524  1.0  23.0  1.0  1.0  0.0  0.256250
525  1.0  24.0  1.0  1.0  0.0  0.246988
526  1.0  25.0  1.0  1.0  0.0  0.235294
527  1.0  26.0  1.0  1.0  0.0  0.246479

[528 rows x 6 columns]

In [9]:
column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'transDim', 4: 'transConds', 5: 'transAcc'} 
transAcc_lmm_pd = transAcc_lmm_pd.rename(columns = column_name) 
transAcc_lmm_pd.groupNo    = transAcc_lmm_pd.groupNo.astype('int64')
transAcc_lmm_pd.subjNo     = transAcc_lmm_pd.subjNo.astype('int64')
transAcc_lmm_pd.reportType = transAcc_lmm_pd.reportType.astype('int64')
transAcc_lmm_pd.transDim   = transAcc_lmm_pd.transDim.astype('int64')
transAcc_lmm_pd.transConds = transAcc_lmm_pd.transConds.astype('int64')
transAcc_lmm_pd

     groupNo  subjNo  reportType  transDim  transConds  transAcc
0          0       0           0         0           1  0.979839
1          0       1           0         0           1  0.996078
2          0       2           0         0           1  0.984127
3          0       3           0         0           1  0.983806
4          0       4           0         0           1  0.984000
..       ...     ...         ...       ...         ...       ...
523        1      22           1         1           0  0.317647
524        1      23           1         1           0  0.256250
525        1      24           1         1           0  0.246988
526        1      25           1         1           0  0.235294
527        1      26           1         1           0  0.246479

[528 rows x 6 columns]

In [10]:
# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) transition dimension: 0-item, 1-pos
# (5) transition conditions: 0-preceding response is incorrect, 1-preceding response is correct
# (6) transtion accuracy: a value ranging from 0 to 1

nGroup = 2 # YA and OA
nReps  = 2 # marginal and reconstruction report
nBrec  = 2 # 2 transition dimension: item & pos
nBcon  = 2 # 2 transition condition: preceding response incorrect (0) and preceding response correct (1)
groupList  = ['0younger', '1older']
reportList = ['0marg', '1recons']
bindDirecList = ['0Item', '1Pos']
bindCondsList = ['0PreWrong', '1PreCorrect']
# column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'transDim', 4: 'transConds', 5: 'transAcc'} 
for iGrp in range(0, nGroup):
    transAcc_lmm_pd.loc[(transAcc_lmm_pd["groupNo"] == iGrp), "groupNo"] = groupList[iGrp] 
    
for iRep in range(0, nReps):
    transAcc_lmm_pd.loc[(transAcc_lmm_pd["reportType"] == iRep), "reportType"] = reportList[iRep]
    
for iBd in range(0, nBrec):
    transAcc_lmm_pd.loc[(transAcc_lmm_pd["transDim"] == iBd), "transDim"] = bindDirecList[iBd]
    
for iBc in range(0, nBcon):
    transAcc_lmm_pd.loc[(transAcc_lmm_pd["transConds"] == iBc), "transConds"] = bindCondsList[iBc]

transAcc_lmm_pd

      groupNo  subjNo reportType transDim   transConds  transAcc
0    0younger       0      0marg    0Item  1PreCorrect  0.979839
1    0younger       1      0marg    0Item  1PreCorrect  0.996078
2    0younger       2      0marg    0Item  1PreCorrect  0.984127
3    0younger       3      0marg    0Item  1PreCorrect  0.983806
4    0younger       4      0marg    0Item  1PreCorrect  0.984000
..        ...     ...        ...      ...          ...       ...
523    1older      22    1recons     1Pos    0PreWrong  0.317647
524    1older      23    1recons     1Pos    0PreWrong  0.256250
525    1older      24    1recons     1Pos    0PreWrong  0.246988
526    1older      25    1recons     1Pos    0PreWrong  0.235294
527    1older      26    1recons     1Pos    0PreWrong  0.246479

[528 rows x 6 columns]

In [11]:
path_or_buf = FBdata_folder + 'Fig2E_transAcc_overall_group_stats_Exp1.csv' 
transAcc_lmm_pd.to_csv(path_or_buf = path_or_buf)

## Binding related measures (Experiment 1)

### Figure 2H and 2I: overall binding score difference in Experiment 1

The data was originally saved in seqMemTask_v1_anal_summary.m

In [12]:
bindsMat = loadmat(FBdata_folder + 'Fig2HI_binds_overall_diff_group_stats_Exp1.mat') # 'binds_overall_diff_group'
binds_lmm_group = bindsMat['binds_overall_diff_group']
binds_lmm_pd    = pd.DataFrame(binds_lmm_group) 
binds_lmm_pd
# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) binding direction: 0-(item | pos), 1-(pos | item)
# (5) binding conditions: 0-binding cost (flipped, the same direction as benefit), 1-binding benefit
# (6) binding score: a value ranging from 0 to 1

       0     1    2    3    4         5
0    0.0   0.0  0.0  0.0  0.0  0.237500
1    0.0   1.0  0.0  0.0  0.0 -0.003984
2    0.0   2.0  0.0  0.0  0.0  0.154472
3    0.0   3.0  0.0  0.0  0.0 -0.018868
4    0.0   4.0  0.0  0.0  0.0 -0.016461
..   ...   ...  ...  ...  ...       ...
523  1.0  22.0  1.0  1.0  1.0  0.268443
524  1.0  23.0  1.0  1.0  1.0  0.085714
525  1.0  24.0  1.0  1.0  1.0  0.223977
526  1.0  25.0  1.0  1.0  1.0  0.725869
527  1.0  26.0  1.0  1.0  1.0  0.199916

[528 rows x 6 columns]

In [13]:
column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'bindDirec', 4: 'bindConds', 5: 'bindScore'} 
binds_lmm_pd = binds_lmm_pd.rename(columns = column_name) 
binds_lmm_pd.groupNo    = binds_lmm_pd.groupNo.astype('int64')
binds_lmm_pd.subjNo     = binds_lmm_pd.subjNo.astype('int64')
binds_lmm_pd.reportType = binds_lmm_pd.reportType.astype('int64')
binds_lmm_pd.bindDirec  = binds_lmm_pd.bindDirec.astype('int64')
binds_lmm_pd.bindConds  = binds_lmm_pd.bindConds.astype('int64')
binds_lmm_pd

     groupNo  subjNo  reportType  bindDirec  bindConds  bindScore
0          0       0           0          0          0   0.237500
1          0       1           0          0          0  -0.003984
2          0       2           0          0          0   0.154472
3          0       3           0          0          0  -0.018868
4          0       4           0          0          0  -0.016461
..       ...     ...         ...        ...        ...        ...
523        1      22           1          1          1   0.268443
524        1      23           1          1          1   0.085714
525        1      24           1          1          1   0.223977
526        1      25           1          1          1   0.725869
527        1      26           1          1          1   0.199916

[528 rows x 6 columns]

In [14]:
# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) binding direction: 0-(item | pos), 1-(pos | item)
# (5) binding conditions: 1-the other dimension is correct, 0-the other dimension is incorrect
# (6) binding score: a value ranging from 0 to 1

nGroup = 2 # YA and OA
nReps  = 2 # marginal and reconstruction report
nBrec  = 2 # 2 binding directions: (item | pos) & (pos | item)
nBcon  = 2 # 2 binding condition: cost (0, flipped, with the same direction as benefit) and benefit (1)
groupList  = ['0younger', '1older']
reportList = ['0marg', '1recons']
bindDirecList = ['0ItemOnPos', '1PosOnItem']
bindCondsList = ['0cost', '1benefit']
for iGrp in range(0, nGroup):
    binds_lmm_pd.loc[(binds_lmm_pd["groupNo"] == iGrp), "groupNo"] = groupList[iGrp] 
    
for iRep in range(0, nReps):
    binds_lmm_pd.loc[(binds_lmm_pd["reportType"] == iRep), "reportType"] = reportList[iRep]
    
for iBd in range(0, nBrec):
    binds_lmm_pd.loc[(binds_lmm_pd["bindDirec"] == iBd), "bindDirec"] = bindDirecList[iBd]
    
for iBc in range(0, nBcon):
    binds_lmm_pd.loc[(binds_lmm_pd["bindConds"] == iBc), "bindConds"] = bindCondsList[iBc]

binds_lmm_pd

      groupNo  subjNo reportType   bindDirec bindConds  bindScore
0    0younger       0      0marg  0ItemOnPos     0cost   0.237500
1    0younger       1      0marg  0ItemOnPos     0cost  -0.003984
2    0younger       2      0marg  0ItemOnPos     0cost   0.154472
3    0younger       3      0marg  0ItemOnPos     0cost  -0.018868
4    0younger       4      0marg  0ItemOnPos     0cost  -0.016461
..        ...     ...        ...         ...       ...        ...
523    1older      22    1recons  1PosOnItem  1benefit   0.268443
524    1older      23    1recons  1PosOnItem  1benefit   0.085714
525    1older      24    1recons  1PosOnItem  1benefit   0.223977
526    1older      25    1recons  1PosOnItem  1benefit   0.725869
527    1older      26    1recons  1PosOnItem  1benefit   0.199916

[528 rows x 6 columns]

In [15]:
path_or_buf = FBdata_folder + 'Fig2HI_binds_overall_diff_group_stats_Exp1.csv' 
binds_lmm_pd.to_csv(path_or_buf = path_or_buf)

### Figure 2G and the corresponding SI: overall binding score in Experiment 1

The data was originally saved in seqMemTask_v1_anal_summary.m

In [16]:
bindsMat = loadmat(FBdata_folder + 'Fig2G_binds_overall_group_stats_Exp1.mat') # 'binds_overall_group'
binds_lmm_group = bindsMat['binds_overall_group']
binds_lmm_pd    = pd.DataFrame(binds_lmm_group) 
binds_lmm_pd
# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) binding direction: 0-(item | pos), 1-(pos | item)
# (5) binding conditions: 1-the other dimension is correct, 0-the other dimension is incorrect
# (6) binding score: a value ranging from 0 to 1

        0     1    2    3    4         5
0     0.0   0.0  0.0  0.0  1.0  0.987500
1     0.0   1.0  0.0  0.0  1.0  0.996016
2     0.0   2.0  0.0  0.0  1.0  0.987805
3     0.0   3.0  0.0  0.0  1.0  0.981132
4     0.0   4.0  0.0  0.0  1.0  0.983539
...   ...   ...  ...  ...  ...       ...
1051  1.0  22.0  1.0  1.0  0.0  0.125000
1052  1.0  23.0  1.0  1.0  0.0  0.200000
1053  1.0  24.0  1.0  1.0  0.0  0.144444
1054  1.0  25.0  1.0  1.0  0.0  0.036036
1055  1.0  26.0  1.0  1.0  0.0  0.170455

[1056 rows x 6 columns]

In [17]:
column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'bindDirec', 4: 'bindConds', 5: 'bindScore'} 
binds_lmm_pd = binds_lmm_pd.rename(columns = column_name) 
binds_lmm_pd.groupNo    = binds_lmm_pd.groupNo.astype('int64')
binds_lmm_pd.subjNo     = binds_lmm_pd.subjNo.astype('int64')
binds_lmm_pd.reportType = binds_lmm_pd.reportType.astype('int64')
binds_lmm_pd.bindDirec  = binds_lmm_pd.bindDirec.astype('int64')
binds_lmm_pd.bindConds  = binds_lmm_pd.bindConds.astype('int64')
binds_lmm_pd

      groupNo  subjNo  reportType  bindDirec  bindConds  bindScore
0           0       0           0          0          1   0.987500
1           0       1           0          0          1   0.996016
2           0       2           0          0          1   0.987805
3           0       3           0          0          1   0.981132
4           0       4           0          0          1   0.983539
...       ...     ...         ...        ...        ...        ...
1051        1      22           1          1          0   0.125000
1052        1      23           1          1          0   0.200000
1053        1      24           1          1          0   0.144444
1054        1      25           1          1          0   0.036036
1055        1      26           1          1          0   0.170455

[1056 rows x 6 columns]

In [18]:
# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) binding direction: 0-(item | pos), 1-(pos | item)
# (5) binding conditions: 1-the other dimension is correct, 0-the other dimension is incorrect
# (6) binding score: a value ranging from 0 to 1

nGroup = 2 # YA and OA
nReps  = 2 # marginal and reconstruction report
nBrec  = 2 # 2 binding directions: (item | pos) & (pos | item)
nBcon  = 2 # 2 binding condition (their difference is 'cost' or 'benefit'): other dimension is Wrong (0) or Right (1)
groupList  = ['0younger', '1older']
reportList = ['0marg', '1recons']
bindDirecList = ['0ItemOnPos', '1PosOnItem']
bindCondsList = ['0OtherW', '1OtherR']
for iGrp in range(0, nGroup):
    binds_lmm_pd.loc[(binds_lmm_pd["groupNo"] == iGrp), "groupNo"] = groupList[iGrp] 
    
for iRep in range(0, nReps):
    binds_lmm_pd.loc[(binds_lmm_pd["reportType"] == iRep), "reportType"] = reportList[iRep]
    
for iBd in range(0, nBrec):
    binds_lmm_pd.loc[(binds_lmm_pd["bindDirec"] == iBd), "bindDirec"] = bindDirecList[iBd]
    
for iBc in range(0, nBcon):
    binds_lmm_pd.loc[(binds_lmm_pd["bindConds"] == iBc), "bindConds"] = bindCondsList[iBc]

binds_lmm_pd

       groupNo  subjNo reportType   bindDirec bindConds  bindScore
0     0younger       0      0marg  0ItemOnPos   1OtherR   0.987500
1     0younger       1      0marg  0ItemOnPos   1OtherR   0.996016
2     0younger       2      0marg  0ItemOnPos   1OtherR   0.987805
3     0younger       3      0marg  0ItemOnPos   1OtherR   0.981132
4     0younger       4      0marg  0ItemOnPos   1OtherR   0.983539
...        ...     ...        ...         ...       ...        ...
1051    1older      22    1recons  1PosOnItem   0OtherW   0.125000
1052    1older      23    1recons  1PosOnItem   0OtherW   0.200000
1053    1older      24    1recons  1PosOnItem   0OtherW   0.144444
1054    1older      25    1recons  1PosOnItem   0OtherW   0.036036
1055    1older      26    1recons  1PosOnItem   0OtherW   0.170455

[1056 rows x 6 columns]

In [19]:
path_or_buf = FBdata_folder + 'Fig2G_binds_overall_group_stats_Exp1.csv' 
binds_lmm_pd.to_csv(path_or_buf = path_or_buf)

# Experiment 2: only Interleaved curriculum is relevant -- three trial organization conditions (interleaved, contentBlocked, positionBlocked)

<div class="alert alert-success">
<b>(Columns) variables</b>:
    
{0: 'groupNo', 1: 'subjNo', 2: 'trialNo', 3: 'measNo', 4: 'accuracy', 5: 'fullyCor', 6: 'order'}

groupNo: younger or older
    
measNo: content, position, and reconstruction
    
order: chronological order after the encoding stage, could be 1, 2, & 3
</div>

## Figure 2C: memory gradient

The data (choice_within_between_trials_group.mat) was originally saved in seqMemTask_BehvPaper_Figure2Exp2.m

The data contains two types of data:
(1) 3 types of retrieval in the three-retrieval trials (excluding full retrieval only trials)
(2) 3 types of retrieval in the first reporting window

(1) and (2) were partly overlapped

In [4]:
choiceMat = loadmat(FBdata_folder + 'Fig2C_choice_within_between_trials_group_stats_Exp2.mat') # 'choice_within_between_trials_group'
choice_glmm_group = choiceMat['choice_within_between_trials_group']
choice_glmm_pd    = pd.DataFrame(choice_glmm_group) 
choice_glmm_pd

# 6 columns
# (1) ageNo: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) data types: 0-3-retrieval trials, 1-reports in the 1st reporting window
# (4) 3 measures: 0-objReport, 1-locReport, 2-reconsReport
# (5) trial numbers: some trial numbers were skipped
# (6) response in each slot of the retrieval: 0-incorrect, 1-correct

       0   1  2  3   4  5
0      0   0  0  0   1  1
1      0   0  0  0   1  1
2      0   0  0  0   1  1
3      0   0  0  0   1  1
4      0   0  0  0   1  1
...   ..  .. .. ..  .. ..
48875  1  22  1  2  64  0
48876  1  22  1  2  64  0
48877  1  22  1  2  64  1
48878  1  22  1  2  64  1
48879  1  22  1  2  64  1

[48880 rows x 6 columns]

In [5]:
column_name = {0: 'ageNo', 1: 'subjNo', 2: 'dataType', 3: 'reportType', 4: 'trialNo', 5: 'resp'} 
choice_glmm_pd = choice_glmm_pd.rename(columns = column_name) 
choice_glmm_pd.ageNo      = choice_glmm_pd.ageNo.astype('int64')
choice_glmm_pd.subjNo     = choice_glmm_pd.subjNo.astype('int64')
choice_glmm_pd.dataType   = choice_glmm_pd.dataType.astype('int64')
choice_glmm_pd.reportType = choice_glmm_pd.reportType.astype('int64')
choice_glmm_pd.trialNo    = choice_glmm_pd.trialNo.astype('int64')
choice_glmm_pd.resp       = choice_glmm_pd.resp.astype('int64')
choice_glmm_pd

       ageNo  subjNo  dataType  reportType  trialNo  resp
0          0       0         0           0        1     1
1          0       0         0           0        1     1
2          0       0         0           0        1     1
3          0       0         0           0        1     1
4          0       0         0           0        1     1
...      ...     ...       ...         ...      ...   ...
48875      1      22         1           2       64     0
48876      1      22         1           2       64     0
48877      1      22         1           2       64     1
48878      1      22         1           2       64     1
48879      1      22         1           2       64     1

[48880 rows x 6 columns]

In [6]:
# 6 columns
# (1) ageNo: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) data types: 0-3-retrieval trials, 1-reports in the 1st reporting window
# (4) 3 measures: 0-objReport, 1-locReport, 2-reconsReport
# (5) trial numbers: some trial numbers were skipped
# (6) response in each slot of the retrieval: 0-incorrect, 1-correct

nAges   = 2 # YA and OA
ndataTp = 2 # 2 data types: within-trial (3-retrieval trials) and between-trial (data in the 1st reporting window)
nReps   = 3 # 3 measures: object, location and reconstruction

ageList    = ['0younger', '1older']
dataTpList = ['0withinTrl', '1betweenTrl']
measList   = ['0content', '1position', '2both']

for iAg in range(0, nAges):
    choice_glmm_pd.loc[(choice_glmm_pd["ageNo"] == iAg), "ageNo"] = ageList[iAg] 
    
for iDt in range(0, ndataTp):
    choice_glmm_pd.loc[(choice_glmm_pd["dataType"] == iDt), "dataType"] = dataTpList[iDt]
    
for iRep in range(0, nReps):
    choice_glmm_pd.loc[(choice_glmm_pd["reportType"] == iRep), "reportType"] = measList[iRep]

choice_glmm_pd

          ageNo  subjNo     dataType reportType  trialNo  resp
0      0younger       0   0withinTrl   0content        1     1
1      0younger       0   0withinTrl   0content        1     1
2      0younger       0   0withinTrl   0content        1     1
3      0younger       0   0withinTrl   0content        1     1
4      0younger       0   0withinTrl   0content        1     1
...         ...     ...          ...        ...      ...   ...
48875    1older      22  1betweenTrl      2both       64     0
48876    1older      22  1betweenTrl      2both       64     0
48877    1older      22  1betweenTrl      2both       64     1
48878    1older      22  1betweenTrl      2both       64     1
48879    1older      22  1betweenTrl      2both       64     1

[48880 rows x 6 columns]

In [7]:
path_or_buf = FBdata_folder + 'Fig2C_choice_within_between_trials_group_stats_Exp2.csv' 
choice_glmm_pd.to_csv(path_or_buf = path_or_buf)

## Figure 2C: Decline change percentage (older minus younger) 

The data was originally saved in seqMemTask_BehvPaper_Figure2Exp2.m

(1) Fig2C_acc_change_conds_group_stats_Exp2.mat: memory drop based on all trials
(2) Fig2C_acc_change_conds_threeRetr_group_stats_Exp2.mat: memory drop based on three-retrieval trials
(3) Fig2C_acc_change_conds_firstWin_group_stats_Exp2.mat: memory drop based on retrievals in the first reporting window

In [20]:
dataFlg = 2
if dataFlg == 0:   # all trials
    acc_change_mat = loadmat(FBdata_folder + 'Fig2C_acc_change_conds_group_stats_Exp2.mat') # 'acc_change_conds_group'
    acc_lmm_group  = acc_change_mat['acc_change_conds_group']
    
elif dataFlg == 1: # three-retrieval trials
    acc_change_mat = loadmat(FBdata_folder + 'Fig2C_acc_change_conds_threeRetr_group_stats_Exp2.mat') # 'acc_change_conds_threeRetr_group'
    acc_lmm_group  = acc_change_mat['acc_change_conds_threeRetr_group']
    
elif dataFlg == 2: # retrievals in the first reporting window
    acc_change_mat = loadmat(FBdata_folder + 'Fig2C_acc_change_conds_firstWin_group_stats_Exp2.mat') # 'acc_change_conds_firstWin_group'
    acc_lmm_group  = acc_change_mat['acc_change_conds_firstWin_group']

In [21]:
acc_lmm_pd = pd.DataFrame(acc_lmm_group) 
acc_lmm_pd

# 6 columns
# (1) ageNo: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) trial number: some of the trial numbers were skipped in the latter two conditions
# (4) 3 measures: 0-objReport, 1-locReport, 2-reconsReport
# (5) accuracy change (OA relative to YA): continuous variable
# (6) reporting window (after encoding stage) labels: 1-first report, 2-second report, 3-third report

        0     1     2    3         4    5
0     1.0   0.0   2.0  0.0  0.118856  1.0
1     1.0   0.0   4.0  0.0  0.118856  1.0
2     1.0   0.0   6.0  0.0  0.118856  1.0
3     1.0   0.0  12.0  0.0  0.118856  1.0
4     1.0   0.0  13.0  0.0  0.118856  1.0
...   ...   ...   ...  ...       ...  ...
1467  1.0  22.0  42.0  2.0  0.068894  1.0
1468  1.0  22.0  55.0  2.0 -0.198330  1.0
1469  1.0  22.0  56.0  2.0 -0.465553  1.0
1470  1.0  22.0  57.0  2.0 -0.198330  1.0
1471  1.0  22.0  64.0  2.0 -0.198330  1.0

[1472 rows x 6 columns]

In [22]:
column_name = {0: 'ageNo', 1: 'subjNo', 2: 'trialNo', 3: 'measNo', 4: 'accuracy_change', 5: 'order'} 
acc_lmm_pd = acc_lmm_pd.rename(columns = column_name) 
acc_lmm_pd.ageNo   = acc_lmm_pd.ageNo.astype('int64')
acc_lmm_pd.subjNo  = acc_lmm_pd.subjNo.astype('int64')
acc_lmm_pd.trialNo = acc_lmm_pd.trialNo.astype('int64')
acc_lmm_pd.measNo  = acc_lmm_pd.measNo.astype('int64')
acc_lmm_pd.order   = acc_lmm_pd.order.astype('int64')
acc_lmm_pd

      ageNo  subjNo  trialNo  measNo  accuracy_change  order
0         1       0        2       0         0.118856      1
1         1       0        4       0         0.118856      1
2         1       0        6       0         0.118856      1
3         1       0       12       0         0.118856      1
4         1       0       13       0         0.118856      1
...     ...     ...      ...     ...              ...    ...
1467      1      22       42       2         0.068894      1
1468      1      22       55       2        -0.198330      1
1469      1      22       56       2        -0.465553      1
1470      1      22       57       2        -0.198330      1
1471      1      22       64       2        -0.198330      1

[1472 rows x 6 columns]

In [23]:
# 6 columns
# (1) ageNo: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) trial number: some of the trial numbers were skipped in the latter two conditions
# (4) 3 measures: 0-objReport, 1-locReport, 2-reconsReport
# (5) accuracy change (OA relative to YA): continuous variable
# (6) reporting window (after encoding stage) labels: 1-first report, 2-second report, 3-third report

nAges  = 2 # YA and OA
nMeas  = 3 # object/location/full retrieval
nOrder = 3 # 1st/2nd/3rd reporting window

ageList   = ['0younger', '1older']
measList  = ['0content', '1position', '2both']
orderList = ['0first', '1second', '2third']

for iAg in range(0, nAges):
    acc_lmm_pd.loc[(acc_lmm_pd["ageNo"] == iAg), "ageNo"] = ageList[iAg] 
    
for iM in range(0, nMeas):
    acc_lmm_pd.loc[(acc_lmm_pd["measNo"] == iM), "measNo"] = measList[iM]
 
for iOrd in range(0, nOrder):
    acc_lmm_pd.loc[(acc_lmm_pd["order"] == (iOrd + 1)), "order"] = orderList[iOrd]

In [24]:
acc_lmm_pd

       ageNo  subjNo  trialNo    measNo  accuracy_change   order
0     1older       0        2  0content         0.118856  0first
1     1older       0        4  0content         0.118856  0first
2     1older       0        6  0content         0.118856  0first
3     1older       0       12  0content         0.118856  0first
4     1older       0       13  0content         0.118856  0first
...      ...     ...      ...       ...              ...     ...
1467  1older      22       42     2both         0.068894  0first
1468  1older      22       55     2both        -0.198330  0first
1469  1older      22       56     2both        -0.465553  0first
1470  1older      22       57     2both        -0.198330  0first
1471  1older      22       64     2both        -0.198330  0first

[1472 rows x 6 columns]

In [25]:
if dataFlg == 0:   # all trials
    path_or_buf = FBdata_folder + 'Fig2C_acc_change_conds_group_stats_Exp2.csv'
    
elif dataFlg == 1: # three-retrieval trials
    path_or_buf = FBdata_folder + 'Fig2C_acc_change_conds_threeRetr_group_stats_Exp2.csv'
    
elif dataFlg == 2: # retrievals in the first reporting window
    path_or_buf = FBdata_folder + 'Fig2C_acc_change_conds_firstWin_group_stats_Exp2.csv'

acc_lmm_pd.to_csv(path_or_buf = path_or_buf)

## Figure 2D: False alarm rates

The data was saved in seqMemTask_BehvPaper_Figure2Exp2.m (the same data was also saved in seqMemTask_v2_lureEffect.m)

In [4]:
FAmat = loadmat(FBdata_folder + 'Fig2D_FA_lure_overall_YAOA_stats_Exp2.mat') # FA_lure_overall_YAOA
FA_lmm_group = FAmat['FA_lure_overall_YAOA']
FA_lmm_pd    = pd.DataFrame(FA_lmm_group) 
FA_lmm_pd
# 5 columns
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) dimension: 0-item, 1-pos
# (5) False alarm (FA) rates due to the lure stimuli: continuous variable between 0 and 1

       0     1    2    3         4
0    0.0   0.0  0.0  0.0  0.062500
1    0.0   1.0  0.0  0.0  0.000000
2    0.0   2.0  0.0  0.0  0.020833
3    0.0   3.0  0.0  0.0  0.000000
4    0.0   4.0  0.0  0.0  0.041667
..   ...   ...  ...  ...       ...
183  1.0  18.0  1.0  1.0  0.781250
184  1.0  19.0  1.0  1.0  0.609375
185  1.0  20.0  1.0  1.0  0.031250
186  1.0  21.0  1.0  1.0  0.656250
187  1.0  22.0  1.0  1.0  0.578125

[188 rows x 5 columns]

In [5]:
column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'reportDim', 4: 'FArates'} 
FA_lmm_pd   = FA_lmm_pd.rename(columns = column_name) 
FA_lmm_pd.groupNo    = FA_lmm_pd.groupNo.astype('int64')
FA_lmm_pd.subjNo     = FA_lmm_pd.subjNo.astype('int64')
FA_lmm_pd.reportType = FA_lmm_pd.reportType.astype('int64')
FA_lmm_pd.reportDim  = FA_lmm_pd.reportDim.astype('int64')
FA_lmm_pd

     groupNo  subjNo  reportType  reportDim   FArates
0          0       0           0          0  0.062500
1          0       1           0          0  0.000000
2          0       2           0          0  0.020833
3          0       3           0          0  0.000000
4          0       4           0          0  0.041667
..       ...     ...         ...        ...       ...
183        1      18           1          1  0.781250
184        1      19           1          1  0.609375
185        1      20           1          1  0.031250
186        1      21           1          1  0.656250
187        1      22           1          1  0.578125

[188 rows x 5 columns]

In [6]:
# 5 columns
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) dimension: 0-item, 1-pos
# (5) False alarm (FA) rates due to the lure stimuli: continuous variable between 0 and 1

nGroup = 2 # YA and OA
nReps  = 2 # marginal and reconstruction report
nBrec  = 2 # 2 transition dimension: item & pos
groupList  = ['0younger', '1older']
reportList = ['0marg', '1recons']
bindDirecList = ['0Item', '1Pos']
# column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'reportDim', 4: 'FArates'} 
for iGrp in range(0, nGroup):
    FA_lmm_pd.loc[(FA_lmm_pd["groupNo"] == iGrp), "groupNo"] = groupList[iGrp] 
    
for iRep in range(0, nReps):
    FA_lmm_pd.loc[(FA_lmm_pd["reportType"] == iRep), "reportType"] = reportList[iRep]
    
for iBd in range(0, nBrec):
    FA_lmm_pd.loc[(FA_lmm_pd["reportDim"] == iBd), "reportDim"] = bindDirecList[iBd]

FA_lmm_pd

      groupNo  subjNo reportType reportDim   FArates
0    0younger       0      0marg     0Item  0.062500
1    0younger       1      0marg     0Item  0.000000
2    0younger       2      0marg     0Item  0.020833
3    0younger       3      0marg     0Item  0.000000
4    0younger       4      0marg     0Item  0.041667
..        ...     ...        ...       ...       ...
183    1older      18    1recons      1Pos  0.781250
184    1older      19    1recons      1Pos  0.609375
185    1older      20    1recons      1Pos  0.031250
186    1older      21    1recons      1Pos  0.656250
187    1older      22    1recons      1Pos  0.578125

[188 rows x 5 columns]

In [7]:
path_or_buf = FBdata_folder + 'Fig2D_FA_lure_overall_YAOA_stats_Exp2.csv' 
FA_lmm_pd.to_csv(path_or_buf = path_or_buf)

## Figure 2E: transition accuracy

The original data was saved in seqMemTask_BehvPaper_Figure2Exp2.m

In [8]:
transAccMat = loadmat(FBdata_folder + 'Fig2E_transAcc_overall_group_stats_Exp2.mat') # transAccMat = loadmat(statSaveDir + 'transAcc_overall_group_exp1.mat') # 'transAcc_overall_group'
transAcc_lmm_group = transAccMat['transAcc_overall_group']
transAcc_lmm_pd    = pd.DataFrame(transAcc_lmm_group) 
transAcc_lmm_pd
# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) transition dimension: 0-item, 1-pos
# (5) transition conditions: 0-preceding response is incorrect, 1-preceding response is correct
# (6) transtion accuracy: a value ranging from 0 to 1

       0     1    2    3    4         5
0    0.0   0.0  0.0  0.0  1.0  0.978836
1    0.0   1.0  0.0  0.0  1.0  1.000000
2    0.0   2.0  0.0  0.0  1.0  0.944751
3    0.0   3.0  0.0  0.0  1.0  0.994737
4    0.0   4.0  0.0  0.0  1.0  0.983333
..   ...   ...  ...  ...  ...       ...
371  1.0  18.0  1.0  1.0  0.0  0.385135
372  1.0  19.0  1.0  1.0  0.0  0.335260
373  1.0  20.0  1.0  1.0  0.0  0.421053
374  1.0  21.0  1.0  1.0  0.0  0.364780
375  1.0  22.0  1.0  1.0  0.0  0.248408

[376 rows x 6 columns]

In [9]:
column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'transDim', 4: 'transConds', 5: 'transAcc'} 
transAcc_lmm_pd = transAcc_lmm_pd.rename(columns = column_name) 
transAcc_lmm_pd.groupNo    = transAcc_lmm_pd.groupNo.astype('int64')
transAcc_lmm_pd.subjNo     = transAcc_lmm_pd.subjNo.astype('int64')
transAcc_lmm_pd.reportType = transAcc_lmm_pd.reportType.astype('int64')
transAcc_lmm_pd.transDim   = transAcc_lmm_pd.transDim.astype('int64')
transAcc_lmm_pd.transConds = transAcc_lmm_pd.transConds.astype('int64')
transAcc_lmm_pd

     groupNo  subjNo  reportType  transDim  transConds  transAcc
0          0       0           0         0           1  0.978836
1          0       1           0         0           1  1.000000
2          0       2           0         0           1  0.944751
3          0       3           0         0           1  0.994737
4          0       4           0         0           1  0.983333
..       ...     ...         ...       ...         ...       ...
371        1      18           1         1           0  0.385135
372        1      19           1         1           0  0.335260
373        1      20           1         1           0  0.421053
374        1      21           1         1           0  0.364780
375        1      22           1         1           0  0.248408

[376 rows x 6 columns]

In [10]:
# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) transition dimension: 0-item, 1-pos
# (5) transition conditions: 0-preceding response is incorrect, 1-preceding response is correct
# (6) transtion accuracy: a value ranging from 0 to 1

nGroup = 2 # YA and OA
nReps  = 2 # marginal and reconstruction report
nBrec  = 2 # 2 transition dimension: item & pos
nBcon  = 2 # 2 transition condition: preceding response incorrect (0) and preceding response correct (1)
groupList  = ['0younger', '1older']
reportList = ['0marg', '1recons']
bindDirecList = ['0Item', '1Pos']
bindCondsList = ['0PreWrong', '1PreCorrect']
# column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'transDim', 4: 'transConds', 5: 'transAcc'} 
for iGrp in range(0, nGroup):
    transAcc_lmm_pd.loc[(transAcc_lmm_pd["groupNo"] == iGrp), "groupNo"] = groupList[iGrp] 
    
for iRep in range(0, nReps):
    transAcc_lmm_pd.loc[(transAcc_lmm_pd["reportType"] == iRep), "reportType"] = reportList[iRep]
    
for iBd in range(0, nBrec):
    transAcc_lmm_pd.loc[(transAcc_lmm_pd["transDim"] == iBd), "transDim"] = bindDirecList[iBd]
    
for iBc in range(0, nBcon):
    transAcc_lmm_pd.loc[(transAcc_lmm_pd["transConds"] == iBc), "transConds"] = bindCondsList[iBc]

transAcc_lmm_pd

      groupNo  subjNo reportType transDim   transConds  transAcc
0    0younger       0      0marg    0Item  1PreCorrect  0.978836
1    0younger       1      0marg    0Item  1PreCorrect  1.000000
2    0younger       2      0marg    0Item  1PreCorrect  0.944751
3    0younger       3      0marg    0Item  1PreCorrect  0.994737
4    0younger       4      0marg    0Item  1PreCorrect  0.983333
..        ...     ...        ...      ...          ...       ...
371    1older      18    1recons     1Pos    0PreWrong  0.385135
372    1older      19    1recons     1Pos    0PreWrong  0.335260
373    1older      20    1recons     1Pos    0PreWrong  0.421053
374    1older      21    1recons     1Pos    0PreWrong  0.364780
375    1older      22    1recons     1Pos    0PreWrong  0.248408

[376 rows x 6 columns]

In [11]:
path_or_buf = FBdata_folder + 'Fig2E_transAcc_overall_group_stats_Exp2.csv' 
transAcc_lmm_pd.to_csv(path_or_buf = path_or_buf)

## Figure 2G: Binding related measures (conditional probability)

The data was saved in seqMemTask_BehvPaper_Figure2Exp2.m

In [12]:
bindsMat = loadmat(FBdata_folder + 'Fig2G_binds_overall_group_stats_Exp2.mat') # 'binds_overall_group'
binds_lmm_group = bindsMat['binds_overall_group']
binds_lmm_pd    = pd.DataFrame(binds_lmm_group) 
binds_lmm_pd
# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) binding direction: 0-(item | pos), 1-(pos | item)
# (5) binding conditions: 1-the other dimension is correct, 0-the other dimension is incorrect
# (6) binding score: a value ranging from 0 to 1

       0     1    2    3    4         5
0    0.0   0.0  0.0  0.0  1.0  0.977654
1    0.0   1.0  0.0  0.0  1.0  1.000000
2    0.0   2.0  0.0  0.0  1.0  0.947674
3    0.0   3.0  0.0  0.0  1.0  0.994652
4    0.0   4.0  0.0  0.0  1.0  0.983051
..   ...   ...  ...  ...  ...       ...
747  1.0  18.0  1.0  1.0  0.0  0.211268
748  1.0  19.0  1.0  1.0  0.0  0.227848
749  1.0  20.0  1.0  1.0  0.0  0.125000
750  1.0  21.0  1.0  1.0  0.0  0.157895
751  1.0  22.0  1.0  1.0  0.0  0.176471

[752 rows x 6 columns]

In [13]:
column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'bindDirec', 4: 'bindConds', 5: 'bindScore'} 
binds_lmm_pd = binds_lmm_pd.rename(columns = column_name) 
binds_lmm_pd.groupNo    = binds_lmm_pd.groupNo.astype('int64')
binds_lmm_pd.subjNo     = binds_lmm_pd.subjNo.astype('int64')
binds_lmm_pd.reportType = binds_lmm_pd.reportType.astype('int64')
binds_lmm_pd.bindDirec  = binds_lmm_pd.bindDirec.astype('int64')
binds_lmm_pd.bindConds  = binds_lmm_pd.bindConds.astype('int64')
binds_lmm_pd

# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) binding direction: 0-(item | pos), 1-(pos | item)
# (5) binding conditions: 1-the other dimension is correct, 0-the other dimension is incorrect
# (6) binding score: a value ranging from 0 to 1

     groupNo  subjNo  reportType  bindDirec  bindConds  bindScore
0          0       0           0          0          1   0.977654
1          0       1           0          0          1   1.000000
2          0       2           0          0          1   0.947674
3          0       3           0          0          1   0.994652
4          0       4           0          0          1   0.983051
..       ...     ...         ...        ...        ...        ...
747        1      18           1          1          0   0.211268
748        1      19           1          1          0   0.227848
749        1      20           1          1          0   0.125000
750        1      21           1          1          0   0.157895
751        1      22           1          1          0   0.176471

[752 rows x 6 columns]

In [14]:
nGroup = 2 # YA and OA
nReps  = 2 # marginal and reconstruction report
nBrec  = 2 # 2 binding directions: (item | pos) & (pos | item)
nBcon  = 2 # 2 binding condition (their difference is 'cost' or 'benefit'): other dimension is Wrong (0) or Right (1)
groupList  = ['0younger', '1older']
reportList = ['0marg', '1recons']
bindDirecList = ['0ItemOnPos', '1PosOnItem']
bindCondsList = ['0OtherW', '1OtherR']
for iGrp in range(0, nGroup):
    binds_lmm_pd.loc[(binds_lmm_pd["groupNo"] == iGrp), "groupNo"] = groupList[iGrp] 
    
for iRep in range(0, nReps):
    binds_lmm_pd.loc[(binds_lmm_pd["reportType"] == iRep), "reportType"] = reportList[iRep]
    
for iBd in range(0, nBrec):
    binds_lmm_pd.loc[(binds_lmm_pd["bindDirec"] == iBd), "bindDirec"] = bindDirecList[iBd]
    
for iBc in range(0, nBcon):
    binds_lmm_pd.loc[(binds_lmm_pd["bindConds"] == iBc), "bindConds"] = bindCondsList[iBc]

binds_lmm_pd

      groupNo  subjNo reportType   bindDirec bindConds  bindScore
0    0younger       0      0marg  0ItemOnPos   1OtherR   0.977654
1    0younger       1      0marg  0ItemOnPos   1OtherR   1.000000
2    0younger       2      0marg  0ItemOnPos   1OtherR   0.947674
3    0younger       3      0marg  0ItemOnPos   1OtherR   0.994652
4    0younger       4      0marg  0ItemOnPos   1OtherR   0.983051
..        ...     ...        ...         ...       ...        ...
747    1older      18    1recons  1PosOnItem   0OtherW   0.211268
748    1older      19    1recons  1PosOnItem   0OtherW   0.227848
749    1older      20    1recons  1PosOnItem   0OtherW   0.125000
750    1older      21    1recons  1PosOnItem   0OtherW   0.157895
751    1older      22    1recons  1PosOnItem   0OtherW   0.176471

[752 rows x 6 columns]

In [15]:
path_or_buf = FBdata_folder + 'Fig2G_binds_overall_group_stats_Exp2.csv' 
binds_lmm_pd.to_csv(path_or_buf = path_or_buf)

## Figure 2HI: Binding related measures

The original data was saved in seqMemTask_BehvPaper_Figure2Exp2.m

In [16]:
bindsMat = loadmat(FBdata_folder + 'Fig2HI_binds_overall_diff_group_stats_Exp2.mat') # 'binds_overall_diff_group'
binds_lmm_group = bindsMat['binds_overall_diff_group']
binds_lmm_pd    = pd.DataFrame(binds_lmm_group) 
binds_lmm_pd
# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) binding direction: 0-(item | pos), 1-(pos | item)
# (5) binding conditions: 0-binding cost (flipped, the same direction as benefit), 1-binding benefit
# (6) binding score: a value ranging from 0 to 1

       0     1    2    3    4         5
0    0.0   0.0  0.0  0.0  0.0 -0.022346
1    0.0   1.0  0.0  0.0  0.0  0.000000
2    0.0   2.0  0.0  0.0  0.0  0.058786
3    0.0   3.0  0.0  0.0  0.0 -0.005348
4    0.0   4.0  0.0  0.0  0.0 -0.016949
..   ...   ...  ...  ...  ...       ...
371  1.0  18.0  1.0  1.0  1.0  0.334187
372  1.0  19.0  1.0  1.0  1.0  0.197684
373  1.0  20.0  1.0  1.0  1.0  0.511364
374  1.0  21.0  1.0  1.0  1.0  0.322497
375  1.0  22.0  1.0  1.0  1.0  0.080672

[376 rows x 6 columns]

In [17]:
column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'bindDirec', 4: 'bindConds', 5: 'bindScore'} 
binds_lmm_pd = binds_lmm_pd.rename(columns = column_name) 
binds_lmm_pd.groupNo    = binds_lmm_pd.groupNo.astype('int64')
binds_lmm_pd.subjNo     = binds_lmm_pd.subjNo.astype('int64')
binds_lmm_pd.reportType = binds_lmm_pd.reportType.astype('int64')
binds_lmm_pd.bindDirec  = binds_lmm_pd.bindDirec.astype('int64')
binds_lmm_pd.bindConds  = binds_lmm_pd.bindConds.astype('int64')
binds_lmm_pd

     groupNo  subjNo  reportType  bindDirec  bindConds  bindScore
0          0       0           0          0          0  -0.022346
1          0       1           0          0          0   0.000000
2          0       2           0          0          0   0.058786
3          0       3           0          0          0  -0.005348
4          0       4           0          0          0  -0.016949
..       ...     ...         ...        ...        ...        ...
371        1      18           1          1          1   0.334187
372        1      19           1          1          1   0.197684
373        1      20           1          1          1   0.511364
374        1      21           1          1          1   0.322497
375        1      22           1          1          1   0.080672

[376 rows x 6 columns]

In [18]:
# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) binding direction: 0-(item | pos), 1-(pos | item)
# (5) binding conditions: 1-the other dimension is correct, 0-the other dimension is incorrect
# (6) binding score: a value ranging from 0 to 1

nGroup = 2 # YA and OA
nReps  = 2 # marginal and reconstruction report
nBrec  = 2 # 2 binding directions: (item | pos) & (pos | item)
nBcon  = 2 # 2 binding condition: cost (0, flipped, with the same direction as benefit) and benefit (1)
groupList  = ['0younger', '1older']
reportList = ['0marg', '1recons']
bindDirecList = ['0ItemOnPos', '1PosOnItem']
bindCondsList = ['0cost', '1benefit']
for iGrp in range(0, nGroup):
    binds_lmm_pd.loc[(binds_lmm_pd["groupNo"] == iGrp), "groupNo"] = groupList[iGrp] 
    
for iRep in range(0, nReps):
    binds_lmm_pd.loc[(binds_lmm_pd["reportType"] == iRep), "reportType"] = reportList[iRep]
    
for iBd in range(0, nBrec):
    binds_lmm_pd.loc[(binds_lmm_pd["bindDirec"] == iBd), "bindDirec"] = bindDirecList[iBd]
    
for iBc in range(0, nBcon):
    binds_lmm_pd.loc[(binds_lmm_pd["bindConds"] == iBc), "bindConds"] = bindCondsList[iBc]

binds_lmm_pd

      groupNo  subjNo reportType   bindDirec bindConds  bindScore
0    0younger       0      0marg  0ItemOnPos     0cost  -0.022346
1    0younger       1      0marg  0ItemOnPos     0cost   0.000000
2    0younger       2      0marg  0ItemOnPos     0cost   0.058786
3    0younger       3      0marg  0ItemOnPos     0cost  -0.005348
4    0younger       4      0marg  0ItemOnPos     0cost  -0.016949
..        ...     ...        ...         ...       ...        ...
371    1older      18    1recons  1PosOnItem  1benefit   0.334187
372    1older      19    1recons  1PosOnItem  1benefit   0.197684
373    1older      20    1recons  1PosOnItem  1benefit   0.511364
374    1older      21    1recons  1PosOnItem  1benefit   0.322497
375    1older      22    1recons  1PosOnItem  1benefit   0.080672

[376 rows x 6 columns]

In [19]:
path_or_buf = FBdata_folder + 'Fig2HI_binds_overall_diff_group_stats_Exp2.csv' 
binds_lmm_pd.to_csv(path_or_buf = path_or_buf)

# Merge the data from Experiment 1 and Experiment 2 for Figures 2E, 2GHI

<div class="alert alert-success">
<b>Subjects</b>:

Exp1: N_{YA} = 39, N_{OA} = 27

Exp2: N_{YA} = 24, N_{OA} = 23

</div>

## Figure 2D (Exp1 + Exp2): False alarm rate

In [4]:
FAmat = loadmat(FBdata_folder + 'Fig2D_FA_lure_overall_YAOA_stats_Exp12.mat') # FA_lure_overall_YAOA
FA_lmm_group = FAmat['FA_lure_overall_YAOA']
FA_lmm_pd    = pd.DataFrame(FA_lmm_group) 
FA_lmm_pd
# 5 columns
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) dimension: 0-item, 1-pos
# (5) False alarm (FA) rates due to the lure stimuli: continuous variable between 0 and 1

       0     1    2    3         4
0    0.0   0.0  0.0  0.0  0.078125
1    0.0   1.0  0.0  0.0  0.015625
2    0.0   2.0  0.0  0.0  0.015625
3    0.0   3.0  0.0  0.0  0.000000
4    0.0   4.0  0.0  0.0  0.015625
..   ...   ...  ...  ...       ...
447  1.0  45.0  1.0  1.0  0.781250
448  1.0  46.0  1.0  1.0  0.609375
449  1.0  47.0  1.0  1.0  0.031250
450  1.0  48.0  1.0  1.0  0.656250
451  1.0  49.0  1.0  1.0  0.578125

[452 rows x 5 columns]

In [5]:
column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'reportDim', 4: 'FArates'} 
FA_lmm_pd   = FA_lmm_pd.rename(columns = column_name) 
FA_lmm_pd.groupNo    = FA_lmm_pd.groupNo.astype('int64')
FA_lmm_pd.subjNo     = FA_lmm_pd.subjNo.astype('int64')
FA_lmm_pd.reportType = FA_lmm_pd.reportType.astype('int64')
FA_lmm_pd.reportDim  = FA_lmm_pd.reportDim.astype('int64')
FA_lmm_pd

     groupNo  subjNo  reportType  reportDim   FArates
0          0       0           0          0  0.078125
1          0       1           0          0  0.015625
2          0       2           0          0  0.015625
3          0       3           0          0  0.000000
4          0       4           0          0  0.015625
..       ...     ...         ...        ...       ...
447        1      45           1          1  0.781250
448        1      46           1          1  0.609375
449        1      47           1          1  0.031250
450        1      48           1          1  0.656250
451        1      49           1          1  0.578125

[452 rows x 5 columns]

In [6]:
# 5 columns
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) dimension: 0-item, 1-pos
# (5) False alarm (FA) rates due to the lure stimuli: continuous variable between 0 and 1

nGroup = 2 # YA and OA
nReps  = 2 # marginal and reconstruction report
nBrec  = 2 # 2 transition dimension: item & pos
groupList  = ['0younger', '1older']
reportList = ['0marg', '1recons']
bindDirecList = ['0Item', '1Pos']
# column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'reportDim', 4: 'FArates'} 
for iGrp in range(0, nGroup):
    FA_lmm_pd.loc[(FA_lmm_pd["groupNo"] == iGrp), "groupNo"] = groupList[iGrp] 
    
for iRep in range(0, nReps):
    FA_lmm_pd.loc[(FA_lmm_pd["reportType"] == iRep), "reportType"] = reportList[iRep]
    
for iBd in range(0, nBrec):
    FA_lmm_pd.loc[(FA_lmm_pd["reportDim"] == iBd), "reportDim"] = bindDirecList[iBd]

FA_lmm_pd

      groupNo  subjNo reportType reportDim   FArates
0    0younger       0      0marg     0Item  0.078125
1    0younger       1      0marg     0Item  0.015625
2    0younger       2      0marg     0Item  0.015625
3    0younger       3      0marg     0Item  0.000000
4    0younger       4      0marg     0Item  0.015625
..        ...     ...        ...       ...       ...
447    1older      45    1recons      1Pos  0.781250
448    1older      46    1recons      1Pos  0.609375
449    1older      47    1recons      1Pos  0.031250
450    1older      48    1recons      1Pos  0.656250
451    1older      49    1recons      1Pos  0.578125

[452 rows x 5 columns]

In [8]:
path_or_buf = FBdata_folder + 'Fig2D_FA_lure_overall_YAOA_stats_Exp12.csv' 
FA_lmm_pd.to_csv(path_or_buf = path_or_buf)

## Figure 2E (Exp1 + Exp2): Transition accuracy

In [9]:
transAccMat = loadmat(FBdata_folder + 'Fig2E_transAcc_overall_group_stats_Exp12.mat') # transAccMat = loadmat(statSaveDir + 'transAcc_overall_group_exp1.mat') # 'transAcc_overall_group'
transAcc_lmm_group = transAccMat['transAcc_overall_group']
transAcc_lmm_pd    = pd.DataFrame(transAcc_lmm_group) 
transAcc_lmm_pd
# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) transition dimension: 0-item, 1-pos
# (5) transition conditions: 0-preceding response is incorrect, 1-preceding response is correct
# (6) transtion accuracy: a value ranging from 0 to 1

       0     1    2    3    4         5
0    0.0   0.0  0.0  0.0  1.0  0.979839
1    0.0   1.0  0.0  0.0  1.0  0.996078
2    0.0   2.0  0.0  0.0  1.0  0.984127
3    0.0   3.0  0.0  0.0  1.0  0.983806
4    0.0   4.0  0.0  0.0  1.0  0.984000
..   ...   ...  ...  ...  ...       ...
899  1.0  45.0  1.0  1.0  0.0  0.385135
900  1.0  46.0  1.0  1.0  0.0  0.335260
901  1.0  47.0  1.0  1.0  0.0  0.421053
902  1.0  48.0  1.0  1.0  0.0  0.364780
903  1.0  49.0  1.0  1.0  0.0  0.248408

[904 rows x 6 columns]

In [10]:
column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'transDim', 4: 'transConds', 5: 'transAcc'} 
transAcc_lmm_pd = transAcc_lmm_pd.rename(columns = column_name) 
transAcc_lmm_pd.groupNo    = transAcc_lmm_pd.groupNo.astype('int64')
transAcc_lmm_pd.subjNo     = transAcc_lmm_pd.subjNo.astype('int64')
transAcc_lmm_pd.reportType = transAcc_lmm_pd.reportType.astype('int64')
transAcc_lmm_pd.transDim   = transAcc_lmm_pd.transDim.astype('int64')
transAcc_lmm_pd.transConds = transAcc_lmm_pd.transConds.astype('int64')
transAcc_lmm_pd

     groupNo  subjNo  reportType  transDim  transConds  transAcc
0          0       0           0         0           1  0.979839
1          0       1           0         0           1  0.996078
2          0       2           0         0           1  0.984127
3          0       3           0         0           1  0.983806
4          0       4           0         0           1  0.984000
..       ...     ...         ...       ...         ...       ...
899        1      45           1         1           0  0.385135
900        1      46           1         1           0  0.335260
901        1      47           1         1           0  0.421053
902        1      48           1         1           0  0.364780
903        1      49           1         1           0  0.248408

[904 rows x 6 columns]

In [11]:
# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) transition dimension: 0-item, 1-pos
# (5) transition conditions: 0-preceding response is incorrect, 1-preceding response is correct
# (6) transtion accuracy: a value ranging from 0 to 1

nGroup = 2 # YA and OA
nReps  = 2 # marginal and reconstruction report
nBrec  = 2 # 2 transition dimension: item & pos
nBcon  = 2 # 2 transition condition: preceding response incorrect (0) and preceding response correct (1)
groupList  = ['0younger', '1older']
reportList = ['0marg', '1recons']
bindDirecList = ['0Item', '1Pos']
bindCondsList = ['0PreWrong', '1PreCorrect']
# column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'transDim', 4: 'transConds', 5: 'transAcc'} 
for iGrp in range(0, nGroup):
    transAcc_lmm_pd.loc[(transAcc_lmm_pd["groupNo"] == iGrp), "groupNo"] = groupList[iGrp] 
    
for iRep in range(0, nReps):
    transAcc_lmm_pd.loc[(transAcc_lmm_pd["reportType"] == iRep), "reportType"] = reportList[iRep]
    
for iBd in range(0, nBrec):
    transAcc_lmm_pd.loc[(transAcc_lmm_pd["transDim"] == iBd), "transDim"] = bindDirecList[iBd]
    
for iBc in range(0, nBcon):
    transAcc_lmm_pd.loc[(transAcc_lmm_pd["transConds"] == iBc), "transConds"] = bindCondsList[iBc]

transAcc_lmm_pd

      groupNo  subjNo reportType transDim   transConds  transAcc
0    0younger       0      0marg    0Item  1PreCorrect  0.979839
1    0younger       1      0marg    0Item  1PreCorrect  0.996078
2    0younger       2      0marg    0Item  1PreCorrect  0.984127
3    0younger       3      0marg    0Item  1PreCorrect  0.983806
4    0younger       4      0marg    0Item  1PreCorrect  0.984000
..        ...     ...        ...      ...          ...       ...
899    1older      45    1recons     1Pos    0PreWrong  0.385135
900    1older      46    1recons     1Pos    0PreWrong  0.335260
901    1older      47    1recons     1Pos    0PreWrong  0.421053
902    1older      48    1recons     1Pos    0PreWrong  0.364780
903    1older      49    1recons     1Pos    0PreWrong  0.248408

[904 rows x 6 columns]

In [12]:
path_or_buf = FBdata_folder + 'Fig2E_transAcc_overall_group_stats_Exp12.csv' 
transAcc_lmm_pd.to_csv(path_or_buf = path_or_buf)

## Figure 2G (Exp1 + Exp2): Binding-related measure (conditional probability)

The data was originally saved in seqMemTask_BehvPaper_Figure2Exp12.m

In [4]:
bindsMat = loadmat(FBdata_folder + 'Fig2G_binds_overall_group_stats_Exp12.mat') # 'binds_overall_group'
binds_lmm_group = bindsMat['binds_overall_group']
binds_lmm_pd    = pd.DataFrame(binds_lmm_group) 
binds_lmm_pd
# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) binding direction: 0-(item | pos), 1-(pos | item)
# (5) binding conditions: 1-the other dimension is correct, 0-the other dimension is incorrect
# (6) binding score: a value ranging from 0 to 1
# (7) age per participant

        0     1    2    3    4         5     6
0     0.0   0.0  0.0  0.0  1.0  0.987500  22.0
1     0.0   1.0  0.0  0.0  1.0  0.996016  22.0
2     0.0   2.0  0.0  0.0  1.0  0.987805  22.0
3     0.0   3.0  0.0  0.0  1.0  0.981132  22.0
4     0.0   4.0  0.0  0.0  1.0  0.983539  21.0
...   ...   ...  ...  ...  ...       ...   ...
1803  1.0  45.0  1.0  1.0  0.0  0.211268  67.0
1804  1.0  46.0  1.0  1.0  0.0  0.227848  67.0
1805  1.0  47.0  1.0  1.0  0.0  0.125000  67.0
1806  1.0  48.0  1.0  1.0  0.0  0.157895  67.0
1807  1.0  49.0  1.0  1.0  0.0  0.176471  67.0

[1808 rows x 7 columns]

In [5]:
column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'bindDirec', 4: 'bindConds', 5: 'bindScore', 6: 'age'} 
binds_lmm_pd = binds_lmm_pd.rename(columns = column_name) 
binds_lmm_pd.groupNo    = binds_lmm_pd.groupNo.astype('int64')
binds_lmm_pd.subjNo     = binds_lmm_pd.subjNo.astype('int64')
binds_lmm_pd.reportType = binds_lmm_pd.reportType.astype('int64')
binds_lmm_pd.bindDirec  = binds_lmm_pd.bindDirec.astype('int64')
binds_lmm_pd.bindConds  = binds_lmm_pd.bindConds.astype('int64')
binds_lmm_pd

# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) binding direction: 0-(item | pos), 1-(pos | item)
# (5) binding conditions: 1-the other dimension is correct, 0-the other dimension is incorrect
# (6) binding score: a value ranging from 0 to 1

      groupNo  subjNo  reportType  bindDirec  bindConds  bindScore   age
0           0       0           0          0          1   0.987500  22.0
1           0       1           0          0          1   0.996016  22.0
2           0       2           0          0          1   0.987805  22.0
3           0       3           0          0          1   0.981132  22.0
4           0       4           0          0          1   0.983539  21.0
...       ...     ...         ...        ...        ...        ...   ...
1803        1      45           1          1          0   0.211268  67.0
1804        1      46           1          1          0   0.227848  67.0
1805        1      47           1          1          0   0.125000  67.0
1806        1      48           1          1          0   0.157895  67.0
1807        1      49           1          1          0   0.176471  67.0

[1808 rows x 7 columns]

In [6]:
nGroup = 2 # YA and OA
nReps  = 2 # marginal and reconstruction report
nBrec  = 2 # 2 binding directions: (item | pos) & (pos | item)
nBcon  = 2 # 2 binding condition (their difference is 'cost' or 'benefit'): other dimension is Wrong (0) or Right (1)
groupList  = ['0younger', '1older']
reportList = ['0marg', '1recons']
bindDirecList = ['0ItemOnPos', '1PosOnItem']
bindCondsList = ['0OtherW', '1OtherR']
for iGrp in range(0, nGroup):
    binds_lmm_pd.loc[(binds_lmm_pd["groupNo"] == iGrp), "groupNo"] = groupList[iGrp] 
    
for iRep in range(0, nReps):
    binds_lmm_pd.loc[(binds_lmm_pd["reportType"] == iRep), "reportType"] = reportList[iRep]
    
for iBd in range(0, nBrec):
    binds_lmm_pd.loc[(binds_lmm_pd["bindDirec"] == iBd), "bindDirec"] = bindDirecList[iBd]
    
for iBc in range(0, nBcon):
    binds_lmm_pd.loc[(binds_lmm_pd["bindConds"] == iBc), "bindConds"] = bindCondsList[iBc]

binds_lmm_pd

       groupNo  subjNo reportType   bindDirec bindConds  bindScore   age
0     0younger       0      0marg  0ItemOnPos   1OtherR   0.987500  22.0
1     0younger       1      0marg  0ItemOnPos   1OtherR   0.996016  22.0
2     0younger       2      0marg  0ItemOnPos   1OtherR   0.987805  22.0
3     0younger       3      0marg  0ItemOnPos   1OtherR   0.981132  22.0
4     0younger       4      0marg  0ItemOnPos   1OtherR   0.983539  21.0
...        ...     ...        ...         ...       ...        ...   ...
1803    1older      45    1recons  1PosOnItem   0OtherW   0.211268  67.0
1804    1older      46    1recons  1PosOnItem   0OtherW   0.227848  67.0
1805    1older      47    1recons  1PosOnItem   0OtherW   0.125000  67.0
1806    1older      48    1recons  1PosOnItem   0OtherW   0.157895  67.0
1807    1older      49    1recons  1PosOnItem   0OtherW   0.176471  67.0

[1808 rows x 7 columns]

In [7]:
path_or_buf = FBdata_folder + 'Fig2G_binds_overall_group_stats_Exp12.csv' 
binds_lmm_pd.to_csv(path_or_buf = path_or_buf)

## Figure 2HI (Exp1 + Exp2): Binding-related measures

The data was originally saved in seqMemTask_BehvPaper_Figure2Exp12.m

In [8]:
bindsMat = loadmat(FBdata_folder + 'Fig2HI_binds_overall_diff_group_stats_Exp12.mat') # 'binds_overall_diff_group'
binds_lmm_group = bindsMat['binds_overall_diff_group']
binds_lmm_pd    = pd.DataFrame(binds_lmm_group) 
binds_lmm_pd
# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj: 0-subLen
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) binding direction: 0-(item | pos), 1-(pos | item)
# (5) binding conditions: 0-binding cost (flipped, the same direction as benefit), 1-binding benefit
# (6) binding score: a value ranging from 0 to 1
# (7) age per participant

       0     1    2    3    4         5     6
0    0.0   0.0  0.0  0.0  0.0  0.237500  22.0
1    0.0   1.0  0.0  0.0  0.0 -0.003984  22.0
2    0.0   2.0  0.0  0.0  0.0  0.154472  21.0
3    0.0   3.0  0.0  0.0  0.0 -0.018868  21.0
4    0.0   4.0  0.0  0.0  0.0 -0.016461  25.0
..   ...   ...  ...  ...  ...       ...   ...
899  1.0  45.0  1.0  1.0  1.0  0.334187  65.0
900  1.0  46.0  1.0  1.0  1.0  0.197684  67.0
901  1.0  47.0  1.0  1.0  1.0  0.511364  67.0
902  1.0  48.0  1.0  1.0  1.0  0.322497  67.0
903  1.0  49.0  1.0  1.0  1.0  0.080672  67.0

[904 rows x 7 columns]

In [9]:
column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'bindDirec', 4: 'bindConds', 5: 'bindScore', 6: 'age'} 
binds_lmm_pd = binds_lmm_pd.rename(columns = column_name) 
binds_lmm_pd.groupNo    = binds_lmm_pd.groupNo.astype('int64')
binds_lmm_pd.subjNo     = binds_lmm_pd.subjNo.astype('int64')
binds_lmm_pd.reportType = binds_lmm_pd.reportType.astype('int64')
binds_lmm_pd.bindDirec  = binds_lmm_pd.bindDirec.astype('int64')
binds_lmm_pd.bindConds  = binds_lmm_pd.bindConds.astype('int64')
binds_lmm_pd

# 6 columns:
# (1) age groups: 0-YA, 1-OA
# (2) subj
# (3) report types: 0-marginal reports, 1-reconstruction report
# (4) binding direction: 0-(item | pos), 1-(pos | item)
# (5) binding conditions: 1-the other dimension is correct, 0-the other dimension is incorrect
# (6) binding score: a value ranging from 0 to 1

     groupNo  subjNo  reportType  bindDirec  bindConds  bindScore   age
0          0       0           0          0          0   0.237500  22.0
1          0       1           0          0          0  -0.003984  22.0
2          0       2           0          0          0   0.154472  21.0
3          0       3           0          0          0  -0.018868  21.0
4          0       4           0          0          0  -0.016461  25.0
..       ...     ...         ...        ...        ...        ...   ...
899        1      45           1          1          1   0.334187  65.0
900        1      46           1          1          1   0.197684  67.0
901        1      47           1          1          1   0.511364  67.0
902        1      48           1          1          1   0.322497  67.0
903        1      49           1          1          1   0.080672  67.0

[904 rows x 7 columns]

In [10]:
nGroup = 2 # YA and OA
nReps  = 2 # marginal and reconstruction report
nBrec  = 2 # 2 binding directions: (item | pos) & (pos | item)
nBcon  = 2 # 2 binding condition: cost (0, flipped, with the same direction as benefit) and benefit (1)
groupList  = ['0younger', '1older']
reportList = ['0marg', '1recons']
bindDirecList = ['0ItemOnPos', '1PosOnItem']
bindCondsList = ['0cost', '1benefit']
for iGrp in range(0, nGroup):
    binds_lmm_pd.loc[(binds_lmm_pd["groupNo"] == iGrp), "groupNo"] = groupList[iGrp] 
    
for iRep in range(0, nReps):
    binds_lmm_pd.loc[(binds_lmm_pd["reportType"] == iRep), "reportType"] = reportList[iRep]
    
for iBd in range(0, nBrec):
    binds_lmm_pd.loc[(binds_lmm_pd["bindDirec"] == iBd), "bindDirec"] = bindDirecList[iBd]
    
for iBc in range(0, nBcon):
    binds_lmm_pd.loc[(binds_lmm_pd["bindConds"] == iBc), "bindConds"] = bindCondsList[iBc]

binds_lmm_pd

      groupNo  subjNo reportType   bindDirec bindConds  bindScore   age
0    0younger       0      0marg  0ItemOnPos     0cost   0.237500  22.0
1    0younger       1      0marg  0ItemOnPos     0cost  -0.003984  22.0
2    0younger       2      0marg  0ItemOnPos     0cost   0.154472  21.0
3    0younger       3      0marg  0ItemOnPos     0cost  -0.018868  21.0
4    0younger       4      0marg  0ItemOnPos     0cost  -0.016461  25.0
..        ...     ...        ...         ...       ...        ...   ...
899    1older      45    1recons  1PosOnItem  1benefit   0.334187  65.0
900    1older      46    1recons  1PosOnItem  1benefit   0.197684  67.0
901    1older      47    1recons  1PosOnItem  1benefit   0.511364  67.0
902    1older      48    1recons  1PosOnItem  1benefit   0.322497  67.0
903    1older      49    1recons  1PosOnItem  1benefit   0.080672  67.0

[904 rows x 7 columns]

In [11]:
path_or_buf = FBdata_folder + 'Fig2HI_binds_overall_diff_group_stats_Exp12.csv' 
binds_lmm_pd.to_csv(path_or_buf = path_or_buf)