**seqMem_LMM**

In [1]:
library(lmerTest)
# install.packages("afex") 
library(afex)
# install.packages("emmeans")
library(emmeans) # used for post-hoc test
#install.packages("betareg")
# library(betareg) # used for beta-regression
#install.packages("TMB", type = "binary")
#install.packages("glmmTMB", type = "binary")
# library(glmmTMB)
# install.packages("brms"): running in the Rstudio
# library(brms)
library(dplyr)

Lade nötiges Paket: lme4

Lade nötiges Paket: Matrix


Attache Paket: ‘lmerTest’


Das folgende Objekt ist maskiert ‘package:lme4’:

    lmer


Das folgende Objekt ist maskiert ‘package:stats’:

    step


************
Welcome to afex. For support visit: http://afex.singmann.science/

- Functions for ANOVAs: aov_car(), aov_ez(), and aov_4()
- Methods for calculating p-values with mixed(): 'S', 'KR', 'LRT', and 'PB'
- 'afex_aov' and 'mixed' objects can be passed to emmeans() for follow-up tests
- Get and set global package options with: afex_options()
- Set sum-to-zero contrasts globally: set_sum_contrasts()
- For example analyses see: browseVignettes("afex")
************


Attache Paket: ‘afex’


Das folgende Objekt ist maskiert ‘package:lme4’:

    lmer


Welcome to emmeans.
Caution: You lose important information if you filter this package's results.
See '? untidy'


Attache Paket: ‘dplyr’


Die folgenden Objekte sind maskiert von ‘package:stats’:

    filter, lag


Die folgenden Objekte sind maskiert von ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
packageVersion("afex")

[1] ‘1.5.0’

In [3]:
packageVersion("lmerTest")

[1] ‘3.1.3’

In [4]:
packageVersion("emmeans")

[1] ‘1.11.2.8’

# Subjects' information

In [2]:
expDir         = '/Users/ren/Projects-NeuroCode/MyExperiment/Aging-SeqMemTask/AgingReplay-OnlineData/'
expDir_inHouse = '/Users/ren/Projects-NeuroCode/MyExperiment/Aging-SeqMemTask/AgingReplay-InHouseData/'
statSaveDir    = '/Users/ren/Projects-NeuroCode/MyExperiment/Aging-SeqMemTask/AgingReplay-StatAnal/' 
modelSaveDir   = '/Users/ren/Projects-NeuroCode/MyExperiment/Aging-SeqMemTask/ModelFitting_Results/'
FBdata_folder  = '/Users/ren/Projects-NeuroCode/MyExperiment/Aging-SeqMemTask/AgingReplay-OnlineData/FlexibleBindingPaper-Data/'

# Experiment 1: memory gradation across content, position and reconstruction report in both younger (18-30 ys) and older (>75 ys) adults

## Figure 2A and 2B-left panel: Within-age group comparison –– accuracy in content > position > reconstruction report

response (1/0) ~ measure * trialNo + (1 + measure * trialNo | subjNo)

In [ ]:
# path_or_buf <- paste0(expDir, 'acc_lmm_group_exp1.csv') #'acc_lmm_pd.csv'
# resp_glmm_pd <- read.csv(file = path_or_buf)
# resp_glmm_pd

In [3]:
path_or_buf <- paste0(expDir, 'resp_glmm_group_exp1.csv') #'resp_glmm_group.csv'
resp_glmm_pd <- read.csv(file = path_or_buf)
resp_glmm_pd

      X     groupNo  subjNo trialNo   transNo measNo   resp
1      0    0younger 0      0.0000000 1       0content 1
2      1    0younger 0      0.0000000 2       0content 1
3      2    0younger 0      0.0000000 3       0content 1
4      3    0younger 0      0.0000000 4       0content 1
5      4    0younger 0      0.0000000 5       0content 1
6      5    0younger 0      0.6931472 1       0content 1
7      6    0younger 0      0.6931472 2       0content 1
8      7    0younger 0      0.6931472 3       0content 1
9      8    0younger 0      0.6931472 4       0content 1
10     9    0younger 0      0.6931472 5       0content 1
11    10    0younger 0      1.0986123 1       0content 1
12    11    0younger 0      1.0986123 2       0content 1
13    12    0younger 0      1.0986123 3       0content 0
14    13    0younger 0      1.0986123 4       0content 1
15    14    0younger 0      1.0986123 5       0content 1
16    15    0younger 0      1.3862944 1       0content 1
17    16    0younger 0      1.3862944 2       0content 1
18    17    0younger 0      1.3862944 3       0content 1
19    18    0younger 0      1.3862944 4       0content 1
20    19    0younger 0      1.3862944 5       0content 1
21    20    0younger 0      1.6094379 1       0content 1
22    21    0younger 0      1.6094379 2       0content 1
23    22    0younger 0      1.6094379 3       0content 1
24    23    0younger 0      1.6094379 4       0content 1
25    24    0younger 0      1.6094379 5       0content 1
26    25    0younger 0      1.7917595 1       0content 1
27    26    0younger 0      1.7917595 2       0content 1
28    27    0younger 0      1.7917595 3       0content 1
29    28    0younger 0      1.7917595 4       0content 1
30    29    0younger 0      1.7917595 5       0content 1
⋮     ⋮     ⋮        ⋮      ⋮         ⋮       ⋮        ⋮
63331 63330 1older   26     4.077537  1       2both    1
63332 63331 1older   26     4.077537  2       2both    1
63333 63332 1older   26     4.077537  3       2both    1
63334 63333 1older   26     4.077537  4       2both    1
63335 63334 1older   26     4.077537  5       2both    1
63336 63335 1older   26     4.094345  1       2both    0
63337 63336 1older   26     4.094345  2       2both    0
63338 63337 1older   26     4.094345  3       2both    0
63339 63338 1older   26     4.094345  4       2both    0
63340 63339 1older   26     4.094345  5       2both    0
63341 63340 1older   26     4.110874  1       2both    1
63342 63341 1older   26     4.110874  2       2both    1
63343 63342 1older   26     4.110874  3       2both    1
63344 63343 1older   26     4.110874  4       2both    0
63345 63344 1older   26     4.110874  5       2both    0
63346 63345 1older   26     4.127134  1       2both    0
63347 63346 1older   26     4.127134  2       2both    0
63348 63347 1older   26     4.127134  3       2both    0
63349 63348 1older   26     4.127134  4       2both    1
63350 63349 1older   26     4.127134  5       2both    0
63351 63350 1older   26     4.143135  1       2both    0
63352 63351 1older   26     4.143135  2       2both    0
63353 63352 1older   26     4.143135  3       2both    0
63354 63353 1older   26     4.143135  4       2both    0
63355 63354 1older   26     4.143135  5       2both    1
63356 63355 1older   26     4.158883  1       2both    0
63357 63356 1older   26     4.158883  2       2both    0
63358 63357 1older   26     4.158883  3       2both    0
63359 63358 1older   26     4.158883  4       2both    0
63360 63359 1older   26     4.158883  5       2both    0

### YA and OA together

In [4]:
resp_glmm_pd_YAOA = resp_glmm_pd

In [5]:
resp_glmm_pd_YAOA$trialNo = scale(resp_glmm_pd_YAOA$trialNo, center=TRUE, scale=FALSE) #scale=FALSE
resp_glmm_pd_YAOA

      X     groupNo  subjNo trialNo   transNo measNo   resp
1      0    0younger 0      -3.205753 1       0content 1
2      1    0younger 0      -3.205753 2       0content 1
3      2    0younger 0      -3.205753 3       0content 1
4      3    0younger 0      -3.205753 4       0content 1
5      4    0younger 0      -3.205753 5       0content 1
6      5    0younger 0      -2.512606 1       0content 1
7      6    0younger 0      -2.512606 2       0content 1
8      7    0younger 0      -2.512606 3       0content 1
9      8    0younger 0      -2.512606 4       0content 1
10     9    0younger 0      -2.512606 5       0content 1
11    10    0younger 0      -2.107141 1       0content 1
12    11    0younger 0      -2.107141 2       0content 1
13    12    0younger 0      -2.107141 3       0content 0
14    13    0younger 0      -2.107141 4       0content 1
15    14    0younger 0      -2.107141 5       0content 1
16    15    0younger 0      -1.819459 1       0content 1
17    16    0younger 0      -1.819459 2       0content 1
18    17    0younger 0      -1.819459 3       0content 1
19    18    0younger 0      -1.819459 4       0content 1
20    19    0younger 0      -1.819459 5       0content 1
21    20    0younger 0      -1.596315 1       0content 1
22    21    0younger 0      -1.596315 2       0content 1
23    22    0younger 0      -1.596315 3       0content 1
24    23    0younger 0      -1.596315 4       0content 1
25    24    0younger 0      -1.596315 5       0content 1
26    25    0younger 0      -1.413994 1       0content 1
27    26    0younger 0      -1.413994 2       0content 1
28    27    0younger 0      -1.413994 3       0content 1
29    28    0younger 0      -1.413994 4       0content 1
30    29    0younger 0      -1.413994 5       0content 1
⋮     ⋮     ⋮        ⋮      ⋮         ⋮       ⋮        ⋮
63331 63330 1older   26     0.8717843 1       2both    1
63332 63331 1older   26     0.8717843 2       2both    1
63333 63332 1older   26     0.8717843 3       2both    1
63334 63333 1older   26     0.8717843 4       2both    1
63335 63334 1older   26     0.8717843 5       2both    1
63336 63335 1older   26     0.8885914 1       2both    0
63337 63336 1older   26     0.8885914 2       2both    0
63338 63337 1older   26     0.8885914 3       2both    0
63339 63338 1older   26     0.8885914 4       2both    0
63340 63339 1older   26     0.8885914 5       2both    0
63341 63340 1older   26     0.9051207 1       2both    1
63342 63341 1older   26     0.9051207 2       2both    1
63343 63342 1older   26     0.9051207 3       2both    1
63344 63343 1older   26     0.9051207 4       2both    0
63345 63344 1older   26     0.9051207 5       2both    0
63346 63345 1older   26     0.9213813 1       2both    0
63347 63346 1older   26     0.9213813 2       2both    0
63348 63347 1older   26     0.9213813 3       2both    0
63349 63348 1older   26     0.9213813 4       2both    1
63350 63349 1older   26     0.9213813 5       2both    0
63351 63350 1older   26     0.9373816 1       2both    0
63352 63351 1older   26     0.9373816 2       2both    0
63353 63352 1older   26     0.9373816 3       2both    0
63354 63353 1older   26     0.9373816 4       2both    0
63355 63354 1older   26     0.9373816 5       2both    1
63356 63355 1older   26     0.9531300 1       2both    0
63357 63356 1older   26     0.9531300 2       2both    0
63358 63357 1older   26     0.9531300 3       2both    0
63359 63358 1older   26     0.9531300 4       2both    0
63360 63359 1older   26     0.9531300 5       2both    0

In [7]:
choiceModel <- mixed(resp ~ trialNo*measNo*groupNo + (1 | subjNo), data = resp_glmm_pd_YAOA, family = binomial, method="LRT")
choiceModel

Contrasts set to contr.sum for the following variables: measNo, groupNo

Mixed Model Anova Table (Type 3 tests, LRT-method)

Model: resp ~ trialNo * measNo * groupNo + (1 | subjNo)
Data: resp_glmm_pd_YAOA
Df full model: 13
                  Effect df       Chisq p.value
1                trialNo  1 1055.57 ***   <.001
2                 measNo  2 4548.33 ***   <.001
3                groupNo  1 5552.26 ***   <.001
4         trialNo:measNo  2   14.94 ***   <.001
5        trialNo:groupNo  1   21.57 ***   <.001
6         measNo:groupNo  2  174.68 ***   <.001
7 trialNo:measNo:groupNo  2   21.59 ***   <.001
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1

In [9]:
emm1 = emmeans(choiceModel, specs = ~ trialNo*measNo*groupNo) # same as: emmeans(choiceModel, ~ networkName) & emmeans(choiceModel, c("networkName"))
emm1

   trialNo measNo    groupNo  emmean    SE  df asymp.LCL asymp.UCL
 -9.07e-14 0content  0younger  2.889 0.156 Inf    2.5830     3.195
 -9.07e-14 1position 0younger  2.500 0.155 Inf    2.1961     2.804
 -9.07e-14 2both     0younger  1.399 0.153 Inf    1.0985     1.700
 -9.07e-14 0content  1older    1.576 0.155 Inf    1.2732     1.879
 -9.07e-14 1position 1older    0.397 0.154 Inf    0.0958     0.699
 -9.07e-14 2both     1older   -0.469 0.154 Inf   -0.7705    -0.167

Results are given on the logit (not the response) scale.
Confidence level used: 0.95

In [10]:
emm_pairs <- pairs(emm1, simple = "measNo", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

trialNo = -9.07e-14, groupNo = 0younger:
 contrast             estimate     SE  df z.ratio p.value
 0content - 1position    0.389 0.0478 Inf   8.137  <.0001
 0content - 2both        1.490 0.0429 Inf  34.735  <.0001
 1position - 2both       1.101 0.0390 Inf  28.217  <.0001

trialNo = -9.07e-14, groupNo = 1older:
 contrast             estimate     SE  df z.ratio p.value
 0content - 1position    1.179 0.0361 Inf  32.645  <.0001
 0content - 2both        2.045 0.0370 Inf  55.329  <.0001
 1position - 2both       0.866 0.0331 Inf  26.136  <.0001

Results are given on the log odds ratio (not the response) scale.
P value adjustment: bonferroni method for 3 tests

### Younger group

In [4]:
resp_glmm_pd_young = resp_glmm_pd[resp_glmm_pd$groupNo == '0younger', ]
resp_glmm_pd_young

      X     groupNo  subjNo trialNo   transNo measNo   resp
1      0    0younger 0      0.0000000 1       0content 1
2      1    0younger 0      0.0000000 2       0content 1
3      2    0younger 0      0.0000000 3       0content 1
4      3    0younger 0      0.0000000 4       0content 1
5      4    0younger 0      0.0000000 5       0content 1
6      5    0younger 0      0.6931472 1       0content 1
7      6    0younger 0      0.6931472 2       0content 1
8      7    0younger 0      0.6931472 3       0content 1
9      8    0younger 0      0.6931472 4       0content 1
10     9    0younger 0      0.6931472 5       0content 1
11    10    0younger 0      1.0986123 1       0content 1
12    11    0younger 0      1.0986123 2       0content 1
13    12    0younger 0      1.0986123 3       0content 0
14    13    0younger 0      1.0986123 4       0content 1
15    14    0younger 0      1.0986123 5       0content 1
16    15    0younger 0      1.3862944 1       0content 1
17    16    0younger 0      1.3862944 2       0content 1
18    17    0younger 0      1.3862944 3       0content 1
19    18    0younger 0      1.3862944 4       0content 1
20    19    0younger 0      1.3862944 5       0content 1
21    20    0younger 0      1.6094379 1       0content 1
22    21    0younger 0      1.6094379 2       0content 1
23    22    0younger 0      1.6094379 3       0content 1
24    23    0younger 0      1.6094379 4       0content 1
25    24    0younger 0      1.6094379 5       0content 1
26    25    0younger 0      1.7917595 1       0content 1
27    26    0younger 0      1.7917595 2       0content 1
28    27    0younger 0      1.7917595 3       0content 1
29    28    0younger 0      1.7917595 4       0content 1
30    29    0younger 0      1.7917595 5       0content 1
⋮     ⋮     ⋮        ⋮      ⋮         ⋮       ⋮        ⋮
37411 37410 0younger 38     4.077537  1       2both    1
37412 37411 0younger 38     4.077537  2       2both    1
37413 37412 0younger 38     4.077537  3       2both    1
37414 37413 0younger 38     4.077537  4       2both    1
37415 37414 0younger 38     4.077537  5       2both    1
37416 37415 0younger 38     4.094345  1       2both    1
37417 37416 0younger 38     4.094345  2       2both    1
37418 37417 0younger 38     4.094345  3       2both    1
37419 37418 0younger 38     4.094345  4       2both    1
37420 37419 0younger 38     4.094345  5       2both    1
37421 37420 0younger 38     4.110874  1       2both    1
37422 37421 0younger 38     4.110874  2       2both    1
37423 37422 0younger 38     4.110874  3       2both    1
37424 37423 0younger 38     4.110874  4       2both    1
37425 37424 0younger 38     4.110874  5       2both    1
37426 37425 0younger 38     4.127134  1       2both    1
37427 37426 0younger 38     4.127134  2       2both    1
37428 37427 0younger 38     4.127134  3       2both    1
37429 37428 0younger 38     4.127134  4       2both    1
37430 37429 0younger 38     4.127134  5       2both    1
37431 37430 0younger 38     4.143135  1       2both    1
37432 37431 0younger 38     4.143135  2       2both    1
37433 37432 0younger 38     4.143135  3       2both    1
37434 37433 0younger 38     4.143135  4       2both    1
37435 37434 0younger 38     4.143135  5       2both    1
37436 37435 0younger 38     4.158883  1       2both    1
37437 37436 0younger 38     4.158883  2       2both    1
37438 37437 0younger 38     4.158883  3       2both    1
37439 37438 0younger 38     4.158883  4       2both    1
37440 37439 0younger 38     4.158883  5       2both    1

In [5]:
resp_glmm_pd_young$trialNo = scale(resp_glmm_pd_young$trialNo, center=TRUE, scale=FALSE) #scale=FALSE

In [6]:
choiceModel <- mixed(resp ~ trialNo*measNo + (1 | subjNo), data = resp_glmm_pd_young, family = binomial, method="LRT")
choiceModel

Contrasts set to contr.sum for the following variables: measNo

Mixed Model Anova Table (Type 3 tests, LRT-method)

Model: resp ~ trialNo * measNo + (1 | subjNo)
Data: resp_glmm_pd_young
Df full model: 7
          Effect df       Chisq p.value
1        trialNo  1  669.81 ***   <.001
2         measNo  2 1725.01 ***   <.001
3 trialNo:measNo  2   36.33 ***   <.001
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1

In [7]:
emm1 = emmeans(choiceModel, specs = ~ trialNo*measNo) # same as: emmeans(choiceModel, ~ networkName) & emmeans(choiceModel, c("networkName"))
emm1

  trialNo measNo    emmean    SE  df asymp.LCL asymp.UCL
 2.88e-13 0content    3.12 0.191 Inf      2.74      3.49
 2.88e-13 1position   2.70 0.190 Inf      2.32      3.07
 2.88e-13 2both       1.49 0.189 Inf      1.12      1.86

Results are given on the logit (not the response) scale.
Confidence level used: 0.95

In [8]:
emm_pairs <- pairs(emm1, simple = "measNo", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

trialNo = 2.88e-13:
 contrast             estimate     SE  df z.ratio p.value
 0content - 1position    0.421 0.0496 Inf   8.484  <.0001
 0content - 2both        1.628 0.0452 Inf  35.995  <.0001
 1position - 2both       1.207 0.0411 Inf  29.360  <.0001

Results are given on the log odds ratio (not the response) scale.
P value adjustment: bonferroni method for 3 tests

### Older group

In [9]:
resp_glmm_pd_old = resp_glmm_pd[resp_glmm_pd$groupNo == '1older', ]
resp_glmm_pd_old

      X     groupNo subjNo trialNo   transNo measNo   resp
37441 37440 1older  0      0.0000000 1       0content 1
37442 37441 1older  0      0.0000000 2       0content 1
37443 37442 1older  0      0.0000000 3       0content 1
37444 37443 1older  0      0.0000000 4       0content 1
37445 37444 1older  0      0.0000000 5       0content 1
37446 37445 1older  0      0.6931472 1       0content 1
37447 37446 1older  0      0.6931472 2       0content 0
37448 37447 1older  0      0.6931472 3       0content 0
37449 37448 1older  0      0.6931472 4       0content 1
37450 37449 1older  0      0.6931472 5       0content 1
37451 37450 1older  0      1.0986123 1       0content 0
37452 37451 1older  0      1.0986123 2       0content 0
37453 37452 1older  0      1.0986123 3       0content 0
37454 37453 1older  0      1.0986123 4       0content 0
37455 37454 1older  0      1.0986123 5       0content 1
37456 37455 1older  0      1.3862944 1       0content 1
37457 37456 1older  0      1.3862944 2       0content 1
37458 37457 1older  0      1.3862944 3       0content 1
37459 37458 1older  0      1.3862944 4       0content 1
37460 37459 1older  0      1.3862944 5       0content 1
37461 37460 1older  0      1.6094379 1       0content 1
37462 37461 1older  0      1.6094379 2       0content 1
37463 37462 1older  0      1.6094379 3       0content 0
37464 37463 1older  0      1.6094379 4       0content 1
37465 37464 1older  0      1.6094379 5       0content 1
37466 37465 1older  0      1.7917595 1       0content 0
37467 37466 1older  0      1.7917595 2       0content 1
37468 37467 1older  0      1.7917595 3       0content 1
37469 37468 1older  0      1.7917595 4       0content 0
37470 37469 1older  0      1.7917595 5       0content 1
⋮     ⋮     ⋮       ⋮      ⋮         ⋮       ⋮        ⋮
63331 63330 1older  26     4.077537  1       2both    1
63332 63331 1older  26     4.077537  2       2both    1
63333 63332 1older  26     4.077537  3       2both    1
63334 63333 1older  26     4.077537  4       2both    1
63335 63334 1older  26     4.077537  5       2both    1
63336 63335 1older  26     4.094345  1       2both    0
63337 63336 1older  26     4.094345  2       2both    0
63338 63337 1older  26     4.094345  3       2both    0
63339 63338 1older  26     4.094345  4       2both    0
63340 63339 1older  26     4.094345  5       2both    0
63341 63340 1older  26     4.110874  1       2both    1
63342 63341 1older  26     4.110874  2       2both    1
63343 63342 1older  26     4.110874  3       2both    1
63344 63343 1older  26     4.110874  4       2both    0
63345 63344 1older  26     4.110874  5       2both    0
63346 63345 1older  26     4.127134  1       2both    0
63347 63346 1older  26     4.127134  2       2both    0
63348 63347 1older  26     4.127134  3       2both    0
63349 63348 1older  26     4.127134  4       2both    1
63350 63349 1older  26     4.127134  5       2both    0
63351 63350 1older  26     4.143135  1       2both    0
63352 63351 1older  26     4.143135  2       2both    0
63353 63352 1older  26     4.143135  3       2both    0
63354 63353 1older  26     4.143135  4       2both    0
63355 63354 1older  26     4.143135  5       2both    1
63356 63355 1older  26     4.158883  1       2both    0
63357 63356 1older  26     4.158883  2       2both    0
63358 63357 1older  26     4.158883  3       2both    0
63359 63358 1older  26     4.158883  4       2both    0
63360 63359 1older  26     4.158883  5       2both    0

In [10]:
resp_glmm_pd_old$trialNo = scale(resp_glmm_pd_old$trialNo, center=TRUE, scale=FALSE) #scale=FALSE

In [11]:
choiceModel <- mixed(resp ~ trialNo*measNo + (1 | subjNo), data = resp_glmm_pd_old, family = binomial, method="LRT")
choiceModel

Contrasts set to contr.sum for the following variables: measNo

Mixed Model Anova Table (Type 3 tests, LRT-method)

Model: resp ~ trialNo * measNo + (1 | subjNo)
Data: resp_glmm_pd_old
Df full model: 7
          Effect df       Chisq p.value
1        trialNo  1  480.89 ***   <.001
2         measNo  2 3758.27 ***   <.001
3 trialNo:measNo  2      6.28 *    .043
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1

In [12]:
emm1 = emmeans(choiceModel, specs = ~ trialNo*measNo) # same as: emmeans(choiceModel, ~ networkName) & emmeans(choiceModel, c("networkName"))
emm1

  trialNo measNo    emmean    SE  df asymp.LCL asymp.UCL
 1.77e-13 0content   1.563 0.201 Inf     1.169     1.956
 1.77e-13 1position  0.284 0.200 Inf    -0.109     0.676
 1.77e-13 2both     -0.657 0.200 Inf    -1.050    -0.264

Results are given on the logit (not the response) scale.
Confidence level used: 0.95

In [13]:
emm_pairs <- pairs(emm1, simple = "measNo", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

trialNo = 1.77e-13:
 contrast             estimate     SE  df z.ratio p.value
 0content - 1position    1.279 0.0380 Inf  33.643  <.0001
 0content - 2both        2.219 0.0395 Inf  56.221  <.0001
 1position - 2both       0.941 0.0347 Inf  27.075  <.0001

Results are given on the log odds ratio (not the response) scale.
P value adjustment: bonferroni method for 3 tests

## Between-group comparison: accuracy difference between groups in content < position < reconstruction

### Method 1: importing the accuracy change percentage ((old-young)/young)

In [19]:
path_or_buf <- paste0(expDir, 'acc_change_lmm_subj_exp1.csv') 
acc_lmm_pd <- read.csv(file = path_or_buf)
acc_lmm_pd

     X    groupNo subjNo trialNo measNo   acc_change  fullyCor
1     0   1       0       1      0content  0.07977159 0
2     1   1       0       2      0content -0.35213705 0
3     2   1       0       3      0content -0.78404568 0
4     3   1       0       4      0content  0.07977159 0
5     4   1       0       5      0content -0.13618273 0
6     5   1       0       6      0content -0.35213705 0
7     6   1       0       7      0content  0.07977159 0
8     7   1       0       8      0content -0.35213705 0
9     8   1       0       9      0content -0.35213705 0
10    9   1       0      10      0content -0.35213705 0
11   10   1       0      11      0content  0.07977159 0
12   11   1       0      12      0content -0.35213705 0
13   12   1       0      13      0content -0.35213705 0
14   13   1       0      14      0content -0.35213705 0
15   14   1       0      15      0content -0.35213705 0
16   15   1       0      16      0content -0.13618273 0
17   16   1       0      17      0content  0.07977159 0
18   17   1       0      18      0content  0.07977159 0
19   18   1       0      19      0content -0.13618273 0
20   19   1       0      20      0content -0.13618273 0
21   20   1       0      21      0content -0.35213705 0
22   21   1       0      22      0content  0.07977159 0
23   22   1       0      23      0content -0.56809137 0
24   23   1       0      24      0content -0.13618273 0
25   24   1       0      25      0content  0.07977159 0
26   25   1       0      26      0content -0.56809137 0
27   26   1       0      27      0content -0.78404568 0
28   27   1       0      28      0content  0.07977159 0
29   28   1       0      29      0content -0.78404568 0
30   29   1       0      30      0content -0.56809137 0
⋮    ⋮    ⋮       ⋮      ⋮       ⋮        ⋮           ⋮
5155 5154 1       26     35      2both    -0.47297297 0
5156 5155 1       26     36      2both    -0.73648649 0
5157 5156 1       26     37      2both     0.31756757 0
5158 5157 1       26     38      2both    -1.00000000 0
5159 5158 1       26     39      2both     0.05405405 0
5160 5159 1       26     40      2both    -1.00000000 0
5161 5160 1       26     41      2both     0.05405405 0
5162 5161 1       26     42      2both     0.05405405 0
5163 5162 1       26     43      2both    -0.73648649 0
5164 5163 1       26     44      2both    -0.47297297 0
5165 5164 1       26     45      2both     0.31756757 0
5166 5165 1       26     46      2both    -1.00000000 0
5167 5166 1       26     47      2both    -0.20945946 0
5168 5167 1       26     48      2both    -0.47297297 0
5169 5168 1       26     49      2both    -0.47297297 0
5170 5169 1       26     50      2both     0.31756757 0
5171 5170 1       26     51      2both    -0.47297297 0
5172 5171 1       26     52      2both    -1.00000000 0
5173 5172 1       26     53      2both    -0.73648649 0
5174 5173 1       26     54      2both    -0.47297297 0
5175 5174 1       26     55      2both    -0.20945946 0
5176 5175 1       26     56      2both    -0.73648649 0
5177 5176 1       26     57      2both     0.31756757 0
5178 5177 1       26     58      2both    -0.73648649 0
5179 5178 1       26     59      2both     0.31756757 0
5180 5179 1       26     60      2both    -1.00000000 0
5181 5180 1       26     61      2both    -0.20945946 0
5182 5181 1       26     62      2both    -0.73648649 0
5183 5182 1       26     63      2both    -0.73648649 0
5184 5183 1       26     64      2both    -1.00000000 0

In [20]:
accModel_group <- lmer(acc_change ~ measNo + (1 + measNo | subjNo), data = acc_lmm_pd)

In [21]:
summary(accModel_group)

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: acc_change ~ measNo + (1 + measNo | subjNo)
   Data: acc_lmm_pd

REML criterion at convergence: 2901.5

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.4990 -0.6657  0.1269  0.6799  3.2687

Random effects:
 Groups   Name            Variance Std.Dev. Corr
 subjNo   (Intercept)     0.03615  0.1901
          measNo1position 0.04287  0.2071   -0.22
          measNo2both     0.04197  0.2049   -0.02  0.77
 Residual                 0.09752  0.3123
Number of obs: 5184, groups:  subjNo, 27

Fixed effects:
                Estimate Std. Error       df t value Pr(>|t|)
(Intercept)     -0.15405    0.03736 26.00001  -4.124 0.000338 ***
measNo1position -0.22235    0.04124 26.00099  -5.392 1.20e-05 ***
measNo2both     -0.35933    0.04083 26.00047  -8.800 2.83e-09 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) msN1ps
measNo1pstn -0.242
measNo2both -0.054  0.750

In [22]:
anova(accModel_group, ddf='Satterthwaite')

       Sum Sq   Mean Sq  NumDF DenDF    F value  Pr(>F)
measNo 7.874142 3.937071 2     26.00024 40.37192 1.062093e-08

In [23]:
emm_options(lmerTest.limit = 5184)
emm_comp = emmeans(accModel_group, specs = ~ measNo, lmer.df = "satterthwaite") # specs = ~ groupNo*measNo

In [25]:
test(emm_comp)

  measNo    emmean     SE         df       t.ratio   p.value
1 0content  -0.1540540 0.03735619 26.00001 -4.123920 3.381827e-04
2 1position -0.3764067 0.04848981 26.00034 -7.762594 3.096942e-08
3 2both     -0.5133845 0.05384543 26.00005 -9.534411 5.667354e-10

In [26]:
emm_pairs_comp <- pairs(emm_comp, simple = "measNo", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs_comp

 contrast             estimate     SE df t.ratio p.value
 0content - 1position    0.222 0.0412 26   5.392  <.0001
 0content - 2both        0.359 0.0408 26   8.800  <.0001
 1position - 2both       0.137 0.0290 26   4.715  0.0002

Degrees-of-freedom method: satterthwaite
P value adjustment: bonferroni method for 3 tests

# Experiment 2: only Interleaved curriculum –– three trial organization conditions (interleaved, contentBlocked, positionBlocked)

The data (acc_fullyCor_within_between_trials_YA_OA_group_exp2.mat) was saved in seqMemTask_v2_anal_early_late_window_Binding.m

See more details in seqMem_dataFrame.ipynb and seqMem_LMM.ipynb

## Figure 2C: memory gradient across 3 measures (objReport, locReport, reconsReport) 

Two types of the memory gradient:
(1) 3 retrievals in the three-retrieval trials
(2) 3 retrievals in the first reporting window

In [3]:
path_or_buf  <- paste0(FBdata_folder, 'Fig2C_choice_within_between_trials_group_stats_Exp2.csv')
acc_glmm_pd <- read.csv(file = path_or_buf)
acc_glmm_pd

      X     ageNo    subjNo dataType    reportType trialNo resp
1      0    0younger 0      0withinTrl  0content   1       1
2      1    0younger 0      0withinTrl  0content   1       1
3      2    0younger 0      0withinTrl  0content   1       1
4      3    0younger 0      0withinTrl  0content   1       1
5      4    0younger 0      0withinTrl  0content   1       1
6      5    0younger 0      0withinTrl  0content   3       1
7      6    0younger 0      0withinTrl  0content   3       1
8      7    0younger 0      0withinTrl  0content   3       1
9      8    0younger 0      0withinTrl  0content   3       1
10     9    0younger 0      0withinTrl  0content   3       1
11    10    0younger 0      0withinTrl  0content   4       1
12    11    0younger 0      0withinTrl  0content   4       1
13    12    0younger 0      0withinTrl  0content   4       1
14    13    0younger 0      0withinTrl  0content   4       0
15    14    0younger 0      0withinTrl  0content   4       0
16    15    0younger 0      0withinTrl  0content   5       1
17    16    0younger 0      0withinTrl  0content   5       1
18    17    0younger 0      0withinTrl  0content   5       1
19    18    0younger 0      0withinTrl  0content   5       1
20    19    0younger 0      0withinTrl  0content   5       1
21    20    0younger 0      0withinTrl  0content   7       1
22    21    0younger 0      0withinTrl  0content   7       1
23    22    0younger 0      0withinTrl  0content   7       1
24    23    0younger 0      0withinTrl  0content   7       1
25    24    0younger 0      0withinTrl  0content   7       1
26    25    0younger 0      0withinTrl  0content   8       1
27    26    0younger 0      0withinTrl  0content   8       1
28    27    0younger 0      0withinTrl  0content   8       1
29    28    0younger 0      0withinTrl  0content   8       1
30    29    0younger 0      0withinTrl  0content   8       0
⋮     ⋮     ⋮        ⋮      ⋮           ⋮          ⋮       ⋮
48851 48850 1older   22     1betweenTrl 2both      41      1
48852 48851 1older   22     1betweenTrl 2both      41      0
48853 48852 1older   22     1betweenTrl 2both      41      1
48854 48853 1older   22     1betweenTrl 2both      41      1
48855 48854 1older   22     1betweenTrl 2both      41      1
48856 48855 1older   22     1betweenTrl 2both      42      1
48857 48856 1older   22     1betweenTrl 2both      42      0
48858 48857 1older   22     1betweenTrl 2both      42      1
48859 48858 1older   22     1betweenTrl 2both      42      1
48860 48859 1older   22     1betweenTrl 2both      42      1
48861 48860 1older   22     1betweenTrl 2both      55      0
48862 48861 1older   22     1betweenTrl 2both      55      0
48863 48862 1older   22     1betweenTrl 2both      55      1
48864 48863 1older   22     1betweenTrl 2both      55      1
48865 48864 1older   22     1betweenTrl 2both      55      1
48866 48865 1older   22     1betweenTrl 2both      56      1
48867 48866 1older   22     1betweenTrl 2both      56      0
48868 48867 1older   22     1betweenTrl 2both      56      1
48869 48868 1older   22     1betweenTrl 2both      56      0
48870 48869 1older   22     1betweenTrl 2both      56      0
48871 48870 1older   22     1betweenTrl 2both      57      0
48872 48871 1older   22     1betweenTrl 2both      57      0
48873 48872 1older   22     1betweenTrl 2both      57      1
48874 48873 1older   22     1betweenTrl 2both      57      1
48875 48874 1older   22     1betweenTrl 2both      57      1
48876 48875 1older   22     1betweenTrl 2both      64      0
48877 48876 1older   22     1betweenTrl 2both      64      0
48878 48877 1older   22     1betweenTrl 2both      64      1
48879 48878 1older   22     1betweenTrl 2both      64      1
48880 48879 1older   22     1betweenTrl 2both      64      1

### Memory gradient in the three-retrieval trials

In [39]:
# ------ Three reports within a trial ------
acc_glmm_pd_threeReports = acc_glmm_pd[acc_glmm_pd$dataType == '0withinTrl', ]
acc_glmm_pd_threeReports

      X     ageNo    subjNo dataType   reportType trialNo resp
1      0    0younger 0      0withinTrl 0content   1       1
2      1    0younger 0      0withinTrl 0content   1       1
3      2    0younger 0      0withinTrl 0content   1       1
4      3    0younger 0      0withinTrl 0content   1       1
5      4    0younger 0      0withinTrl 0content   1       1
6      5    0younger 0      0withinTrl 0content   3       1
7      6    0younger 0      0withinTrl 0content   3       1
8      7    0younger 0      0withinTrl 0content   3       1
9      8    0younger 0      0withinTrl 0content   3       1
10     9    0younger 0      0withinTrl 0content   3       1
11    10    0younger 0      0withinTrl 0content   4       1
12    11    0younger 0      0withinTrl 0content   4       1
13    12    0younger 0      0withinTrl 0content   4       1
14    13    0younger 0      0withinTrl 0content   4       0
15    14    0younger 0      0withinTrl 0content   4       0
16    15    0younger 0      0withinTrl 0content   5       1
17    16    0younger 0      0withinTrl 0content   5       1
18    17    0younger 0      0withinTrl 0content   5       1
19    18    0younger 0      0withinTrl 0content   5       1
20    19    0younger 0      0withinTrl 0content   5       1
21    20    0younger 0      0withinTrl 0content   7       1
22    21    0younger 0      0withinTrl 0content   7       1
23    22    0younger 0      0withinTrl 0content   7       1
24    23    0younger 0      0withinTrl 0content   7       1
25    24    0younger 0      0withinTrl 0content   7       1
26    25    0younger 0      0withinTrl 0content   8       1
27    26    0younger 0      0withinTrl 0content   8       1
28    27    0younger 0      0withinTrl 0content   8       1
29    28    0younger 0      0withinTrl 0content   8       1
30    29    0younger 0      0withinTrl 0content   8       0
⋮     ⋮     ⋮        ⋮      ⋮          ⋮          ⋮       ⋮
48531 48530 1older   22     0withinTrl 2both      58      0
48532 48531 1older   22     0withinTrl 2both      58      0
48533 48532 1older   22     0withinTrl 2both      58      1
48534 48533 1older   22     0withinTrl 2both      58      1
48535 48534 1older   22     0withinTrl 2both      58      1
48536 48535 1older   22     0withinTrl 2both      59      1
48537 48536 1older   22     0withinTrl 2both      59      0
48538 48537 1older   22     0withinTrl 2both      59      0
48539 48538 1older   22     0withinTrl 2both      59      0
48540 48539 1older   22     0withinTrl 2both      59      0
48541 48540 1older   22     0withinTrl 2both      60      1
48542 48541 1older   22     0withinTrl 2both      60      0
48543 48542 1older   22     0withinTrl 2both      60      0
48544 48543 1older   22     0withinTrl 2both      60      0
48545 48544 1older   22     0withinTrl 2both      60      0
48546 48545 1older   22     0withinTrl 2both      61      0
48547 48546 1older   22     0withinTrl 2both      61      0
48548 48547 1older   22     0withinTrl 2both      61      0
48549 48548 1older   22     0withinTrl 2both      61      0
48550 48549 1older   22     0withinTrl 2both      61      1
48551 48550 1older   22     0withinTrl 2both      62      0
48552 48551 1older   22     0withinTrl 2both      62      0
48553 48552 1older   22     0withinTrl 2both      62      0
48554 48553 1older   22     0withinTrl 2both      62      0
48555 48554 1older   22     0withinTrl 2both      62      0
48556 48555 1older   22     0withinTrl 2both      63      0
48557 48556 1older   22     0withinTrl 2both      63      1
48558 48557 1older   22     0withinTrl 2both      63      0
48559 48558 1older   22     0withinTrl 2both      63      0
48560 48559 1older   22     0withinTrl 2both      63      0

In [40]:
acc_glmm_pd_threeReports$trialNo = scale(acc_glmm_pd_threeReports$trialNo, center=TRUE, scale=FALSE) #scale=FALSE
acc_glmm_pd_threeReports

      X     ageNo    subjNo dataType   reportType trialNo   resp
1      0    0younger 0      0withinTrl 0content   -31.51418 1
2      1    0younger 0      0withinTrl 0content   -31.51418 1
3      2    0younger 0      0withinTrl 0content   -31.51418 1
4      3    0younger 0      0withinTrl 0content   -31.51418 1
5      4    0younger 0      0withinTrl 0content   -31.51418 1
6      5    0younger 0      0withinTrl 0content   -29.51418 1
7      6    0younger 0      0withinTrl 0content   -29.51418 1
8      7    0younger 0      0withinTrl 0content   -29.51418 1
9      8    0younger 0      0withinTrl 0content   -29.51418 1
10     9    0younger 0      0withinTrl 0content   -29.51418 1
11    10    0younger 0      0withinTrl 0content   -28.51418 1
12    11    0younger 0      0withinTrl 0content   -28.51418 1
13    12    0younger 0      0withinTrl 0content   -28.51418 1
14    13    0younger 0      0withinTrl 0content   -28.51418 0
15    14    0younger 0      0withinTrl 0content   -28.51418 0
16    15    0younger 0      0withinTrl 0content   -27.51418 1
17    16    0younger 0      0withinTrl 0content   -27.51418 1
18    17    0younger 0      0withinTrl 0content   -27.51418 1
19    18    0younger 0      0withinTrl 0content   -27.51418 1
20    19    0younger 0      0withinTrl 0content   -27.51418 1
21    20    0younger 0      0withinTrl 0content   -25.51418 1
22    21    0younger 0      0withinTrl 0content   -25.51418 1
23    22    0younger 0      0withinTrl 0content   -25.51418 1
24    23    0younger 0      0withinTrl 0content   -25.51418 1
25    24    0younger 0      0withinTrl 0content   -25.51418 1
26    25    0younger 0      0withinTrl 0content   -24.51418 1
27    26    0younger 0      0withinTrl 0content   -24.51418 1
28    27    0younger 0      0withinTrl 0content   -24.51418 1
29    28    0younger 0      0withinTrl 0content   -24.51418 1
30    29    0younger 0      0withinTrl 0content   -24.51418 0
⋮     ⋮     ⋮        ⋮      ⋮          ⋮          ⋮         ⋮
48531 48530 1older   22     0withinTrl 2both      25.48582  0
48532 48531 1older   22     0withinTrl 2both      25.48582  0
48533 48532 1older   22     0withinTrl 2both      25.48582  1
48534 48533 1older   22     0withinTrl 2both      25.48582  1
48535 48534 1older   22     0withinTrl 2both      25.48582  1
48536 48535 1older   22     0withinTrl 2both      26.48582  1
48537 48536 1older   22     0withinTrl 2both      26.48582  0
48538 48537 1older   22     0withinTrl 2both      26.48582  0
48539 48538 1older   22     0withinTrl 2both      26.48582  0
48540 48539 1older   22     0withinTrl 2both      26.48582  0
48541 48540 1older   22     0withinTrl 2both      27.48582  1
48542 48541 1older   22     0withinTrl 2both      27.48582  0
48543 48542 1older   22     0withinTrl 2both      27.48582  0
48544 48543 1older   22     0withinTrl 2both      27.48582  0
48545 48544 1older   22     0withinTrl 2both      27.48582  0
48546 48545 1older   22     0withinTrl 2both      28.48582  0
48547 48546 1older   22     0withinTrl 2both      28.48582  0
48548 48547 1older   22     0withinTrl 2both      28.48582  0
48549 48548 1older   22     0withinTrl 2both      28.48582  0
48550 48549 1older   22     0withinTrl 2both      28.48582  1
48551 48550 1older   22     0withinTrl 2both      29.48582  0
48552 48551 1older   22     0withinTrl 2both      29.48582  0
48553 48552 1older   22     0withinTrl 2both      29.48582  0
48554 48553 1older   22     0withinTrl 2both      29.48582  0
48555 48554 1older   22     0withinTrl 2both      29.48582  0
48556 48555 1older   22     0withinTrl 2both      30.48582  0
48557 48556 1older   22     0withinTrl 2both      30.48582  1
48558 48557 1older   22     0withinTrl 2both      30.48582  0
48559 48558 1older   22     0withinTrl 2both      30.48582  0
48560 48559 1older   22     0withinTrl 2both      30.48582  0

In [42]:
choiceModel <- mixed(resp ~ reportType*ageNo + (1 | subjNo), data = acc_glmm_pd_threeReports, family = binomial, method="LRT")
choiceModel

Contrasts set to contr.sum for the following variables: reportType, ageNo

Mixed Model Anova Table (Type 3 tests, LRT-method)

Model: resp ~ reportType * ageNo + (1 | subjNo)
Data: acc_glmm_pd_threeReports
Df full model: 7
            Effect df       Chisq p.value
1       reportType  2 2226.01 ***   <.001
2            ageNo  1  762.92 ***   <.001
3 reportType:ageNo  2   56.55 ***   <.001
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1

In [43]:
emm1 = emmeans(choiceModel, specs = ~ reportType*ageNo)
emm1

 reportType ageNo    emmean    SE  df asymp.LCL asymp.UCL
 0content   0younger  2.277 0.148 Inf     1.986     2.568
 1position  0younger  1.592 0.146 Inf     1.306     1.879
 2both      0younger  0.937 0.145 Inf     0.653     1.221
 0content   1older    1.825 0.147 Inf     1.537     2.113
 1position  1older    0.655 0.145 Inf     0.371     0.939
 2both      1older   -0.015 0.145 Inf    -0.299     0.269

Results are given on the logit (not the response) scale.
Confidence level used: 0.95

In [44]:
emm_pairs <- pairs(emm1, simple = "reportType", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

ageNo = 0younger:
 contrast             estimate     SE  df z.ratio p.value
 0content - 1position    0.684 0.0553 Inf  12.370  <.0001
 0content - 2both        1.340 0.0526 Inf  25.451  <.0001
 1position - 2both       0.655 0.0459 Inf  14.276  <.0001

ageNo = 1older:
 contrast             estimate     SE  df z.ratio p.value
 0content - 1position    1.170 0.0484 Inf  24.176  <.0001
 0content - 2both        1.840 0.0480 Inf  38.336  <.0001
 1position - 2both       0.670 0.0411 Inf  16.276  <.0001

Results are given on the log odds ratio (not the response) scale.
P value adjustment: bonferroni method for 3 tests

### Memory gradient in the first reporting window (between trials)

In [10]:
# ------ Three reports within a trial ------
acc_glmm_pd_firstWin = acc_glmm_pd[acc_glmm_pd$dataType == '1betweenTrl', ]
acc_glmm_pd_firstWin

      X     ageNo    subjNo dataType    reportType trialNo resp
721   720   0younger 0      1betweenTrl 0content    3      1
722   721   0younger 0      1betweenTrl 0content    3      1
723   722   0younger 0      1betweenTrl 0content    3      1
724   723   0younger 0      1betweenTrl 0content    3      1
725   724   0younger 0      1betweenTrl 0content    3      1
726   725   0younger 0      1betweenTrl 0content    7      1
727   726   0younger 0      1betweenTrl 0content    7      1
728   727   0younger 0      1betweenTrl 0content    7      1
729   728   0younger 0      1betweenTrl 0content    7      1
730   729   0younger 0      1betweenTrl 0content    7      1
731   730   0younger 0      1betweenTrl 0content    8      1
732   731   0younger 0      1betweenTrl 0content    8      1
733   732   0younger 0      1betweenTrl 0content    8      1
734   733   0younger 0      1betweenTrl 0content    8      1
735   734   0younger 0      1betweenTrl 0content    8      0
736   735   0younger 0      1betweenTrl 0content   12      1
737   736   0younger 0      1betweenTrl 0content   12      1
738   737   0younger 0      1betweenTrl 0content   12      1
739   738   0younger 0      1betweenTrl 0content   12      1
740   739   0younger 0      1betweenTrl 0content   12      1
741   740   0younger 0      1betweenTrl 0content   13      1
742   741   0younger 0      1betweenTrl 0content   13      1
743   742   0younger 0      1betweenTrl 0content   13      1
744   743   0younger 0      1betweenTrl 0content   13      1
745   744   0younger 0      1betweenTrl 0content   13      1
746   745   0younger 0      1betweenTrl 0content   14      1
747   746   0younger 0      1betweenTrl 0content   14      1
748   747   0younger 0      1betweenTrl 0content   14      1
749   748   0younger 0      1betweenTrl 0content   14      1
750   749   0younger 0      1betweenTrl 0content   14      1
⋮     ⋮     ⋮        ⋮      ⋮           ⋮          ⋮       ⋮
48851 48850 1older   22     1betweenTrl 2both      41      1
48852 48851 1older   22     1betweenTrl 2both      41      0
48853 48852 1older   22     1betweenTrl 2both      41      1
48854 48853 1older   22     1betweenTrl 2both      41      1
48855 48854 1older   22     1betweenTrl 2both      41      1
48856 48855 1older   22     1betweenTrl 2both      42      1
48857 48856 1older   22     1betweenTrl 2both      42      0
48858 48857 1older   22     1betweenTrl 2both      42      1
48859 48858 1older   22     1betweenTrl 2both      42      1
48860 48859 1older   22     1betweenTrl 2both      42      1
48861 48860 1older   22     1betweenTrl 2both      55      0
48862 48861 1older   22     1betweenTrl 2both      55      0
48863 48862 1older   22     1betweenTrl 2both      55      1
48864 48863 1older   22     1betweenTrl 2both      55      1
48865 48864 1older   22     1betweenTrl 2both      55      1
48866 48865 1older   22     1betweenTrl 2both      56      1
48867 48866 1older   22     1betweenTrl 2both      56      0
48868 48867 1older   22     1betweenTrl 2both      56      1
48869 48868 1older   22     1betweenTrl 2both      56      0
48870 48869 1older   22     1betweenTrl 2both      56      0
48871 48870 1older   22     1betweenTrl 2both      57      0
48872 48871 1older   22     1betweenTrl 2both      57      0
48873 48872 1older   22     1betweenTrl 2both      57      1
48874 48873 1older   22     1betweenTrl 2both      57      1
48875 48874 1older   22     1betweenTrl 2both      57      1
48876 48875 1older   22     1betweenTrl 2both      64      0
48877 48876 1older   22     1betweenTrl 2both      64      0
48878 48877 1older   22     1betweenTrl 2both      64      1
48879 48878 1older   22     1betweenTrl 2both      64      1
48880 48879 1older   22     1betweenTrl 2both      64      1

In [11]:
acc_glmm_pd_firstWin$trialNo = scale(acc_glmm_pd_firstWin$trialNo, center=TRUE, scale=FALSE) #scale=FALSE
acc_glmm_pd_firstWin

      X     ageNo    subjNo dataType    reportType trialNo resp
721   720   0younger 0      1betweenTrl 0content   -29.5   1
722   721   0younger 0      1betweenTrl 0content   -29.5   1
723   722   0younger 0      1betweenTrl 0content   -29.5   1
724   723   0younger 0      1betweenTrl 0content   -29.5   1
725   724   0younger 0      1betweenTrl 0content   -29.5   1
726   725   0younger 0      1betweenTrl 0content   -25.5   1
727   726   0younger 0      1betweenTrl 0content   -25.5   1
728   727   0younger 0      1betweenTrl 0content   -25.5   1
729   728   0younger 0      1betweenTrl 0content   -25.5   1
730   729   0younger 0      1betweenTrl 0content   -25.5   1
731   730   0younger 0      1betweenTrl 0content   -24.5   1
732   731   0younger 0      1betweenTrl 0content   -24.5   1
733   732   0younger 0      1betweenTrl 0content   -24.5   1
734   733   0younger 0      1betweenTrl 0content   -24.5   1
735   734   0younger 0      1betweenTrl 0content   -24.5   0
736   735   0younger 0      1betweenTrl 0content   -20.5   1
737   736   0younger 0      1betweenTrl 0content   -20.5   1
738   737   0younger 0      1betweenTrl 0content   -20.5   1
739   738   0younger 0      1betweenTrl 0content   -20.5   1
740   739   0younger 0      1betweenTrl 0content   -20.5   1
741   740   0younger 0      1betweenTrl 0content   -19.5   1
742   741   0younger 0      1betweenTrl 0content   -19.5   1
743   742   0younger 0      1betweenTrl 0content   -19.5   1
744   743   0younger 0      1betweenTrl 0content   -19.5   1
745   744   0younger 0      1betweenTrl 0content   -19.5   1
746   745   0younger 0      1betweenTrl 0content   -18.5   1
747   746   0younger 0      1betweenTrl 0content   -18.5   1
748   747   0younger 0      1betweenTrl 0content   -18.5   1
749   748   0younger 0      1betweenTrl 0content   -18.5   1
750   749   0younger 0      1betweenTrl 0content   -18.5   1
⋮     ⋮     ⋮        ⋮      ⋮           ⋮          ⋮       ⋮
48851 48850 1older   22     1betweenTrl 2both       8.5    1
48852 48851 1older   22     1betweenTrl 2both       8.5    0
48853 48852 1older   22     1betweenTrl 2both       8.5    1
48854 48853 1older   22     1betweenTrl 2both       8.5    1
48855 48854 1older   22     1betweenTrl 2both       8.5    1
48856 48855 1older   22     1betweenTrl 2both       9.5    1
48857 48856 1older   22     1betweenTrl 2both       9.5    0
48858 48857 1older   22     1betweenTrl 2both       9.5    1
48859 48858 1older   22     1betweenTrl 2both       9.5    1
48860 48859 1older   22     1betweenTrl 2both       9.5    1
48861 48860 1older   22     1betweenTrl 2both      22.5    0
48862 48861 1older   22     1betweenTrl 2both      22.5    0
48863 48862 1older   22     1betweenTrl 2both      22.5    1
48864 48863 1older   22     1betweenTrl 2both      22.5    1
48865 48864 1older   22     1betweenTrl 2both      22.5    1
48866 48865 1older   22     1betweenTrl 2both      23.5    1
48867 48866 1older   22     1betweenTrl 2both      23.5    0
48868 48867 1older   22     1betweenTrl 2both      23.5    1
48869 48868 1older   22     1betweenTrl 2both      23.5    0
48870 48869 1older   22     1betweenTrl 2both      23.5    0
48871 48870 1older   22     1betweenTrl 2both      24.5    0
48872 48871 1older   22     1betweenTrl 2both      24.5    0
48873 48872 1older   22     1betweenTrl 2both      24.5    1
48874 48873 1older   22     1betweenTrl 2both      24.5    1
48875 48874 1older   22     1betweenTrl 2both      24.5    1
48876 48875 1older   22     1betweenTrl 2both      31.5    0
48877 48876 1older   22     1betweenTrl 2both      31.5    0
48878 48877 1older   22     1betweenTrl 2both      31.5    1
48879 48878 1older   22     1betweenTrl 2both      31.5    1
48880 48879 1older   22     1betweenTrl 2both      31.5    1

In [12]:
choiceModel <- mixed(resp ~ reportType*ageNo + (1 | subjNo), data = acc_glmm_pd_firstWin, family = binomial, method="LRT")
choiceModel

Contrasts set to contr.sum for the following variables: reportType, ageNo

Mixed Model Anova Table (Type 3 tests, LRT-method)

Model: resp ~ reportType * ageNo + (1 | subjNo)
Data: acc_glmm_pd_firstWin
Df full model: 7
            Effect df      Chisq p.value
1       reportType  2 666.30 ***   <.001
2            ageNo  1 401.47 ***   <.001
3 reportType:ageNo  2  26.74 ***   <.001
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1

In [13]:
emm1 = emmeans(choiceModel, specs = ~ reportType*ageNo)
emm1

 reportType ageNo    emmean    SE  df asymp.LCL asymp.UCL
 0content   0younger  2.281 0.141 Inf     2.006     2.557
 1position  0younger  1.686 0.136 Inf     1.420     1.952
 2both      0younger  1.181 0.137 Inf     0.912     1.450
 0content   1older    1.756 0.137 Inf     1.489     2.024
 1position  1older    0.715 0.133 Inf     0.454     0.975
 2both      1older    0.122 0.135 Inf    -0.143     0.387

Results are given on the logit (not the response) scale.
Confidence level used: 0.95

In [14]:
emm_pairs <- pairs(emm1, simple = "reportType", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

ageNo = 0younger:
 contrast             estimate     SE  df z.ratio p.value
 0content - 1position    0.595 0.0799 Inf   7.450  <.0001
 0content - 2both        1.100 0.0825 Inf  13.326  <.0001
 1position - 2both       0.505 0.0741 Inf   6.813  <.0001

ageNo = 1older:
 contrast             estimate     SE  df z.ratio p.value
 0content - 1position    1.042 0.0676 Inf  15.414  <.0001
 0content - 2both        1.634 0.0720 Inf  22.696  <.0001
 1position - 2both       0.592 0.0648 Inf   9.139  <.0001

Results are given on the log odds ratio (not the response) scale.
P value adjustment: bonferroni method for 3 tests

### Memory gradient: partial retrieval from three-retrieval trials and full retrieval from the first reporting window

In [15]:
# ------ Three reports: item and location within trials, reconstruction from the 1st report window (between trials) ------
# Subset for partial reports
acc_glmm_pd_partialReports <- acc_glmm_pd[
  acc_glmm_pd$dataType == "0withinTrl" &
  (acc_glmm_pd$reportType == "0content" | acc_glmm_pd$reportType == "1position"),
]
# Subset for full reports (between trials)
acc_glmm_pd_fullReportsBetween <- acc_glmm_pd[
  acc_glmm_pd$dataType == "1betweenTrl" &
  acc_glmm_pd$reportType == "2both",
]
# Combine them
acc_glmm_pd_combined <- rbind(
  acc_glmm_pd_partialReports,
  acc_glmm_pd_fullReportsBetween
)

acc_glmm_pd_combined$trialNo = scale(acc_glmm_pd_combined$trialNo, center=TRUE, scale=FALSE) #scale=FALSE
acc_glmm_pd_combined

      X     ageNo    subjNo dataType    reportType trialNo   resp
1      0    0younger 0      0withinTrl  0content   -31.50608 1
2      1    0younger 0      0withinTrl  0content   -31.50608 1
3      2    0younger 0      0withinTrl  0content   -31.50608 1
4      3    0younger 0      0withinTrl  0content   -31.50608 1
5      4    0younger 0      0withinTrl  0content   -31.50608 1
6      5    0younger 0      0withinTrl  0content   -29.50608 1
7      6    0younger 0      0withinTrl  0content   -29.50608 1
8      7    0younger 0      0withinTrl  0content   -29.50608 1
9      8    0younger 0      0withinTrl  0content   -29.50608 1
10     9    0younger 0      0withinTrl  0content   -29.50608 1
11    10    0younger 0      0withinTrl  0content   -28.50608 1
12    11    0younger 0      0withinTrl  0content   -28.50608 1
13    12    0younger 0      0withinTrl  0content   -28.50608 1
14    13    0younger 0      0withinTrl  0content   -28.50608 0
15    14    0younger 0      0withinTrl  0content   -28.50608 0
16    15    0younger 0      0withinTrl  0content   -27.50608 1
17    16    0younger 0      0withinTrl  0content   -27.50608 1
18    17    0younger 0      0withinTrl  0content   -27.50608 1
19    18    0younger 0      0withinTrl  0content   -27.50608 1
20    19    0younger 0      0withinTrl  0content   -27.50608 1
21    20    0younger 0      0withinTrl  0content   -25.50608 1
22    21    0younger 0      0withinTrl  0content   -25.50608 1
23    22    0younger 0      0withinTrl  0content   -25.50608 1
24    23    0younger 0      0withinTrl  0content   -25.50608 1
25    24    0younger 0      0withinTrl  0content   -25.50608 1
26    25    0younger 0      0withinTrl  0content   -24.50608 1
27    26    0younger 0      0withinTrl  0content   -24.50608 1
28    27    0younger 0      0withinTrl  0content   -24.50608 1
29    28    0younger 0      0withinTrl  0content   -24.50608 1
30    29    0younger 0      0withinTrl  0content   -24.50608 0
⋮     ⋮     ⋮        ⋮      ⋮           ⋮          ⋮         ⋮
48851 48850 1older   22     1betweenTrl 2both       8.493921 1
48852 48851 1older   22     1betweenTrl 2both       8.493921 0
48853 48852 1older   22     1betweenTrl 2both       8.493921 1
48854 48853 1older   22     1betweenTrl 2both       8.493921 1
48855 48854 1older   22     1betweenTrl 2both       8.493921 1
48856 48855 1older   22     1betweenTrl 2both       9.493921 1
48857 48856 1older   22     1betweenTrl 2both       9.493921 0
48858 48857 1older   22     1betweenTrl 2both       9.493921 1
48859 48858 1older   22     1betweenTrl 2both       9.493921 1
48860 48859 1older   22     1betweenTrl 2both       9.493921 1
48861 48860 1older   22     1betweenTrl 2both      22.493921 0
48862 48861 1older   22     1betweenTrl 2both      22.493921 0
48863 48862 1older   22     1betweenTrl 2both      22.493921 1
48864 48863 1older   22     1betweenTrl 2both      22.493921 1
48865 48864 1older   22     1betweenTrl 2both      22.493921 1
48866 48865 1older   22     1betweenTrl 2both      23.493921 1
48867 48866 1older   22     1betweenTrl 2both      23.493921 0
48868 48867 1older   22     1betweenTrl 2both      23.493921 1
48869 48868 1older   22     1betweenTrl 2both      23.493921 0
48870 48869 1older   22     1betweenTrl 2both      23.493921 0
48871 48870 1older   22     1betweenTrl 2both      24.493921 0
48872 48871 1older   22     1betweenTrl 2both      24.493921 0
48873 48872 1older   22     1betweenTrl 2both      24.493921 1
48874 48873 1older   22     1betweenTrl 2both      24.493921 1
48875 48874 1older   22     1betweenTrl 2both      24.493921 1
48876 48875 1older   22     1betweenTrl 2both      31.493921 0
48877 48876 1older   22     1betweenTrl 2both      31.493921 0
48878 48877 1older   22     1betweenTrl 2both      31.493921 1
48879 48878 1older   22     1betweenTrl 2both      31.493921 1
48880 48879 1older   22     1betweenTrl 2both      31.493921 1

In [16]:
choiceModel <- mixed(resp ~ reportType*ageNo + (1 | subjNo), data = acc_glmm_pd_combined, family = binomial, method="LRT")
choiceModel

Contrasts set to contr.sum for the following variables: reportType, ageNo

Mixed Model Anova Table (Type 3 tests, LRT-method)

Model: resp ~ reportType * ageNo + (1 | subjNo)
Data: acc_glmm_pd_combined
Df full model: 7
            Effect df       Chisq p.value
1       reportType  2 1084.56 ***   <.001
2            ageNo  1  551.94 ***   <.001
3 reportType:ageNo  2   58.22 ***   <.001
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1

In [17]:
emm1 = emmeans(choiceModel, specs = ~ reportType*ageNo)
emm1

 reportType ageNo    emmean    SE  df asymp.LCL asymp.UCL
 0content   0younger  2.255 0.138 Inf     1.984     2.527
 1position  0younger  1.573 0.136 Inf     1.306     1.839
 2both      0younger  1.189 0.142 Inf     0.910     1.468
 0content   1older    1.810 0.137 Inf     1.541     2.078
 1position  1older    0.647 0.135 Inf     0.383     0.911
 2both      1older    0.124 0.140 Inf    -0.151     0.399

Results are given on the logit (not the response) scale.
Confidence level used: 0.95

In [18]:
emm_pairs <- pairs(emm1, simple = "reportType", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

ageNo = 0younger:
 contrast             estimate     SE  df z.ratio p.value
 0content - 1position    0.683 0.0553 Inf  12.351  <.0001
 0content - 2both        1.066 0.0695 Inf  15.334  <.0001
 1position - 2both       0.384 0.0646 Inf   5.943  <.0001

ageNo = 1older:
 contrast             estimate     SE  df z.ratio p.value
 0content - 1position    1.163 0.0483 Inf  24.079  <.0001
 0content - 2both        1.686 0.0624 Inf  27.008  <.0001
 1position - 2both       0.523 0.0572 Inf   9.129  <.0001

Results are given on the log odds ratio (not the response) scale.
P value adjustment: bonferroni method for 3 tests

## Figure 2C: Decline change percentage (older minus younger) across three learning curriculums

### Memory drop: based on three-retrieval trials

In [19]:
path_or_buf <- paste0(FBdata_folder, 'Fig2C_acc_change_conds_threeRetr_group_stats_Exp2.csv') 
acc_lmm_pd_cond_threeRetr <- read.csv(file = path_or_buf)
acc_lmm_pd_cond_threeRetr

     X    ageNo  subjNo trialNo measNo   accuracy_change order
1     0   1older 0       1      0content  0.1225882      1second
2     1   1older 0       2      0content  0.1225882      0first
3     2   1older 0       3      0content  0.1225882      1second
4     3   1older 0       4      0content  0.1225882      0first
5     4   1older 0       6      0content  0.1225882      0first
6     5   1older 0       8      0content  0.1225882      1second
7     6   1older 0       9      0content  0.1225882      1second
8     7   1older 0      10      0content  0.1225882      1second
9     8   1older 0      12      0content  0.1225882      0first
10    9   1older 0      13      0content  0.1225882      0first
11   10   1older 0      14      0content  0.1225882      1second
12   11   1older 0      15      0content  0.1225882      1second
13   12   1older 0      17      0content  0.1225882      0first
14   13   1older 0      18      0content  0.1225882      1second
15   14   1older 0      20      0content  0.1225882      0first
16   15   1older 0      21      0content  0.1225882      1second
17   16   1older 0      22      0content  0.1225882      0first
18   17   1older 0      23      0content  0.1225882      1second
19   18   1older 0      25      0content  0.1225882      1second
20   19   1older 0      26      0content -0.1019294      1second
21   20   1older 0      27      0content  0.1225882      0first
22   21   1older 0      28      0content -0.1019294      0first
23   22   1older 0      31      0content  0.1225882      1second
24   23   1older 0      32      0content  0.1225882      0first
25   24   1older 0      33      0content  0.1225882      1second
26   25   1older 0      34      0content  0.1225882      0first
27   26   1older 0      35      0content  0.1225882      1second
28   27   1older 0      36      0content  0.1225882      0first
29   28   1older 0      37      0content  0.1225882      0first
30   29   1older 0      38      0content  0.1225882      0first
⋮    ⋮    ⋮      ⋮      ⋮       ⋮        ⋮               ⋮
3283 3282 1older 22     25      2both    -1.0000000      2third
3284 3283 1older 22     26      2both     0.1445604      2third
3285 3284 1older 22     27      2both    -0.7138599      2third
3286 3285 1older 22     28      2both    -0.7138599      2third
3287 3286 1older 22     29      2both    -0.7138599      2third
3288 3287 1older 22     32      2both     0.4307004      2third
3289 3288 1older 22     33      2both    -0.4277198      2third
3290 3289 1older 22     34      2both    -1.0000000      2third
3291 3290 1older 22     35      2both     0.1445604      2third
3292 3291 1older 22     37      2both     0.1445604      2third
3293 3292 1older 22     39      2both    -0.7138599      2third
3294 3293 1older 22     40      2both    -0.7138599      2third
3295 3294 1older 22     43      2both    -1.0000000      2third
3296 3295 1older 22     44      2both    -1.0000000      2third
3297 3296 1older 22     45      2both    -1.0000000      2third
3298 3297 1older 22     46      2both    -0.1415797      2third
3299 3298 1older 22     47      2both    -0.4277198      2third
3300 3299 1older 22     48      2both    -0.7138599      2third
3301 3300 1older 22     49      2both    -1.0000000      2third
3302 3301 1older 22     50      2both    -0.1415797      2third
3303 3302 1older 22     51      2both     0.4307004      2third
3304 3303 1older 22     52      2both    -0.7138599      2third
3305 3304 1older 22     53      2both    -0.4277198      2third
3306 3305 1older 22     54      2both    -0.4277198      2third
3307 3306 1older 22     58      2both    -0.1415797      2third
3308 3307 1older 22     59      2both    -0.7138599      2third
3309 3308 1older 22     60      2both    -0.7138599      2third
3310 3309 1older 22     61      2both    -0.7138599      2third
3311 3310 1older 22     62      2both    -1.0000000      2third
3312 3311 1older 22     63      2both    -0.7138599      2third

In [20]:
accModel_comp <- lmer(accuracy_change ~ measNo + (1 + measNo| subjNo), data = acc_lmm_pd_cond_threeRetr) # *measNo

In [21]:
summary(accModel_comp)

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: accuracy_change ~ measNo + (1 + measNo | subjNo)
   Data: acc_lmm_pd_cond_threeRetr

REML criterion at convergence: 2461.8

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.6910 -0.5744  0.1743  0.5421  2.9396

Random effects:
 Groups   Name            Variance Std.Dev. Corr
 subjNo   (Intercept)     0.03519  0.1876
          measNo1position 0.04974  0.2230   -0.18
          measNo2both     0.10883  0.3299   -0.03  0.95
 Residual                 0.11635  0.3411
Number of obs: 3312, groups:  subjNo, 23

Fixed effects:
                Estimate Std. Error       df t value Pr(>|t|)
(Intercept)     -0.05312    0.04044 22.00005  -1.314  0.20254
measNo1position -0.14856    0.04872 22.00557  -3.049  0.00588 **
measNo2both     -0.23075    0.07030 22.00480  -3.282  0.00340 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) msN1ps
measNo1pstn -0.223
measNo2both -0.062  0.918

In [22]:
anova(accModel_comp, ddf='Satterthwaite')

       Sum Sq   Mean Sq   NumDF DenDF    F value  Pr(>F)
measNo 1.254372 0.6271859 2     22.00382 5.390373 0.01243897

In [24]:
emm_options(lmerTest.limit = 3312)
emm1 = emmeans(accModel_comp, specs = ~ measNo, lmer.df = "satterthwaite") # specs = ~ groupNo*measNo; same as: emmeans(choiceModel, ~ networkName) & emmeans(choiceModel, c("networkName"))
emm1

 measNo     emmean     SE df lower.CL upper.CL
 0content  -0.0531 0.0404 22   -0.137   0.0307
 1position -0.2017 0.0559 22   -0.318  -0.0857
 2both     -0.2839 0.0789 22   -0.448  -0.1202

Degrees-of-freedom method: satterthwaite
Confidence level used: 0.95

In [25]:
emm_pairs <- pairs(emm1, simple = "measNo", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

 contrast             estimate     SE df t.ratio p.value
 0content - 1position   0.1486 0.0487 22   3.049  0.0176
 0content - 2both       0.2308 0.0703 22   3.282  0.0102
 1position - 2both      0.0822 0.0320 22   2.566  0.0528

Degrees-of-freedom method: satterthwaite
P value adjustment: bonferroni method for 3 tests

### Memory drop: based on retrievals in the first reporting window

In [26]:
path_or_buf <- paste0(FBdata_folder, 'Fig2C_acc_change_conds_firstWin_group_stats_Exp2.csv') 
acc_lmm_pd_conds_firstWin <- read.csv(file = path_or_buf)
acc_lmm_pd_conds_firstWin

     X    ageNo  subjNo trialNo measNo    accuracy_change order
1     0   1older 0       2      0content   0.11885610     0first
2     1   1older 0       4      0content   0.11885610     0first
3     2   1older 0       6      0content   0.11885610     0first
4     3   1older 0      12      0content   0.11885610     0first
5     4   1older 0      13      0content   0.11885610     0first
6     5   1older 0      17      0content   0.11885610     0first
7     6   1older 0      20      0content   0.11885610     0first
8     7   1older 0      22      0content   0.11885610     0first
9     8   1older 0      27      0content   0.11885610     0first
10    9   1older 0      28      0content  -0.10491512     0first
11   10   1older 0      32      0content   0.11885610     0first
12   11   1older 0      34      0content   0.11885610     0first
13   12   1older 0      36      0content   0.11885610     0first
14   13   1older 0      37      0content   0.11885610     0first
15   14   1older 0      38      0content   0.11885610     0first
16   15   1older 0      43      0content   0.11885610     0first
17   16   1older 0      44      0content   0.11885610     0first
18   17   1older 0      45      0content   0.11885610     0first
19   18   1older 0      51      0content   0.11885610     0first
20   19   1older 0      52      0content   0.11885610     0first
21   20   1older 0      55      0content   0.11885610     0first
22   21   1older 0      63      0content   0.11885610     0first
23   22   1older 0      64      0content   0.11885610     0first
24   23   1older 0       1      1position  0.20610129     0first
25   24   1older 0       3      1position -0.27633922     0first
26   25   1older 0       8      1position -0.51755948     0first
27   26   1older 0       9      1position -0.75877974     0first
28   27   1older 0      10      1position -0.27633922     0first
29   28   1older 0      14      1position -0.03511897     0first
30   29   1older 0      15      1position -0.51755948     0first
⋮    ⋮    ⋮      ⋮      ⋮       ⋮         ⋮               ⋮
1443 1442 1older 22     27      1position -0.51755948     0first
1444 1443 1older 22     29      1position -0.51755948     0first
1445 1444 1older 22     33      1position  0.20610129     0first
1446 1445 1older 22     37      1position -0.03511897     0first
1447 1446 1older 22     39      1position -0.51755948     0first
1448 1447 1older 22     43      1position -0.51755948     0first
1449 1448 1older 22     46      1position  0.20610129     0first
1450 1449 1older 22     47      1position -0.75877974     0first
1451 1450 1older 22     50      1position -0.75877974     0first
1452 1451 1older 22     51      1position -0.75877974     0first
1453 1452 1older 22     54      1position -0.27633922     0first
1454 1453 1older 22     58      1position -0.27633922     0first
1455 1454 1older 22     60      1position -0.51755948     0first
1456 1455 1older 22     62      1position -0.27633922     0first
1457 1456 1older 22      2      2both     -0.73277662     0first
1458 1457 1older 22      5      2both     -0.46555324     0first
1459 1458 1older 22     13      2both     -0.46555324     0first
1460 1459 1older 22     16      2both     -0.46555324     0first
1461 1460 1older 22     17      2both     -0.73277662     0first
1462 1461 1older 22     24      2both     -0.19832985     0first
1463 1462 1older 22     30      2both     -0.19832985     0first
1464 1463 1older 22     31      2both      0.33611691     0first
1465 1464 1older 22     36      2both     -0.19832985     0first
1466 1465 1older 22     38      2both      0.06889353     0first
1467 1466 1older 22     41      2both      0.06889353     0first
1468 1467 1older 22     42      2both      0.06889353     0first
1469 1468 1older 22     55      2both     -0.19832985     0first
1470 1469 1older 22     56      2both     -0.46555324     0first
1471 1470 1older 22     57      2both     -0.19832985     0first
1472 1471 1older 22     64      2both     -0.19832985     0first

In [27]:
accModel_comp <- lmer(accuracy_change ~ measNo + (1 + measNo| subjNo), data = acc_lmm_pd_conds_firstWin) # *measNo

In [28]:
summary(accModel_comp)

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: accuracy_change ~ measNo + (1 + measNo | subjNo)
   Data: acc_lmm_pd_conds_firstWin

REML criterion at convergence: 945.7

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.4332 -0.5218  0.2215  0.5608  2.5745

Random effects:
 Groups   Name            Variance Std.Dev. Corr
 subjNo   (Intercept)     0.03566  0.1888
          measNo1position 0.04323  0.2079   -0.19
          measNo2both     0.08945  0.2991   -0.16  0.84
 Residual                 0.09983  0.3160
Number of obs: 1472, groups:  subjNo, 23

Fixed effects:
                Estimate Std. Error       df t value Pr(>|t|)
(Intercept)     -0.06343    0.04157 21.89095  -1.526  0.14138
measNo1position -0.13369    0.04736 22.01952  -2.823  0.00991 **
measNo2both     -0.22567    0.06587 21.98169  -3.426  0.00242 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) msN1ps
measNo1pstn -0.253
measNo2both -0.208  0.785

In [29]:
anova(accModel_comp, ddf='Satterthwaite')

       Sum Sq   Mean Sq  NumDF DenDF    F value  Pr(>F)
measNo 1.176544 0.588272 2     21.92218 5.892997 0.008951673

In [30]:
emm1 = emmeans(accModel_comp, specs = ~ measNo, lmer.df = "satterthwaite") # specs = ~ groupNo*measNo; same as: emmeans(choiceModel, ~ networkName) & emmeans(choiceModel, c("networkName"))
emm1

 measNo     emmean     SE   df lower.CL upper.CL
 0content  -0.0634 0.0416 21.9   -0.150   0.0228
 1position -0.1971 0.0546 22.0   -0.310  -0.0840
 2both     -0.2891 0.0702 22.0   -0.435  -0.1435

Degrees-of-freedom method: satterthwaite
Confidence level used: 0.95

In [31]:
emm_pairs <- pairs(emm1, simple = "measNo", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

 contrast             estimate     SE df t.ratio p.value
 0content - 1position    0.134 0.0474 22   2.823  0.0297
 0content - 2both        0.226 0.0659 22   3.426  0.0073
 1position - 2both       0.092 0.0411 22   2.240  0.1066

Degrees-of-freedom method: satterthwaite
P value adjustment: bonferroni method for 3 tests

### Memory drop: based on all trials

In [32]:
path_or_buf <- paste0(FBdata_folder, 'Fig2C_acc_change_conds_group_stats_Exp2.csv') 
acc_lmm_pd_conds <- read.csv(file = path_or_buf)
acc_lmm_pd_conds

     X    ageNo  subjNo trialNo measNo   accuracy_change order
1     0   1older 0       1      0content  0.1225882      1second
2     1   1older 0       2      0content  0.1225882      0first
3     2   1older 0       3      0content  0.1225882      1second
4     3   1older 0       4      0content  0.1225882      0first
5     4   1older 0       6      0content  0.1225882      0first
6     5   1older 0       8      0content  0.1225882      1second
7     6   1older 0       9      0content  0.1225882      1second
8     7   1older 0      10      0content  0.1225882      1second
9     8   1older 0      12      0content  0.1225882      0first
10    9   1older 0      13      0content  0.1225882      0first
11   10   1older 0      14      0content  0.1225882      1second
12   11   1older 0      15      0content  0.1225882      1second
13   12   1older 0      17      0content  0.1225882      0first
14   13   1older 0      18      0content  0.1225882      1second
15   14   1older 0      20      0content  0.1225882      0first
16   15   1older 0      21      0content  0.1225882      1second
17   16   1older 0      22      0content  0.1225882      0first
18   17   1older 0      23      0content  0.1225882      1second
19   18   1older 0      25      0content  0.1225882      1second
20   19   1older 0      26      0content -0.1019294      1second
21   20   1older 0      27      0content  0.1225882      0first
22   21   1older 0      28      0content -0.1019294      0first
23   22   1older 0      31      0content  0.1225882      1second
24   23   1older 0      32      0content  0.1225882      0first
25   24   1older 0      33      0content  0.1225882      1second
26   25   1older 0      34      0content  0.1225882      0first
27   26   1older 0      35      0content  0.1225882      1second
28   27   1older 0      36      0content  0.1225882      0first
29   28   1older 0      37      0content  0.1225882      0first
30   29   1older 0      38      0content  0.1225882      0first
⋮    ⋮    ⋮      ⋮      ⋮       ⋮        ⋮               ⋮
3651 3650 1older 22     35      2both     0.1246568      2third
3652 3651 1older 22     36      2both    -0.1565074      0first
3653 3652 1older 22     37      2both     0.1246568      2third
3654 3653 1older 22     38      2both     0.1246568      0first
3655 3654 1older 22     39      2both    -0.7188358      2third
3656 3655 1older 22     40      2both    -0.7188358      2third
3657 3656 1older 22     41      2both     0.1246568      0first
3658 3657 1older 22     42      2both     0.1246568      0first
3659 3658 1older 22     43      2both    -1.0000000      2third
3660 3659 1older 22     44      2both    -1.0000000      2third
3661 3660 1older 22     45      2both    -1.0000000      2third
3662 3661 1older 22     46      2both    -0.1565074      2third
3663 3662 1older 22     47      2both    -0.4376716      2third
3664 3663 1older 22     48      2both    -0.7188358      2third
3665 3664 1older 22     49      2both    -1.0000000      2third
3666 3665 1older 22     50      2both    -0.1565074      2third
3667 3666 1older 22     51      2both     0.4058210      2third
3668 3667 1older 22     52      2both    -0.7188358      2third
3669 3668 1older 22     53      2both    -0.4376716      2third
3670 3669 1older 22     54      2both    -0.4376716      2third
3671 3670 1older 22     55      2both    -0.1565074      0first
3672 3671 1older 22     56      2both    -0.4376716      0first
3673 3672 1older 22     57      2both    -0.1565074      0first
3674 3673 1older 22     58      2both    -0.1565074      2third
3675 3674 1older 22     59      2both    -0.7188358      2third
3676 3675 1older 22     60      2both    -0.7188358      2third
3677 3676 1older 22     61      2both    -0.7188358      2third
3678 3677 1older 22     62      2both    -1.0000000      2third
3679 3678 1older 22     63      2both    -0.7188358      2third
3680 3679 1older 22     64      2both    -0.1565074      0first

In [33]:
accModel_comp <- lmer(accuracy_change ~ measNo + (1 + measNo| subjNo), data = acc_lmm_pd_conds) # *measNo

In [34]:
summary(accModel_comp)

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: accuracy_change ~ measNo + (1 + measNo | subjNo)
   Data: acc_lmm_pd_conds

REML criterion at convergence: 2871.8

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.5911 -0.6387  0.1612  0.5675  2.9101

Random effects:
 Groups   Name            Variance Std.Dev. Corr
 subjNo   (Intercept)     0.03509  0.1873
          measNo1position 0.04956  0.2226   -0.18
          measNo2both     0.10066  0.3173   -0.06  0.94
 Residual                 0.12124  0.3482
Number of obs: 3680, groups:  subjNo, 23

Fixed effects:
                Estimate Std. Error       df t value Pr(>|t|)
(Intercept)     -0.05312    0.04044 21.99780  -1.313  0.20256
measNo1position -0.14856    0.04873 21.99149  -3.049  0.00589 **
measNo2both     -0.23213    0.06759 21.99262  -3.434  0.00237 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) msN1ps
measNo1pstn -0.223
measNo2both -0.098  0.909

In [35]:
anova(accModel_comp, ddf='Satterthwaite')

       Sum Sq   Mean Sq   NumDF DenDF    F value Pr(>F)
measNo 1.433703 0.7168517 2     21.99428 5.91284 0.008811255

In [37]:
emm_options(lmerTest.limit = 3680)
emm1 = emmeans(accModel_comp, specs = ~ measNo, lmer.df = "satterthwaite") # specs = ~ groupNo*measNo; same as: emmeans(choiceModel, ~ networkName) & emmeans(choiceModel, c("networkName"))
emm1

 measNo     emmean     SE df lower.CL upper.CL
 0content  -0.0531 0.0404 22   -0.137   0.0308
 1position -0.2017 0.0559 22   -0.318  -0.0856
 2both     -0.2852 0.0753 22   -0.441  -0.1291

Degrees-of-freedom method: satterthwaite
Confidence level used: 0.95

In [38]:
emm_pairs <- pairs(emm1, simple = "measNo", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

 contrast             estimate     SE df t.ratio p.value
 0content - 1position   0.1486 0.0487 22   3.049  0.0177
 0content - 2both       0.2321 0.0676 22   3.434  0.0071
 1position - 2both      0.0836 0.0309 22   2.708  0.0385

Degrees-of-freedom method: satterthwaite
P value adjustment: bonferroni method for 3 tests

# Exp1 and Exp2:  False alarm (FA), Transition accuracy and Binding related statistical tests

Extract the data based on experiments (Exp1 or Exp2) or data collapse (Exp1 + Exp2)

In [3]:
dataFlg <- 3

if (dataFlg == 1) {        # Experiment 1
  # ------ Figure 2D: FA of lure items ------
  FA_lure_name      <- 'Fig2D_FA_lure_overall_YAOA_stats_Exp1.csv'

  # ------ Figure 2E: Transition accuracy ------
  transAcc_name     <- 'Fig2E_transAcc_overall_group_stats_Exp1.csv'

  # ------ Figure 2G: Binding measures (conditional probability) ------
  bindsOverall_name <- 'Fig2G_binds_overall_group_stats_Exp1.csv'

  # ------ Figure 2HI: Binding-related measures ------
  bindsDiff_name    <- 'Fig2HI_binds_overall_diff_group_stats_Exp1.csv'

} else if (dataFlg == 2) { # Experiment 2
  FA_lure_name      <- 'Fig2D_FA_lure_overall_YAOA_stats_Exp2.csv'
  transAcc_name     <- 'Fig2E_transAcc_overall_group_stats_Exp2.csv'
  bindsOverall_name <- 'Fig2G_binds_overall_group_stats_Exp2.csv'
  bindsDiff_name    <- 'Fig2HI_binds_overall_diff_group_stats_Exp2.csv'

} else if (dataFlg == 3) { # Exp1 + Exp2
  FA_lure_name      <- 'Fig2D_FA_lure_overall_YAOA_stats_Exp12.csv'
  transAcc_name     <- 'Fig2E_transAcc_overall_group_stats_Exp12.csv'
  bindsOverall_name <- 'Fig2G_binds_overall_group_stats_Exp12.csv'
  bindsDiff_name    <- 'Fig2HI_binds_overall_diff_group_stats_Exp12.csv'
}

## Figure 2D: false alarm rate

In [4]:
path_or_buf  <- paste0(FBdata_folder, FA_lure_name)
FA_lmm_pd <- read.csv(file = path_or_buf)
FA_lmm_pd

    X   groupNo  subjNo reportType reportDim FArates
1    0  0younger  0     0marg      0Item     0.078125
2    1  0younger  1     0marg      0Item     0.015625
3    2  0younger  2     0marg      0Item     0.015625
4    3  0younger  3     0marg      0Item     0.000000
5    4  0younger  4     0marg      0Item     0.015625
6    5  0younger  5     0marg      0Item     0.000000
7    6  0younger  6     0marg      0Item     0.078125
8    7  0younger  7     0marg      0Item     0.015625
9    8  0younger  8     0marg      0Item     0.046875
10   9  0younger  9     0marg      0Item     0.015625
11  10  0younger 10     0marg      0Item     0.046875
12  11  0younger 11     0marg      0Item     0.375000
13  12  0younger 12     0marg      0Item     0.109375
14  13  0younger 13     0marg      0Item     0.031250
15  14  0younger 14     0marg      0Item     0.078125
16  15  0younger 15     0marg      0Item     0.078125
17  16  0younger 16     0marg      0Item     0.015625
18  17  0younger 17     0marg      0Item     0.031250
19  18  0younger 18     0marg      0Item     0.562500
20  19  0younger 19     0marg      0Item     0.125000
21  20  0younger 20     0marg      0Item     0.031250
22  21  0younger 21     0marg      0Item     0.015625
23  22  0younger 22     0marg      0Item     0.109375
24  23  0younger 23     0marg      0Item     0.031250
25  24  0younger 24     0marg      0Item     0.000000
26  25  0younger 25     0marg      0Item     0.015625
27  26  0younger 26     0marg      0Item     0.000000
28  27  0younger 27     0marg      0Item     0.000000
29  28  0younger 28     0marg      0Item     0.031250
30  29  0younger 29     0marg      0Item     0.171875
⋮   ⋮   ⋮        ⋮      ⋮          ⋮         ⋮
423 422 1older   20     1recons    1Pos      0.640625
424 423 1older   21     1recons    1Pos      0.531250
425 424 1older   22     1recons    1Pos      0.312500
426 425 1older   23     1recons    1Pos      0.546875
427 426 1older   24     1recons    1Pos      0.796875
428 427 1older   25     1recons    1Pos      0.484375
429 428 1older   26     1recons    1Pos      0.531250
430 429 1older   27     1recons    1Pos      0.187500
431 430 1older   28     1recons    1Pos      0.218750
432 431 1older   29     1recons    1Pos      0.156250
433 432 1older   30     1recons    1Pos      0.234375
434 433 1older   31     1recons    1Pos      0.453125
435 434 1older   32     1recons    1Pos      0.500000
436 435 1older   33     1recons    1Pos      0.250000
437 436 1older   34     1recons    1Pos      0.781250
438 437 1older   35     1recons    1Pos      0.500000
439 438 1older   36     1recons    1Pos      0.171875
440 439 1older   37     1recons    1Pos      0.093750
441 440 1older   38     1recons    1Pos      0.656250
442 441 1older   39     1recons    1Pos      0.656250
443 442 1older   40     1recons    1Pos      0.015625
444 443 1older   41     1recons    1Pos      0.156250
445 444 1older   42     1recons    1Pos      0.437500
446 445 1older   43     1recons    1Pos      0.406250
447 446 1older   44     1recons    1Pos      0.453125
448 447 1older   45     1recons    1Pos      0.781250
449 448 1older   46     1recons    1Pos      0.609375
450 449 1older   47     1recons    1Pos      0.031250
451 450 1older   48     1recons    1Pos      0.656250
452 451 1older   49     1recons    1Pos      0.578125

In [5]:
# column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'reportDim', 4: 'FArates'} 
FA_model <- lmer(FArates ~ groupNo*reportType*reportDim + (1 | subjNo), data = FA_lmm_pd)

In [6]:
summary(FA_model)

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: FArates ~ groupNo * reportType * reportDim + (1 | subjNo)
   Data: FA_lmm_pd

REML criterion at convergence: -272.3

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.56518 -0.60411 -0.07041  0.46994  3.14113

Random effects:
 Groups   Name        Variance Std.Dev.
 subjNo   (Intercept) 0.01228  0.1108
 Residual             0.02383  0.1544
Number of obs: 452, groups:  subjNo, 63

Fixed effects:
                                                Estimate Std. Error         df
(Intercept)                                    7.961e-02  2.394e-02  2.452e+02
groupNo1older                                  1.254e-01  2.952e-02  3.833e+02
reportType1recons                              3.497e-02  2.750e-02  3.769e+02
reportDim1Pos                                  8.854e-02  2.750e-02  3.769e+02
groupNo1older:reportType1recons                7.589e-04  4.135e-02  3.769e+02
groupNo1older:reportDim1Pos                    1.927e-01  4.135e-02  3.769e+02
reportType1recons:reportDim1Pos               -2.480e-02  3.890e-02  3.769e+02
groupNo1older:reportType1recons:reportDim1Pos -1.832e-02  5.847e-02  3.769e+02
                                              t value Pr(>|t|)
(Intercept)                                     3.325  0.00102 **
groupNo1older                                   4.247 2.72e-05 ***
reportType1recons                               1.271  0.20435
reportDim1Pos                                   3.219  0.00140 **
groupNo1older:reportType1recons                 0.018  0.98537
groupNo1older:reportDim1Pos                     4.661 4.38e-06 ***
reportType1recons:reportDim1Pos                -0.638  0.52411
groupNo1older:reportType1recons:reportDim1Pos  -0.313  0.75418
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) grpN1l rprtT1 rprD1P grN1:T1 gN1:D1 rT1:D1
groupNo1ldr -0.535
rprtTyp1rcn -0.574  0.466
reportDm1Ps -0.574  0.466  0.500
grpN1ldr:T1  0.382 -0.700 -0.665 -0.333
grpN1ld:D1P  0.382 -0.700 -0.333 -0.665  0.500
rprtTy1:D1P  0.406 -0.329 -0.707 -0.707  0.470   0.470
grN1:T1:D1P -0.270  0.495  0.470  0.470 -0.707  -0.707 -0.665

In [7]:
anova(FA_model, ddf='Satterthwaite')

                             Sum Sq      Mean Sq     NumDF DenDF
groupNo                      4.896271050 4.896271050 1     400.2370
reportType                   0.037619972 0.037619972 1     376.8911
reportDim                    3.143886662 3.143886662 1     376.8911
groupNo:reportType           0.001968239 0.001968239 1     376.8911
groupNo:reportDim            0.939128296 0.939128296 1     376.8911
reportType:reportDim         0.032155237 0.032155237 1     376.8911
groupNo:reportType:reportDim 0.002339833 0.002339833 1     376.8911
                             F value      Pr(>F)
groupNo                      205.47331437 6.642251e-38
reportType                     1.57873212 2.097216e-01
reportDim                    131.93403834 2.182993e-26
groupNo:reportType             0.08259768 7.739655e-01
groupNo:reportDim             39.41076825 9.455053e-10
reportType:reportDim           1.34940304 2.461176e-01
groupNo:reportType:reportDim   0.09819171 7.541839e-01

In [8]:
#emm_options(lmerTest.limit = 4000)
emm1 = emmeans(FA_model, specs = ~ reportDim, lmer.df = "satterthwaite") # groupNo*reportType*bindConds
emm1

NOTE: Results may be misleading due to involvement in interactions

 reportDim emmean     SE   df lower.CL upper.CL
 0Item      0.160 0.0175 83.8    0.125    0.195
 1Pos       0.328 0.0175 83.8    0.293    0.363

Results are averaged over the levels of: groupNo, reportType
Degrees-of-freedom method: satterthwaite
Confidence level used: 0.95

In [9]:
emm_pairs <- pairs(emm1, simple = "reportDim", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

 contrast     estimate     SE  df t.ratio p.value
 0Item - 1Pos   -0.168 0.0146 377 -11.486  <.0001

Results are averaged over the levels of: groupNo, reportType
Degrees-of-freedom method: satterthwaite

## Figure 2E: transition accuracy

In [10]:
path_or_buf  <- paste0(FBdata_folder, transAcc_name)
transAcc_lmm_pd <- read.csv(file = path_or_buf)
transAcc_lmm_pd

    X   groupNo  subjNo reportType transDim transConds  transAcc
1    0  0younger  0     0marg      0Item    1PreCorrect 0.9798387
2    1  0younger  1     0marg      0Item    1PreCorrect 0.9960784
3    2  0younger  2     0marg      0Item    1PreCorrect 0.9841270
4    3  0younger  3     0marg      0Item    1PreCorrect 0.9838057
5    4  0younger  4     0marg      0Item    1PreCorrect 0.9840000
6    5  0younger  5     0marg      0Item    1PreCorrect 1.0000000
7    6  0younger  6     0marg      0Item    1PreCorrect 0.9750000
8    7  0younger  7     0marg      0Item    1PreCorrect 1.0000000
9    8  0younger  8     0marg      0Item    1PreCorrect 0.9751037
10   9  0younger  9     0marg      0Item    1PreCorrect 0.9880478
11  10  0younger 10     0marg      0Item    1PreCorrect 0.9330357
12  11  0younger 11     0marg      0Item    1PreCorrect 0.8435374
13  12  0younger 12     0marg      0Item    1PreCorrect 0.9298246
14  13  0younger 13     0marg      0Item    1PreCorrect 0.9839357
15  14  0younger 14     0marg      0Item    1PreCorrect 0.9586777
16  15  0younger 15     0marg      0Item    1PreCorrect 0.9791667
17  16  0younger 16     0marg      0Item    1PreCorrect 0.9656652
18  17  0younger 17     0marg      0Item    1PreCorrect 0.9708333
19  18  0younger 18     0marg      0Item    1PreCorrect 0.5737705
20  19  0younger 19     0marg      0Item    1PreCorrect 0.9493671
21  20  0younger 20     0marg      0Item    1PreCorrect 0.9535865
22  21  0younger 21     0marg      0Item    1PreCorrect 0.9960784
23  22  0younger 22     0marg      0Item    1PreCorrect 0.9539749
24  23  0younger 23     0marg      0Item    1PreCorrect 0.9666667
25  24  0younger 24     0marg      0Item    1PreCorrect 0.9960474
26  25  0younger 25     0marg      0Item    1PreCorrect 0.9920319
27  26  0younger 26     0marg      0Item    1PreCorrect 0.9839357
28  27  0younger 27     0marg      0Item    1PreCorrect 0.9960474
29  28  0younger 28     0marg      0Item    1PreCorrect 0.9613734
30  29  0younger 29     0marg      0Item    1PreCorrect 0.9300000
⋮   ⋮   ⋮        ⋮      ⋮          ⋮        ⋮           ⋮
875 874 1older   20     1recons    1Pos     0PreWrong   0.13679245
876 875 1older   21     1recons    1Pos     0PreWrong   0.14903846
877 876 1older   22     1recons    1Pos     0PreWrong   0.31764706
878 877 1older   23     1recons    1Pos     0PreWrong   0.25625000
879 878 1older   24     1recons    1Pos     0PreWrong   0.24698795
880 879 1older   25     1recons    1Pos     0PreWrong   0.23529412
881 880 1older   26     1recons    1Pos     0PreWrong   0.24647887
882 881 1older   27     1recons    1Pos     0PreWrong   0.01287554
883 882 1older   28     1recons    1Pos     0PreWrong   0.20430108
884 883 1older   29     1recons    1Pos     0PreWrong   0.38709677
885 884 1older   30     1recons    1Pos     0PreWrong   0.38709677
886 885 1older   31     1recons    1Pos     0PreWrong   0.31481481
887 886 1older   32     1recons    1Pos     0PreWrong   0.08292683
888 887 1older   33     1recons    1Pos     0PreWrong   0.43750000
889 888 1older   34     1recons    1Pos     0PreWrong   0.43511450
890 889 1older   35     1recons    1Pos     0PreWrong   0.25735294
891 890 1older   36     1recons    1Pos     0PreWrong   0.54761905
892 891 1older   37     1recons    1Pos     0PreWrong   0.34782609
893 892 1older   38     1recons    1Pos     0PreWrong   0.17391304
894 893 1older   39     1recons    1Pos     0PreWrong   0.21875000
895 894 1older   40     1recons    1Pos     0PreWrong   0.39285714
896 895 1older   41     1recons    1Pos     0PreWrong   0.25000000
897 896 1older   42     1recons    1Pos     0PreWrong   0.15346535
898 897 1older   43     1recons    1Pos     0PreWrong   0.40425532
899 898 1older   44     1recons    1Pos     0PreWrong   0.44210526
900 899 1older   45     1recons    1Pos     0PreWrong   0.38513514
901 900 1older   46     1recons    1Pos     0PreWrong   0.33526012
902 901 1older   47     1recons    1Pos     0PreWrong   0.42105263
903 902 1older   48     1recons    1Pos     0PreWrong   0.36477987
904 903 1older   49     1recons    1Pos     0PreWrong   0.24840764

In [11]:
trans_model <- lmer(transAcc ~ groupNo*transDim*transConds + (1 | subjNo), data = transAcc_lmm_pd)

In [12]:
summary(trans_model)

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: transAcc ~ groupNo * transDim * transConds + (1 | subjNo)
   Data: transAcc_lmm_pd

REML criterion at convergence: -600.6

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.5252 -0.5523  0.0341  0.5127  4.0236

Random effects:
 Groups   Name        Variance Std.Dev.
 subjNo   (Intercept) 0.004955 0.07039
 Residual             0.026144 0.16169
Number of obs: 899, groups:  subjNo, 63

Fixed effects:
                                                   Estimate Std. Error
(Intercept)                                        0.394391   0.017179
groupNo1older                                     -0.022987   0.022063
transDim1Pos                                       0.005087   0.020591
transConds1PreCorrect                              0.539410   0.020591
groupNo1older:transDim1Pos                        -0.057849   0.030771
groupNo1older:transConds1PreCorrect               -0.103864   0.030771
transDim1Pos:transConds1PreCorrect                -0.037943   0.028965
groupNo1older:transDim1Pos:transConds1PreCorrect  -0.078254   0.043414
                                                         df t value Pr(>|t|)
(Intercept)                                      361.930269  22.958  < 2e-16
groupNo1older                                    843.377085  -1.042 0.297752
transDim1Pos                                     827.129873   0.247 0.804910
transConds1PreCorrect                            827.129873  26.197  < 2e-16
groupNo1older:transDim1Pos                       826.791922  -1.880 0.060464
groupNo1older:transConds1PreCorrect              826.791922  -3.375 0.000772
transDim1Pos:transConds1PreCorrect               826.827195  -1.310 0.190569
groupNo1older:transDim1Pos:transConds1PreCorrect 826.655370  -1.803 0.071828

(Intercept)                                      ***
groupNo1older
transDim1Pos
transConds1PreCorrect                            ***
groupNo1older:transDim1Pos                       .
groupNo1older:transConds1PreCorrect              ***
transDim1Pos:transConds1PreCorrect
groupNo1older:transDim1Pos:transConds1PreCorrect .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) grpN1l trnD1P trC1PC grN1:D1P gN1:C1 tD1P:C
groupNo1ldr -0.572
transDim1Ps -0.612  0.477
trnsCnds1PC -0.612  0.477  0.511
grpN1ld:D1P  0.410 -0.704 -0.669 -0.342
grpN1l:C1PC  0.410 -0.704 -0.342 -0.669  0.505
trnD1P:C1PC  0.435 -0.339 -0.711 -0.711  0.476    0.476
gN1:D1P:C1P -0.290  0.499  0.474  0.474 -0.709   -0.709 -0.667

In [13]:
anova(trans_model, ddf='Satterthwaite')

                            Sum Sq      Mean Sq     NumDF DenDF    F value
groupNo                      3.15717591  3.15717591 1     875.6306  120.759253
transDim                     0.86342527  0.86342527 1     826.6554   33.025271
transConds                  44.73326234 44.73326234 1     826.6554 1711.008659
groupNo:transDim             0.52180834  0.52180834 1     826.6554   19.958718
groupNo:transConds           1.13449024  1.13449024 1     826.6554   43.393272
transDim:transConds          0.32957895  0.32957895 1     826.6554   12.606110
groupNo:transDim:transConds  0.08494507  0.08494507 1     826.6554    3.249075
                            Pr(>F)
groupNo                      2.090701e-26
transDim                     1.278904e-08
transConds                  1.558073e-203
groupNo:transDim             9.014335e-06
groupNo:transConds           7.961483e-11
transDim:transConds          4.062116e-04
groupNo:transDim:transConds  7.182789e-02

In [14]:
#emm_options(lmerTest.limit = 4000)
emm1 = emmeans(trans_model, specs = ~ transConds, lmer.df = "satterthwaite") # groupNo*reportType*bindConds
emm1

NOTE: Results may be misleading due to involvement in interactions

 transConds  emmean     SE   df lower.CL upper.CL
 0PreWrong    0.371 0.0118 95.3    0.348    0.394
 1PreCorrect  0.820 0.0118 94.6    0.796    0.843

Results are averaged over the levels of: groupNo, transDim
Degrees-of-freedom method: satterthwaite
Confidence level used: 0.95

In [15]:
emm_pairs <- pairs(emm1, simple = "transConds", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

 contrast                estimate     SE  df t.ratio p.value
 0PreWrong - 1PreCorrect   -0.449 0.0109 827 -41.364  <.0001

Results are averaged over the levels of: groupNo, transDim
Degrees-of-freedom method: satterthwaite

## Figure 2G & SFigure 4 (??): binding-related measures (conditional probability)

The binding score is calculated in the script: seqMemTask_v1_anal_summary.m

In [30]:
path_or_buf <- paste0(FBdata_folder, bindsOverall_name)
binds_lmm_pd <- read.csv(file = path_or_buf)
binds_lmm_pd

     X    groupNo  subjNo reportType bindDirec  bindConds bindScore   age
1     0   0younger  0     0marg      0ItemOnPos 1OtherR   0.9875000   22
2     1   0younger  1     0marg      0ItemOnPos 1OtherR   0.9960159   22
3     2   0younger  2     0marg      0ItemOnPos 1OtherR   0.9878049   22
4     3   0younger  3     0marg      0ItemOnPos 1OtherR   0.9811321   22
5     4   0younger  4     0marg      0ItemOnPos 1OtherR   0.9835391   21
6     5   0younger  5     0marg      0ItemOnPos 1OtherR   1.0000000   21
7     6   0younger  6     0marg      0ItemOnPos 1OtherR   0.9743590   21
8     7   0younger  7     0marg      0ItemOnPos 1OtherR   1.0000000   21
9     8   0younger  8     0marg      0ItemOnPos 1OtherR   0.9735683   25
10    9   0younger  9     0marg      0ItemOnPos 1OtherR   0.9879032   25
11   10   0younger 10     0marg      0ItemOnPos 1OtherR   0.9420290   25
12   11   0younger 11     0marg      0ItemOnPos 1OtherR   0.9357798   25
13   12   0younger 12     0marg      0ItemOnPos 1OtherR   0.9457014   21
14   13   0younger 13     0marg      0ItemOnPos 1OtherR   0.9838710   21
15   14   0younger 14     0marg      0ItemOnPos 1OtherR   0.9556962   21
16   15   0younger 15     0marg      0ItemOnPos 1OtherR   0.9770642   21
17   16   0younger 16     0marg      0ItemOnPos 1OtherR   0.9861111   23
18   17   0younger 17     0marg      0ItemOnPos 1OtherR   0.9777778   23
19   18   0younger 18     0marg      0ItemOnPos 1OtherR   0.5428571   23
20   19   0younger 19     0marg      0ItemOnPos 1OtherR   0.9525862   23
21   20   0younger 20     0marg      0ItemOnPos 1OtherR   0.9547511   20
22   21   0younger 21     0marg      0ItemOnPos 1OtherR   1.0000000   20
23   22   0younger 22     0marg      0ItemOnPos 1OtherR   0.9555556   20
24   23   0younger 23     0marg      0ItemOnPos 1OtherR   0.9809524   20
25   24   0younger 24     0marg      0ItemOnPos 1OtherR   0.9960159   23
26   25   0younger 25     0marg      0ItemOnPos 1OtherR   0.9917695   23
27   26   0younger 26     0marg      0ItemOnPos 1OtherR   0.9833333   23
28   27   0younger 27     0marg      0ItemOnPos 1OtherR   0.9959514   23
29   28   0younger 28     0marg      0ItemOnPos 1OtherR   0.9621622   23
30   29   0younger 29     0marg      0ItemOnPos 1OtherR   0.9580838   23
⋮    ⋮    ⋮        ⋮      ⋮          ⋮          ⋮         ⋮           ⋮
1779 1778 1older   20     1recons    1PosOnItem 0OtherW   0.114864865 67
1780 1779 1older   21     1recons    1PosOnItem 0OtherW   0.056179775 67
1781 1780 1older   22     1recons    1PosOnItem 0OtherW   0.125000000 65
1782 1781 1older   23     1recons    1PosOnItem 0OtherW   0.200000000 65
1783 1782 1older   24     1recons    1PosOnItem 0OtherW   0.144444444 65
1784 1783 1older   25     1recons    1PosOnItem 0OtherW   0.036036036 65
1785 1784 1older   26     1recons    1PosOnItem 0OtherW   0.170454545 68
1786 1785 1older   27     1recons    1PosOnItem 0OtherW   0.004405286 68
1787 1786 1older   28     1recons    1PosOnItem 0OtherW   0.066666667 68
1788 1787 1older   29     1recons    1PosOnItem 0OtherW   0.000000000 68
1789 1788 1older   30     1recons    1PosOnItem 0OtherW   0.266666667 70
1790 1789 1older   31     1recons    1PosOnItem 0OtherW   0.093750000 70
1791 1790 1older   32     1recons    1PosOnItem 0OtherW   0.068965517 70
1792 1791 1older   33     1recons    1PosOnItem 0OtherW   0.333333333 70
1793 1792 1older   34     1recons    1PosOnItem 0OtherW   0.250000000 72
1794 1793 1older   35     1recons    1PosOnItem 0OtherW   0.080459770 72
1795 1794 1older   36     1recons    1PosOnItem 0OtherW   0.066666667 72
1796 1795 1older   37     1recons    1PosOnItem 0OtherW   0.111111111 72
1797 1796 1older   38     1recons    1PosOnItem 0OtherW   0.094594595 65
1798 1797 1older   39     1recons    1PosOnItem 0OtherW   0.156250000 65
1799 1798 1older   40     1recons    1PosOnItem 0OtherW   0.000000000 65
1800 1799 1older   41     1recons    1PosOnItem 0OtherW   0.069767442 65
1801 1800 1older   42     1recons    1PosOnItem 0OtherW   0.049079755 67
1802 1801 1older   43     1recons    1PosOnItem 0OtherW   0.166666667 67
1803 1802 1older   44     1recons    1PosOnItem 0OtherW   0.086956522 67
1804 1803 1older   45     1recons    1PosOnItem 0OtherW   0.211267606 67
1805 1804 1older   46     1recons    1PosOnItem 0OtherW   0.227848101 67
1806 1805 1older   47     1recons    1PosOnItem 0OtherW   0.125000000 67
1807 1806 1older   48     1recons    1PosOnItem 0OtherW   0.157894737 67
1808 1807 1older   49     1recons    1PosOnItem 0OtherW   0.176470588 67

**Binary age group: YA vs. OA**

In [31]:
# binds_model <- lmer(bindScore ~ groupNo*bindConds*reportType + (1 | subjNo), data = binds_lmm_pd) 
binds_model <- lmer(bindScore ~ groupNo*bindConds + (1 | subjNo), data = binds_lmm_pd)

**Age as continuous variable**

In [9]:
# binds_model <- lmer(bindScore ~ age*bindConds + (1 | subjNo), data = binds_lmm_pd)

In [32]:
summary(binds_model)

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: bindScore ~ groupNo * bindConds + (1 | subjNo)
   Data: binds_lmm_pd

REML criterion at convergence: 747.5

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.61159 -0.86375  0.02746  0.81086  2.00721

Random effects:
 Groups   Name        Variance Std.Dev.
 subjNo   (Intercept) 0.001634 0.04042
 Residual             0.087343 0.29554
Number of obs: 1748, groups:  subjNo, 63

Fixed effects:
                                 Estimate Std. Error         df t value
(Intercept)                       0.48496    0.01481  420.94462  32.750
groupNo1older                    -0.06511    0.02049 1743.98656  -3.177
bindConds1OtherR                  0.26004    0.01919 1686.68727  13.551
groupNo1older:bindConds1OtherR   -0.04404    0.02841 1682.94934  -1.550
                               Pr(>|t|)
(Intercept)                     < 2e-16 ***
groupNo1older                   0.00151 **
bindConds1OtherR                < 2e-16 ***
groupNo1older:bindConds1OtherR  0.12128
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) grpN1l bnC1OR
groupNo1ldr -0.638
bndCnds1OtR -0.680  0.492
grpN1l:C1OR  0.459 -0.711 -0.675

In [33]:
anova(binds_model, ddf='Satterthwaite')

                  Sum Sq     Mean Sq    NumDF DenDF    F value    Pr(>F)
groupNo            3.1945096  3.1945096 1     1698.796  36.574400 1.803127e-09
bindConds         24.5184405 24.5184405 1     1683.102 280.715159 2.156194e-58
groupNo:bindConds  0.2098983  0.2098983 1     1682.949   2.403156 1.212787e-01

In [34]:
#emm_options(lmerTest.limit = 4000)
emm1 = emmeans(binds_model, specs = ~ groupNo*bindConds, lmer.df = "satterthwaite") # groupNo*reportType*bindConds
emm1

 groupNo  bindConds emmean     SE  df lower.CL upper.CL
 0younger 0OtherW    0.485 0.0148 421    0.456    0.514
 1older   0OtherW    0.420 0.0159 425    0.389    0.451
 0younger 1OtherR    0.745 0.0142 371    0.717    0.773
 1older   1OtherR    0.636 0.0158 419    0.605    0.667

Degrees-of-freedom method: satterthwaite
Confidence level used: 0.95

In [35]:
emm_pairs <- pairs(emm1, simple = "bindConds", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

groupNo = 0younger:
 contrast          estimate     SE   df t.ratio p.value
 0OtherW - 1OtherR   -0.260 0.0192 1687 -13.551  <.0001

groupNo = 1older:
 contrast          estimate     SE   df t.ratio p.value
 0OtherW - 1OtherR   -0.216 0.0210 1680 -10.309  <.0001

Degrees-of-freedom method: satterthwaite

## Figure 2H and 2I: overall binding score difference in Experiment 1

The binding score is calculated in the script: seqMemTask_v1_anal_summary.m

In [36]:
path_or_buf  <- paste0(FBdata_folder, bindsDiff_name)
binds_lmm_pd <- read.csv(file = path_or_buf)
binds_lmm_pd

    X   groupNo  subjNo reportType bindDirec  bindConds bindScore    age
1    0  0younger  0     0marg      0ItemOnPos 0cost      0.237500000 22
2    1  0younger  1     0marg      0ItemOnPos 0cost     -0.003984064 22
3    2  0younger  2     0marg      0ItemOnPos 0cost      0.154471545 21
4    3  0younger  3     0marg      0ItemOnPos 0cost     -0.018867925 21
5    4  0younger  4     0marg      0ItemOnPos 0cost     -0.016460905 25
6    5  0younger  5     0marg      0ItemOnPos 0cost      0.000000000 25
7    6  0younger  6     0marg      0ItemOnPos 0cost     -0.003418803 21
8    7  0younger  7     0marg      0ItemOnPos 0cost      0.000000000 21
9    8  0younger  8     0marg      0ItemOnPos 0cost     -0.026431718 23
10   9  0younger  9     0marg      0ItemOnPos 0cost     -0.012096774 23
11  10  0younger 10     0marg      0ItemOnPos 0cost      0.118499574 20
12  11  0younger 11     0marg      0ItemOnPos 0cost      0.356832448 20
13  12  0younger 12     0marg      0ItemOnPos 0cost      0.517129929 23
14  13  0younger 13     0marg      0ItemOnPos 0cost     -0.016129032 23
15  14  0younger 14     0marg      0ItemOnPos 0cost     -0.008589512 23
16  15  0younger 15     0marg      0ItemOnPos 0cost     -0.022935780 23
17  16  0younger 16     0marg      0ItemOnPos 0cost      0.280228758 21
18  17  0younger 17     0marg      0ItemOnPos 0cost      0.111111111 21
19  18  0younger 18     0marg      0ItemOnPos 0cost     -0.072527473 29
20  19  0younger 19     0marg      0ItemOnPos 0cost      0.152586207 29
21  20  0younger 20     0marg      0ItemOnPos 0cost      0.017251131 20
22  21  0younger 21     0marg      0ItemOnPos 0cost      0.055555556 20
23  22  0younger 22     0marg      0ItemOnPos 0cost      0.006403013 20
24  23  0younger 23     0marg      0ItemOnPos 0cost      0.114285714 20
25  24  0younger 24     0marg      0ItemOnPos 0cost     -0.003984064 29
26  25  0younger 25     0marg      0ItemOnPos 0cost     -0.008230453 29
27  26  0younger 26     0marg      0ItemOnPos 0cost     -0.016666667 23
28  27  0younger 27     0marg      0ItemOnPos 0cost     -0.004048583 23
29  28  0younger 28     0marg      0ItemOnPos 0cost      0.003828829 23
30  29  0younger 29     0marg      0ItemOnPos 0cost      0.170205044 23
⋮   ⋮   ⋮        ⋮      ⋮          ⋮          ⋮         ⋮            ⋮
875 874 1older   20     1recons    1PosOnItem 1benefit  0.07263514   70
876 875 1older   21     1recons    1PosOnItem 1benefit  0.64382022   70
877 876 1older   22     1recons    1PosOnItem 1benefit  0.26844262   65
878 877 1older   23     1recons    1PosOnItem 1benefit  0.08571429   65
879 878 1older   24     1recons    1PosOnItem 1benefit  0.22397661   72
880 879 1older   25     1recons    1PosOnItem 1benefit  0.72586873   72
881 880 1older   26     1recons    1PosOnItem 1benefit  0.19991582   72
882 881 1older   27     1recons    1PosOnItem 1benefit  0.32892805   72
883 882 1older   28     1recons    1PosOnItem 1benefit  0.38787879   65
884 883 1older   29     1recons    1PosOnItem 1benefit  0.50000000   65
885 884 1older   30     1recons    1PosOnItem 1benefit  0.23333333   69
886 885 1older   31     1recons    1PosOnItem 1benefit  0.31414474   69
887 886 1older   32     1recons    1PosOnItem 1benefit  0.09232481   67
888 887 1older   33     1recons    1PosOnItem 1benefit  0.10928962   67
889 888 1older   34     1recons    1PosOnItem 1benefit  0.24494949   67
890 889 1older   35     1recons    1PosOnItem 1benefit  0.49096880   67
891 890 1older   36     1recons    1PosOnItem 1benefit  0.74814815   65
892 891 1older   37     1recons    1PosOnItem 1benefit  0.38888889   65
893 892 1older   38     1recons    1PosOnItem 1benefit  0.17103041   68
894 893 1older   39     1recons    1PosOnItem 1benefit  0.12500000   68
895 894 1older   40     1recons    1PosOnItem 1benefit  0.57894737   70
896 895 1older   41     1recons    1PosOnItem 1benefit  0.63611491   70
897 896 1older   42     1recons    1PosOnItem 1benefit  0.54066384   72
898 897 1older   43     1recons    1PosOnItem 1benefit  0.27235772   72
899 898 1older   44     1recons    1PosOnItem 1benefit  0.46859903   65
900 899 1older   45     1recons    1PosOnItem 1benefit  0.33418694   65
901 900 1older   46     1recons    1PosOnItem 1benefit  0.19768381   67
902 901 1older   47     1recons    1PosOnItem 1benefit  0.51136364   67
903 902 1older   48     1recons    1PosOnItem 1benefit  0.32249742   67
904 903 1older   49     1recons    1PosOnItem 1benefit  0.08067227   67

In [37]:
binds_model <- lmer(bindScore ~ groupNo*reportType*bindConds + (1 | subjNo), data = binds_lmm_pd)

In [38]:
summary(binds_model)

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: bindScore ~ groupNo * reportType * bindConds + (1 | subjNo)
   Data: binds_lmm_pd

REML criterion at convergence: 7.1

Scaled residuals:
    Min      1Q  Median      3Q     Max
-4.2780 -0.6462 -0.1094  0.5493  3.5833

Random effects:
 Groups   Name        Variance Std.Dev.
 subjNo   (Intercept) 0.007806 0.08835
 Residual             0.052134 0.22833
Number of obs: 849, groups:  subjNo, 63

Fixed effects:
                                                   Estimate Std. Error
(Intercept)                                         0.09608    0.02357
groupNo1older                                       0.02676    0.03114
reportType1recons                                   0.25778    0.02908
bindConds1benefit                                   0.06219    0.03234
groupNo1older:reportType1recons                    -0.11447    0.04345
groupNo1older:bindConds1benefit                    -0.03891    0.04596
reportType1recons:bindConds1benefit                 0.04763    0.04353
groupNo1older:reportType1recons:bindConds1benefit  -0.01511    0.06328
                                                         df t value Pr(>|t|)
(Intercept)                                       408.99328   4.076  5.5e-05
groupNo1older                                     796.94188   0.859   0.3904
reportType1recons                                 778.89373   8.865  < 2e-16
bindConds1benefit                                 790.75519   1.923   0.0548
groupNo1older:reportType1recons                   778.40742  -2.634   0.0086
groupNo1older:bindConds1benefit                   785.30586  -0.847   0.3975
reportType1recons:bindConds1benefit               784.06366   1.094   0.2742
groupNo1older:reportType1recons:bindConds1benefit 781.29050  -0.239   0.8114

(Intercept)                                       ***
groupNo1older
reportType1recons                                 ***
bindConds1benefit                                 .
groupNo1older:reportType1recons                   **
groupNo1older:bindConds1benefit
reportType1recons:bindConds1benefit
groupNo1older:reportType1recons:bindConds1benefit
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) grpN1l rprtT1 bndCn1 grN1:T1 gN1:C1 rT1:C1
groupNo1ldr -0.589
rprtTyp1rcn -0.630  0.478
bndCnds1bnf -0.564  0.423  0.457
grpN1ldr:T1  0.421 -0.705 -0.669 -0.306
grpN1ldr:C1  0.397 -0.662 -0.322 -0.704  0.477
rprtTyp1:C1  0.419 -0.315 -0.667 -0.741  0.446   0.521
grpN1:T1:C1 -0.289  0.482  0.459  0.510 -0.686  -0.725 -0.688

In [39]:
anova(binds_model, ddf='Satterthwaite')

                             Sum Sq       Mean Sq      NumDF DenDF
groupNo                       0.557741837  0.557741837 1     835.8139
reportType                   10.116828073 10.116828073 1     782.9389
bindConds                     0.818864311  0.818864311 1     783.4465
groupNo:reportType            0.774654332  0.774654332 1     782.0560
groupNo:bindConds             0.112144399  0.112144399 1     783.5563
reportType:bindConds          0.083647117  0.083647117 1     781.4647
groupNo:reportType:bindConds  0.002970533  0.002970533 1     781.2905
                             F value      Pr(>F)
groupNo                       10.69828001 1.116269e-03
reportType                   194.05512070 1.440239e-39
bindConds                     15.70697965 8.070535e-05
groupNo:reportType            14.85896952 1.253676e-04
groupNo:bindConds              2.15108874 1.428700e-01
reportType:bindConds           1.60447043 2.056482e-01
groupNo:reportType:bindConds   0.05697903 8.113986e-01

In [40]:
#emm_options(lmerTest.limit = 4000)
emm1 = emmeans(binds_model, specs = ~ bindConds, lmer.df = "satterthwaite") # groupNo*reportType*bindConds
emm1

NOTE: Results may be misleading due to involvement in interactions

 bindConds emmean     SE  df lower.CL upper.CL
 0cost      0.210 0.0157 100    0.179    0.241
 1benefit   0.273 0.0161 111    0.241    0.304

Results are averaged over the levels of: groupNo, reportType
Degrees-of-freedom method: satterthwaite
Confidence level used: 0.95

In [41]:
emm_pairs <- pairs(emm1, simple = "bindConds", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

 contrast         estimate     SE  df t.ratio p.value
 0cost - 1benefit  -0.0628 0.0158 783  -3.963  0.0001

Results are averaged over the levels of: groupNo, reportType
Degrees-of-freedom method: satterthwaite