**seqMem_LMM**

In [1]:
library(lmerTest)
# install.packages("afex") 
library(afex)
# install.packages("emmeans")
library(emmeans) # used for post-hoc test
#install.packages("betareg")
# library(betareg) # used for beta-regression
#install.packages("TMB", type = "binary")
#install.packages("glmmTMB", type = "binary")
# library(glmmTMB)
# install.packages("brms"): running in the Rstudio
# library(brms)
library(dplyr)

Lade nötiges Paket: lme4

Lade nötiges Paket: Matrix


Attache Paket: ‘lmerTest’


Das folgende Objekt ist maskiert ‘package:lme4’:

    lmer


Das folgende Objekt ist maskiert ‘package:stats’:

    step


************
Welcome to afex. For support visit: http://afex.singmann.science/

- Functions for ANOVAs: aov_car(), aov_ez(), and aov_4()
- Methods for calculating p-values with mixed(): 'S', 'KR', 'LRT', and 'PB'
- 'afex_aov' and 'mixed' objects can be passed to emmeans() for follow-up tests
- Get and set global package options with: afex_options()
- Set sum-to-zero contrasts globally: set_sum_contrasts()
- For example analyses see: browseVignettes("afex")
************


Attache Paket: ‘afex’


Das folgende Objekt ist maskiert ‘package:lme4’:

    lmer


Welcome to emmeans.
Caution: You lose important information if you filter this package's results.
See '? untidy'


Attache Paket: ‘dplyr’


Die folgenden Objekte sind maskiert von ‘package:stats’:

    filter, lag


Die folgenden Objekte sind maskiert von ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
packageVersion("afex")

[1] ‘1.5.0’

In [3]:
packageVersion("lmerTest")

[1] ‘3.1.3’

In [4]:
packageVersion("emmeans")

[1] ‘1.11.2.8’

# Subjects' information

In [2]:
expDir         = '/Users/ren/Projects-NeuroCode/MyExperiment/Aging-SeqMemTask/AgingReplay-OnlineData/'
expDir_inHouse = '/Users/ren/Projects-NeuroCode/MyExperiment/Aging-SeqMemTask/AgingReplay-InHouseData/'
statSaveDir    = '/Users/ren/Projects-NeuroCode/MyExperiment/Aging-SeqMemTask/AgingReplay-StatAnal/' 
modelSaveDir   = '/Users/ren/Projects-NeuroCode/MyExperiment/Aging-SeqMemTask/ModelFitting_Results/'
FBdata_folder  = '/Users/ren/Projects-NeuroCode/MyExperiment/Aging-SeqMemTask/AgingReplay-OnlineData/FlexibleBindingPaper-Data/'

# Experiment 1: memory gradation across content, position and reconstruction report in both younger (18-30 ys) and older (>75 ys) adults

## Figure 2A and 2B-left panel: Within-age group comparison –– accuracy in content > position > reconstruction report

response (1/0) ~ measure * trialNo + (1 + measure * trialNo | subjNo)

In [ ]:
# path_or_buf <- paste0(expDir, 'acc_lmm_group_exp1.csv') #'acc_lmm_pd.csv'
# resp_glmm_pd <- read.csv(file = path_or_buf)
# resp_glmm_pd

In [3]:
path_or_buf <- paste0(expDir, 'resp_glmm_group_exp1.csv') #'resp_glmm_group.csv'
resp_glmm_pd <- read.csv(file = path_or_buf)
resp_glmm_pd

      X     groupNo  subjNo trialNo   transNo measNo   resp
1      0    0younger 0      0.0000000 1       0content 1
2      1    0younger 0      0.0000000 2       0content 1
3      2    0younger 0      0.0000000 3       0content 1
4      3    0younger 0      0.0000000 4       0content 1
5      4    0younger 0      0.0000000 5       0content 1
6      5    0younger 0      0.6931472 1       0content 1
7      6    0younger 0      0.6931472 2       0content 1
8      7    0younger 0      0.6931472 3       0content 1
9      8    0younger 0      0.6931472 4       0content 1
10     9    0younger 0      0.6931472 5       0content 1
11    10    0younger 0      1.0986123 1       0content 1
12    11    0younger 0      1.0986123 2       0content 1
13    12    0younger 0      1.0986123 3       0content 0
14    13    0younger 0      1.0986123 4       0content 1
15    14    0younger 0      1.0986123 5       0content 1
16    15    0younger 0      1.3862944 1       0content 1
17    16    0younger 0      1.3862944 2       0content 1
18    17    0younger 0      1.3862944 3       0content 1
19    18    0younger 0      1.3862944 4       0content 1
20    19    0younger 0      1.3862944 5       0content 1
21    20    0younger 0      1.6094379 1       0content 1
22    21    0younger 0      1.6094379 2       0content 1
23    22    0younger 0      1.6094379 3       0content 1
24    23    0younger 0      1.6094379 4       0content 1
25    24    0younger 0      1.6094379 5       0content 1
26    25    0younger 0      1.7917595 1       0content 1
27    26    0younger 0      1.7917595 2       0content 1
28    27    0younger 0      1.7917595 3       0content 1
29    28    0younger 0      1.7917595 4       0content 1
30    29    0younger 0      1.7917595 5       0content 1
⋮     ⋮     ⋮        ⋮      ⋮         ⋮       ⋮        ⋮
63331 63330 1older   26     4.077537  1       2both    1
63332 63331 1older   26     4.077537  2       2both    1
63333 63332 1older   26     4.077537  3       2both    1
63334 63333 1older   26     4.077537  4       2both    1
63335 63334 1older   26     4.077537  5       2both    1
63336 63335 1older   26     4.094345  1       2both    0
63337 63336 1older   26     4.094345  2       2both    0
63338 63337 1older   26     4.094345  3       2both    0
63339 63338 1older   26     4.094345  4       2both    0
63340 63339 1older   26     4.094345  5       2both    0
63341 63340 1older   26     4.110874  1       2both    1
63342 63341 1older   26     4.110874  2       2both    1
63343 63342 1older   26     4.110874  3       2both    1
63344 63343 1older   26     4.110874  4       2both    0
63345 63344 1older   26     4.110874  5       2both    0
63346 63345 1older   26     4.127134  1       2both    0
63347 63346 1older   26     4.127134  2       2both    0
63348 63347 1older   26     4.127134  3       2both    0
63349 63348 1older   26     4.127134  4       2both    1
63350 63349 1older   26     4.127134  5       2both    0
63351 63350 1older   26     4.143135  1       2both    0
63352 63351 1older   26     4.143135  2       2both    0
63353 63352 1older   26     4.143135  3       2both    0
63354 63353 1older   26     4.143135  4       2both    0
63355 63354 1older   26     4.143135  5       2both    1
63356 63355 1older   26     4.158883  1       2both    0
63357 63356 1older   26     4.158883  2       2both    0
63358 63357 1older   26     4.158883  3       2both    0
63359 63358 1older   26     4.158883  4       2both    0
63360 63359 1older   26     4.158883  5       2both    0

### Younger group

In [4]:
resp_glmm_pd_young = resp_glmm_pd[resp_glmm_pd$groupNo == '0younger', ]
resp_glmm_pd_young

     X    groupNo  subjNo trialNo measNo   accuracy fullyCor
1     0   0younger 0       1      0content 1.0      1
2     1   0younger 0       2      0content 1.0      1
3     2   0younger 0       3      0content 0.8      0
4     3   0younger 0       4      0content 1.0      1
5     4   0younger 0       5      0content 1.0      1
6     5   0younger 0       6      0content 1.0      1
7     6   0younger 0       7      0content 1.0      1
8     7   0younger 0       8      0content 0.6      0
9     8   0younger 0       9      0content 1.0      1
10    9   0younger 0      10      0content 1.0      1
11   10   0younger 0      11      0content 0.8      0
12   11   0younger 0      12      0content 0.8      0
13   12   0younger 0      13      0content 1.0      1
14   13   0younger 0      14      0content 1.0      1
15   14   0younger 0      15      0content 1.0      1
16   15   0younger 0      16      0content 1.0      1
17   16   0younger 0      17      0content 1.0      1
18   17   0younger 0      18      0content 1.0      1
19   18   0younger 0      19      0content 1.0      1
20   19   0younger 0      20      0content 1.0      1
21   20   0younger 0      21      0content 1.0      1
22   21   0younger 0      22      0content 1.0      1
23   22   0younger 0      23      0content 1.0      1
24   23   0younger 0      24      0content 1.0      1
25   24   0younger 0      25      0content 1.0      1
26   25   0younger 0      26      0content 1.0      1
27   26   0younger 0      27      0content 1.0      1
28   27   0younger 0      28      0content 1.0      1
29   28   0younger 0      29      0content 1.0      1
30   29   0younger 0      30      0content 1.0      1
⋮    ⋮    ⋮        ⋮      ⋮       ⋮        ⋮        ⋮
7459 7458 0younger 38     35      2both    1        1
7460 7459 0younger 38     36      2both    1        1
7461 7460 0younger 38     37      2both    1        1
7462 7461 0younger 38     38      2both    1        1
7463 7462 0younger 38     39      2both    1        1
7464 7463 0younger 38     40      2both    1        1
7465 7464 0younger 38     41      2both    1        1
7466 7465 0younger 38     42      2both    1        1
7467 7466 0younger 38     43      2both    1        1
7468 7467 0younger 38     44      2both    1        1
7469 7468 0younger 38     45      2both    1        1
7470 7469 0younger 38     46      2both    1        1
7471 7470 0younger 38     47      2both    1        1
7472 7471 0younger 38     48      2both    1        1
7473 7472 0younger 38     49      2both    1        1
7474 7473 0younger 38     50      2both    1        1
7475 7474 0younger 38     51      2both    1        1
7476 7475 0younger 38     52      2both    1        1
7477 7476 0younger 38     53      2both    1        1
7478 7477 0younger 38     54      2both    1        1
7479 7478 0younger 38     55      2both    1        1
7480 7479 0younger 38     56      2both    1        1
7481 7480 0younger 38     57      2both    1        1
7482 7481 0younger 38     58      2both    1        1
7483 7482 0younger 38     59      2both    1        1
7484 7483 0younger 38     60      2both    1        1
7485 7484 0younger 38     61      2both    1        1
7486 7485 0younger 38     62      2both    1        1
7487 7486 0younger 38     63      2both    1        1
7488 7487 0younger 38     64      2both    1        1

In [5]:
resp_glmm_pd_young$trialNo = scale(resp_glmm_pd_young$trialNo, center=TRUE, scale=FALSE) #scale=FALSE

In [6]:
choiceModel <- mixed(resp ~ trialNo*measNo + (1 | subjNo), data = resp_glmm_pd_young, family = binomial, method="LRT")
choiceModel

Contrasts set to contr.sum for the following variables: measNo

Mixed Model Anova Table (Type 3 tests, LRT-method)

Model: resp ~ trialNo * measNo + (1 | subjNo)
Data: resp_glmm_pd_young
Df full model: 7
          Effect df       Chisq p.value
1        trialNo  1  669.81 ***   <.001
2         measNo  2 1725.01 ***   <.001
3 trialNo:measNo  2   36.33 ***   <.001
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1

In [7]:
emm1 = emmeans(choiceModel, specs = ~ trialNo*measNo) # same as: emmeans(choiceModel, ~ networkName) & emmeans(choiceModel, c("networkName"))
emm1

  trialNo measNo    emmean    SE  df asymp.LCL asymp.UCL
 2.88e-13 0content    3.12 0.191 Inf      2.74      3.49
 2.88e-13 1position   2.70 0.190 Inf      2.32      3.07
 2.88e-13 2both       1.49 0.189 Inf      1.12      1.86

Results are given on the logit (not the response) scale.
Confidence level used: 0.95

In [8]:
emm_pairs <- pairs(emm1, simple = "measNo", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

trialNo = 2.88e-13:
 contrast             estimate     SE  df z.ratio p.value
 0content - 1position    0.421 0.0496 Inf   8.484  <.0001
 0content - 2both        1.628 0.0452 Inf  35.995  <.0001
 1position - 2both       1.207 0.0411 Inf  29.360  <.0001

Results are given on the log odds ratio (not the response) scale.
P value adjustment: bonferroni method for 3 tests

### Older group

In [5]:
resp_glmm_pd_old = resp_glmm_pd[resp_glmm_pd$groupNo == '1older', ]
resp_glmm_pd_old

      X     groupNo subjNo trialNo measNo   accuracy fullyCor
7489  7488  1older  0       1      0content 1.0      1
7490  7489  1older  0       2      0content 0.6      0
7491  7490  1older  0       3      0content 0.2      0
7492  7491  1older  0       4      0content 1.0      1
7493  7492  1older  0       5      0content 0.8      0
7494  7493  1older  0       6      0content 0.6      0
7495  7494  1older  0       7      0content 1.0      1
7496  7495  1older  0       8      0content 0.6      0
7497  7496  1older  0       9      0content 0.6      0
7498  7497  1older  0      10      0content 0.6      0
7499  7498  1older  0      11      0content 1.0      1
7500  7499  1older  0      12      0content 0.6      0
7501  7500  1older  0      13      0content 0.6      0
7502  7501  1older  0      14      0content 0.6      0
7503  7502  1older  0      15      0content 0.6      0
7504  7503  1older  0      16      0content 0.8      0
7505  7504  1older  0      17      0content 1.0      1
7506  7505  1older  0      18      0content 1.0      1
7507  7506  1older  0      19      0content 0.8      0
7508  7507  1older  0      20      0content 0.8      0
7509  7508  1older  0      21      0content 0.6      0
7510  7509  1older  0      22      0content 1.0      1
7511  7510  1older  0      23      0content 0.4      0
7512  7511  1older  0      24      0content 0.8      0
7513  7512  1older  0      25      0content 1.0      1
7514  7513  1older  0      26      0content 0.4      0
7515  7514  1older  0      27      0content 0.2      0
7516  7515  1older  0      28      0content 1.0      1
7517  7516  1older  0      29      0content 0.2      0
7518  7517  1older  0      30      0content 0.4      0
⋮     ⋮     ⋮       ⋮      ⋮       ⋮        ⋮        ⋮
12643 12642 1older  26     35      2both    0.4      0
12644 12643 1older  26     36      2both    0.2      0
12645 12644 1older  26     37      2both    1.0      1
12646 12645 1older  26     38      2both    0.0      0
12647 12646 1older  26     39      2both    0.8      0
12648 12647 1older  26     40      2both    0.0      0
12649 12648 1older  26     41      2both    0.8      0
12650 12649 1older  26     42      2both    0.8      0
12651 12650 1older  26     43      2both    0.2      0
12652 12651 1older  26     44      2both    0.4      0
12653 12652 1older  26     45      2both    1.0      1
12654 12653 1older  26     46      2both    0.0      0
12655 12654 1older  26     47      2both    0.6      0
12656 12655 1older  26     48      2both    0.4      0
12657 12656 1older  26     49      2both    0.4      0
12658 12657 1older  26     50      2both    1.0      1
12659 12658 1older  26     51      2both    0.4      0
12660 12659 1older  26     52      2both    0.0      0
12661 12660 1older  26     53      2both    0.2      0
12662 12661 1older  26     54      2both    0.4      0
12663 12662 1older  26     55      2both    0.6      0
12664 12663 1older  26     56      2both    0.2      0
12665 12664 1older  26     57      2both    1.0      1
12666 12665 1older  26     58      2both    0.2      0
12667 12666 1older  26     59      2both    1.0      1
12668 12667 1older  26     60      2both    0.0      0
12669 12668 1older  26     61      2both    0.6      0
12670 12669 1older  26     62      2both    0.2      0
12671 12670 1older  26     63      2both    0.2      0
12672 12671 1older  26     64      2both    0.0      0

In [10]:
resp_glmm_pd_old$trialNo = scale(resp_glmm_pd_old$trialNo, center=TRUE, scale=FALSE) #scale=FALSE

In [11]:
choiceModel <- mixed(resp ~ trialNo*measNo + (1 | subjNo), data = resp_glmm_pd_old, family = binomial, method="LRT")
choiceModel

Contrasts set to contr.sum for the following variables: measNo

Mixed Model Anova Table (Type 3 tests, LRT-method)

Model: resp ~ trialNo * measNo + (1 | subjNo)
Data: resp_glmm_pd_old
Df full model: 7
          Effect df       Chisq p.value
1        trialNo  1  480.89 ***   <.001
2         measNo  2 3758.27 ***   <.001
3 trialNo:measNo  2      6.28 *    .043
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1

In [12]:
emm1 = emmeans(choiceModel, specs = ~ trialNo*measNo) # same as: emmeans(choiceModel, ~ networkName) & emmeans(choiceModel, c("networkName"))
emm1

  trialNo measNo    emmean    SE  df asymp.LCL asymp.UCL
 1.77e-13 0content   1.563 0.201 Inf     1.169     1.956
 1.77e-13 1position  0.284 0.200 Inf    -0.109     0.676
 1.77e-13 2both     -0.657 0.200 Inf    -1.050    -0.264

Results are given on the logit (not the response) scale.
Confidence level used: 0.95

In [13]:
emm_pairs <- pairs(emm1, simple = "measNo", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

trialNo = 1.77e-13:
 contrast             estimate     SE  df z.ratio p.value
 0content - 1position    1.279 0.0380 Inf  33.643  <.0001
 0content - 2both        2.219 0.0395 Inf  56.221  <.0001
 1position - 2both       0.941 0.0347 Inf  27.075  <.0001

Results are given on the log odds ratio (not the response) scale.
P value adjustment: bonferroni method for 3 tests

## Between-group comparison: accuracy difference between groups in content < position < reconstruction

### Method 1: importing all data from younger and older adults

In [6]:
# Concatenate (stack) the two data frames
resp_glmm_pd_center <- rbind(resp_glmm_pd_young, resp_glmm_pd_old)
resp_glmm_pd_center

      X     groupNo  subjNo trialNo measNo   accuracy fullyCor
1      0    0younger 0       1      0content 1.0      1
2      1    0younger 0       2      0content 1.0      1
3      2    0younger 0       3      0content 0.8      0
4      3    0younger 0       4      0content 1.0      1
5      4    0younger 0       5      0content 1.0      1
6      5    0younger 0       6      0content 1.0      1
7      6    0younger 0       7      0content 1.0      1
8      7    0younger 0       8      0content 0.6      0
9      8    0younger 0       9      0content 1.0      1
10     9    0younger 0      10      0content 1.0      1
11    10    0younger 0      11      0content 0.8      0
12    11    0younger 0      12      0content 0.8      0
13    12    0younger 0      13      0content 1.0      1
14    13    0younger 0      14      0content 1.0      1
15    14    0younger 0      15      0content 1.0      1
16    15    0younger 0      16      0content 1.0      1
17    16    0younger 0      17      0content 1.0      1
18    17    0younger 0      18      0content 1.0      1
19    18    0younger 0      19      0content 1.0      1
20    19    0younger 0      20      0content 1.0      1
21    20    0younger 0      21      0content 1.0      1
22    21    0younger 0      22      0content 1.0      1
23    22    0younger 0      23      0content 1.0      1
24    23    0younger 0      24      0content 1.0      1
25    24    0younger 0      25      0content 1.0      1
26    25    0younger 0      26      0content 1.0      1
27    26    0younger 0      27      0content 1.0      1
28    27    0younger 0      28      0content 1.0      1
29    28    0younger 0      29      0content 1.0      1
30    29    0younger 0      30      0content 1.0      1
⋮     ⋮     ⋮        ⋮      ⋮       ⋮        ⋮        ⋮
12643 12642 1older   26     35      2both    0.4      0
12644 12643 1older   26     36      2both    0.2      0
12645 12644 1older   26     37      2both    1.0      1
12646 12645 1older   26     38      2both    0.0      0
12647 12646 1older   26     39      2both    0.8      0
12648 12647 1older   26     40      2both    0.0      0
12649 12648 1older   26     41      2both    0.8      0
12650 12649 1older   26     42      2both    0.8      0
12651 12650 1older   26     43      2both    0.2      0
12652 12651 1older   26     44      2both    0.4      0
12653 12652 1older   26     45      2both    1.0      1
12654 12653 1older   26     46      2both    0.0      0
12655 12654 1older   26     47      2both    0.6      0
12656 12655 1older   26     48      2both    0.4      0
12657 12656 1older   26     49      2both    0.4      0
12658 12657 1older   26     50      2both    1.0      1
12659 12658 1older   26     51      2both    0.4      0
12660 12659 1older   26     52      2both    0.0      0
12661 12660 1older   26     53      2both    0.2      0
12662 12661 1older   26     54      2both    0.4      0
12663 12662 1older   26     55      2both    0.6      0
12664 12663 1older   26     56      2both    0.2      0
12665 12664 1older   26     57      2both    1.0      1
12666 12665 1older   26     58      2both    0.2      0
12667 12666 1older   26     59      2both    1.0      1
12668 12667 1older   26     60      2both    0.0      0
12669 12668 1older   26     61      2both    0.6      0
12670 12669 1older   26     62      2both    0.2      0
12671 12670 1older   26     63      2both    0.2      0
12672 12671 1older   26     64      2both    0.0      0

In [7]:
choiceModel <- mixed(fullyCor ~ measNo*groupNo + (1 | subjNo), data = resp_glmm_pd_center, family = binomial, method="LRT")
choiceModel

Contrasts set to contr.sum for the following variables: measNo, groupNo

Mixed Model Anova Table (Type 3 tests, LRT-method)

Model: fullyCor ~ measNo * groupNo + (1 | subjNo)
Data: resp_glmm_pd_center
Df full model: 7
          Effect df       Chisq p.value
1         measNo  2 1418.75 ***   <.001
2        groupNo  1 2132.69 ***   <.001
3 measNo:groupNo  2  106.00 ***   <.001
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1

In [10]:
emm1 = emmeans(choiceModel, specs = ~ measNo*groupNo) # same as: emmeans(choiceModel, ~ networkName) & emmeans(choiceModel, c("networkName"))
emm1

 measNo    groupNo  emmean    SE  df asymp.LCL asymp.UCL
 0content  0younger  2.075 0.166 Inf     1.749     2.401
 1position 0younger  1.555 0.163 Inf     1.235     1.875
 2both     0younger  0.516 0.161 Inf     0.202     0.831
 0content  1older    0.566 0.164 Inf     0.244     0.888
 1position 1older   -0.999 0.166 Inf    -1.325    -0.674
 2both     1older   -2.003 0.173 Inf    -2.343    -1.664

Results are given on the logit (not the response) scale.
Confidence level used: 0.95

In [11]:
emm_pairs <- pairs(emm1, simple = "groupNo", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

measNo = 0content:
 contrast          estimate     SE  df z.ratio p.value
 0younger - 1older     1.51 0.0826 Inf  18.266  <.0001

measNo = 1position:
 contrast          estimate     SE  df z.ratio p.value
 0younger - 1older     2.55 0.0810 Inf  31.526  <.0001

measNo = 2both:
 contrast          estimate     SE  df z.ratio p.value
 0younger - 1older     2.52 0.0903 Inf  27.900  <.0001

Results are given on the log odds ratio (not the response) scale.

### Method 2: importing the accuracy change percentage ((old-young)/young)

In [3]:
path_or_buf <- paste0(expDir, 'acc_change_lmm_subj_exp1.csv') 
acc_lmm_pd <- read.csv(file = path_or_buf)
acc_lmm_pd

     X    groupNo subjNo trialNo measNo   acc_change  fullyCor
1     0   1       0       1      0content  0.07977159 0
2     1   1       0       2      0content -0.35213705 0
3     2   1       0       3      0content -0.78404568 0
4     3   1       0       4      0content  0.07977159 0
5     4   1       0       5      0content -0.13618273 0
6     5   1       0       6      0content -0.35213705 0
7     6   1       0       7      0content  0.07977159 0
8     7   1       0       8      0content -0.35213705 0
9     8   1       0       9      0content -0.35213705 0
10    9   1       0      10      0content -0.35213705 0
11   10   1       0      11      0content  0.07977159 0
12   11   1       0      12      0content -0.35213705 0
13   12   1       0      13      0content -0.35213705 0
14   13   1       0      14      0content -0.35213705 0
15   14   1       0      15      0content -0.35213705 0
16   15   1       0      16      0content -0.13618273 0
17   16   1       0      17      0content  0.07977159 0
18   17   1       0      18      0content  0.07977159 0
19   18   1       0      19      0content -0.13618273 0
20   19   1       0      20      0content -0.13618273 0
21   20   1       0      21      0content -0.35213705 0
22   21   1       0      22      0content  0.07977159 0
23   22   1       0      23      0content -0.56809137 0
24   23   1       0      24      0content -0.13618273 0
25   24   1       0      25      0content  0.07977159 0
26   25   1       0      26      0content -0.56809137 0
27   26   1       0      27      0content -0.78404568 0
28   27   1       0      28      0content  0.07977159 0
29   28   1       0      29      0content -0.78404568 0
30   29   1       0      30      0content -0.56809137 0
⋮    ⋮    ⋮       ⋮      ⋮       ⋮        ⋮           ⋮
5155 5154 1       26     35      2both    -0.47297297 0
5156 5155 1       26     36      2both    -0.73648649 0
5157 5156 1       26     37      2both     0.31756757 0
5158 5157 1       26     38      2both    -1.00000000 0
5159 5158 1       26     39      2both     0.05405405 0
5160 5159 1       26     40      2both    -1.00000000 0
5161 5160 1       26     41      2both     0.05405405 0
5162 5161 1       26     42      2both     0.05405405 0
5163 5162 1       26     43      2both    -0.73648649 0
5164 5163 1       26     44      2both    -0.47297297 0
5165 5164 1       26     45      2both     0.31756757 0
5166 5165 1       26     46      2both    -1.00000000 0
5167 5166 1       26     47      2both    -0.20945946 0
5168 5167 1       26     48      2both    -0.47297297 0
5169 5168 1       26     49      2both    -0.47297297 0
5170 5169 1       26     50      2both     0.31756757 0
5171 5170 1       26     51      2both    -0.47297297 0
5172 5171 1       26     52      2both    -1.00000000 0
5173 5172 1       26     53      2both    -0.73648649 0
5174 5173 1       26     54      2both    -0.47297297 0
5175 5174 1       26     55      2both    -0.20945946 0
5176 5175 1       26     56      2both    -0.73648649 0
5177 5176 1       26     57      2both     0.31756757 0
5178 5177 1       26     58      2both    -0.73648649 0
5179 5178 1       26     59      2both     0.31756757 0
5180 5179 1       26     60      2both    -1.00000000 0
5181 5180 1       26     61      2both    -0.20945946 0
5182 5181 1       26     62      2both    -0.73648649 0
5183 5182 1       26     63      2both    -0.73648649 0
5184 5183 1       26     64      2both    -1.00000000 0

In [4]:
accModel_group <- lmer(acc_change ~ measNo + (1 + measNo | subjNo), data = acc_lmm_pd)

In [5]:
summary(accModel_group)

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: acc_change ~ measNo + (1 + measNo | subjNo)
   Data: acc_lmm_pd

REML criterion at convergence: 2901.5

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.4990 -0.6657  0.1269  0.6799  3.2687

Random effects:
 Groups   Name            Variance Std.Dev. Corr
 subjNo   (Intercept)     0.03615  0.1901
          measNo1position 0.04287  0.2071   -0.22
          measNo2both     0.04197  0.2049   -0.02  0.77
 Residual                 0.09752  0.3123
Number of obs: 5184, groups:  subjNo, 27

Fixed effects:
                Estimate Std. Error       df t value Pr(>|t|)
(Intercept)     -0.15405    0.03736 26.00001  -4.124 0.000338 ***
measNo1position -0.22235    0.04124 26.00099  -5.392 1.20e-05 ***
measNo2both     -0.35933    0.04083 26.00047  -8.800 2.83e-09 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) msN1ps
measNo1pstn -0.242
measNo2both -0.054  0.750

In [6]:
anova(accModel_group, ddf='Satterthwaite')

       Sum Sq   Mean Sq  NumDF DenDF    F value  Pr(>F)
measNo 7.874142 3.937071 2     26.00024 40.37192 1.062093e-08

In [8]:
emm_options(lmerTest.limit = 5184)
emm_comp = emmeans(accModel_group, specs = ~ measNo, lmer.df = "satterthwaite") # specs = ~ groupNo*measNo

In [9]:
test(emm_comp)

  measNo    emmean     SE         df       t.ratio   p.value
1 0content  -0.1540540 0.03735619 26.00001 -4.123920 3.381827e-04
2 1position -0.3764067 0.04848981 26.00034 -7.762594 3.096942e-08
3 2both     -0.5133845 0.05384543 26.00005 -9.534411 5.667354e-10

In [10]:
emm_pairs_comp <- pairs(emm_comp, simple = "measNo", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs_comp

 contrast             estimate     SE df t.ratio p.value
 0content - 1position    0.222 0.0412 26   5.392  <.0001
 0content - 2both        0.359 0.0408 26   8.800  <.0001
 1position - 2both       0.137 0.0290 26   4.715  0.0002

Degrees-of-freedom method: satterthwaite
P value adjustment: bonferroni method for 3 tests

# Experiment 2: only Interleaved curriculum –– three trial organization conditions (interleaved, contentBlocked, positionBlocked)

## Method 2: choice in each slot as dependent variables (GLMM)

### Choice (correct-1, incorrect-0) in each slot

In [3]:
groupId <- 1
if (groupId == 1) {
    groupName <- 'younger'
} else if (groupId == 2) {
    groupName <- 'older'
}

In [4]:
groupName

[1] "younger"

In [5]:
path_or_buf   <- paste0(expDir, 'choice_lmm_group_conds_', groupName, '_exp2.csv') #'acc_lmm_pd.csv'
choice_lmm_pd <- read.csv(file = path_or_buf)
choice_lmm_pd

      X     groupNo          subjNo trialNo measNo   slotNo  choice
1      0    0interleaved     0      1       0content 0first  1
2      1    0interleaved     0      1       0content 1second 1
3      2    0interleaved     0      1       0content 2third  1
4      3    0interleaved     0      1       0content 3fourth 1
5      4    0interleaved     0      1       0content 4fifth  1
6      5    0interleaved     0      3       0content 0first  1
7      6    0interleaved     0      3       0content 1second 1
8      7    0interleaved     0      3       0content 2third  1
9      8    0interleaved     0      3       0content 3fourth 1
10     9    0interleaved     0      3       0content 4fifth  1
11    10    0interleaved     0      4       0content 0first  1
12    11    0interleaved     0      4       0content 1second 1
13    12    0interleaved     0      4       0content 2third  1
14    13    0interleaved     0      4       0content 3fourth 0
15    14    0interleaved     0      4       0content 4fifth  0
16    15    0interleaved     0      5       0content 0first  1
17    16    0interleaved     0      5       0content 1second 1
18    17    0interleaved     0      5       0content 2third  1
19    18    0interleaved     0      5       0content 3fourth 1
20    19    0interleaved     0      5       0content 4fifth  1
21    20    0interleaved     0      7       0content 0first  1
22    21    0interleaved     0      7       0content 1second 1
23    22    0interleaved     0      7       0content 2third  1
24    23    0interleaved     0      7       0content 3fourth 1
25    24    0interleaved     0      7       0content 4fifth  1
26    25    0interleaved     0      8       0content 0first  1
27    26    0interleaved     0      8       0content 1second 1
28    27    0interleaved     0      8       0content 2third  1
29    28    0interleaved     0      8       0content 3fourth 1
30    29    0interleaved     0      8       0content 4fifth  0
⋮     ⋮     ⋮                ⋮      ⋮       ⋮        ⋮       ⋮
55171 55170 2positionBlocked 20     59      2both    0first  1
55172 55171 2positionBlocked 20     59      2both    1second 1
55173 55172 2positionBlocked 20     59      2both    2third  1
55174 55173 2positionBlocked 20     59      2both    3fourth 1
55175 55174 2positionBlocked 20     59      2both    4fifth  1
55176 55175 2positionBlocked 20     60      2both    0first  1
55177 55176 2positionBlocked 20     60      2both    1second 1
55178 55177 2positionBlocked 20     60      2both    2third  1
55179 55178 2positionBlocked 20     60      2both    3fourth 1
55180 55179 2positionBlocked 20     60      2both    4fifth  1
55181 55180 2positionBlocked 20     61      2both    0first  1
55182 55181 2positionBlocked 20     61      2both    1second 1
55183 55182 2positionBlocked 20     61      2both    2third  1
55184 55183 2positionBlocked 20     61      2both    3fourth 1
55185 55184 2positionBlocked 20     61      2both    4fifth  1
55186 55185 2positionBlocked 20     62      2both    0first  1
55187 55186 2positionBlocked 20     62      2both    1second 1
55188 55187 2positionBlocked 20     62      2both    2third  1
55189 55188 2positionBlocked 20     62      2both    3fourth 1
55190 55189 2positionBlocked 20     62      2both    4fifth  1
55191 55190 2positionBlocked 20     63      2both    0first  1
55192 55191 2positionBlocked 20     63      2both    1second 1
55193 55192 2positionBlocked 20     63      2both    2third  1
55194 55193 2positionBlocked 20     63      2both    3fourth 1
55195 55194 2positionBlocked 20     63      2both    4fifth  1
55196 55195 2positionBlocked 20     64      2both    0first  1
55197 55196 2positionBlocked 20     64      2both    1second 1
55198 55197 2positionBlocked 20     64      2both    2third  1
55199 55198 2positionBlocked 20     64      2both    3fourth 1
55200 55199 2positionBlocked 20     64      2both    4fifth  1

In [9]:
choiceModel <- glmer(choice ~ groupNo*measNo*slotNo + (1 + measNo*slotNo | subjNo), data = choice_lmm_pd, family = binomial)

Warning message in commonArgs(par, fn, control, environment()):
“maxfun < 10 * length(par)^2 is not recommended.”
Warning message in optwrap(optimizer, devfun, start, rho$lower, control = control, :
“convergence code 1 from bobyqa: bobyqa -- maximum number of function evaluations exceeded”

In [ ]:
summary(choiceModel)

In [ ]:
emm_choice = emmeans(choiceModel, specs = ~ groupNo*measNo*slotNo) # same as: emmeans(choiceModel, ~ networkName) & emmeans(choiceModel, c("networkName"))
emm_choice

In [ ]:
emm_pairs_choice <- pairs(emm_choice, simple = "each", adjust = "tukey") # adjust = "bonferroni", "tukey"
emm_pairs_choice

## Decline change percentage (older minus younger) across three learning curriculums

In [3]:
groupName <- 'older'
path_or_buf <- paste0(expDir, 'acc_change_conds_group_', groupName, '_exp2.csv') #'acc_lmm_pd.csv'
acc_lmm_pd <- read.csv(file = path_or_buf)
acc_lmm_pd

      X     groupNo          subjNo trialNo measNo   accuracy_change fullyCor
1      0    0interleaved     0       1      0content  0.1225882      0
2      1    0interleaved     0       2      0content  0.1225882      0
3      2    0interleaved     0       3      0content  0.1225882      0
4      3    0interleaved     0       4      0content  0.1225882      0
5      4    0interleaved     0       6      0content  0.1225882      0
6      5    0interleaved     0       8      0content  0.1225882      0
7      6    0interleaved     0       9      0content  0.1225882      0
8      7    0interleaved     0      10      0content  0.1225882      0
9      8    0interleaved     0      12      0content  0.1225882      0
10     9    0interleaved     0      13      0content  0.1225882      0
11    10    0interleaved     0      14      0content  0.1225882      0
12    11    0interleaved     0      15      0content  0.1225882      0
13    12    0interleaved     0      17      0content  0.1225882      0
14    13    0interleaved     0      18      0content  0.1225882      0
15    14    0interleaved     0      20      0content  0.1225882      0
16    15    0interleaved     0      21      0content  0.1225882      0
17    16    0interleaved     0      22      0content  0.1225882      0
18    17    0interleaved     0      23      0content  0.1225882      0
19    18    0interleaved     0      25      0content  0.1225882      0
20    19    0interleaved     0      26      0content -0.1019294      0
21    20    0interleaved     0      27      0content  0.1225882      0
22    21    0interleaved     0      28      0content -0.1019294      0
23    22    0interleaved     0      31      0content  0.1225882      0
24    23    0interleaved     0      32      0content  0.1225882      0
25    24    0interleaved     0      33      0content  0.1225882      0
26    25    0interleaved     0      34      0content  0.1225882      0
27    26    0interleaved     0      35      0content  0.1225882      0
28    27    0interleaved     0      36      0content  0.1225882      0
29    28    0interleaved     0      37      0content  0.1225882      0
30    29    0interleaved     0      38      0content  0.1225882      0
⋮     ⋮     ⋮                ⋮      ⋮       ⋮        ⋮               ⋮
11651 11650 2positionBlocked 24     35      2both     0.260551491    0
11652 11651 2positionBlocked 24     36      2both     0.008441193    0
11653 11652 2positionBlocked 24     37      2both    -0.747889702    0
11654 11653 2positionBlocked 24     38      2both     0.260551491    0
11655 11654 2positionBlocked 24     39      2both     0.260551491    0
11656 11655 2positionBlocked 24     40      2both    -0.495779403    0
11657 11656 2positionBlocked 24     41      2both     0.260551491    0
11658 11657 2positionBlocked 24     42      2both     0.260551491    0
11659 11658 2positionBlocked 24     43      2both     0.008441193    0
11660 11659 2positionBlocked 24     44      2both     0.260551491    0
11661 11660 2positionBlocked 24     45      2both     0.260551491    0
11662 11661 2positionBlocked 24     46      2both     0.260551491    0
11663 11662 2positionBlocked 24     47      2both     0.260551491    0
11664 11663 2positionBlocked 24     48      2both     0.260551491    0
11665 11664 2positionBlocked 24     49      2both     0.260551491    0
11666 11665 2positionBlocked 24     50      2both     0.260551491    0
11667 11666 2positionBlocked 24     51      2both     0.260551491    0
11668 11667 2positionBlocked 24     52      2both     0.260551491    0
11669 11668 2positionBlocked 24     53      2both     0.260551491    0
11670 11669 2positionBlocked 24     54      2both     0.260551491    0
11671 11670 2positionBlocked 24     55      2both     0.260551491    0
11672 11671 2positionBlocked 24     56      2both     0.008441193    0
11673 11672 2positionBlocked 24     57      2both     0.260551491    0
11674 11673 2positionBlocked 24     58      2both     0.260551491    0
11675 11674 2positionBlocked 24     59      2both     0.260551491    0
11676 11675 2positionBlocked 24     60      2both     0.260551491    0
11677 11676 2positionBlocked 24     61      2both     0.260551491    0
11678 11677 2positionBlocked 24     62      2both     0.260551491    0
11679 11678 2positionBlocked 24     63      2both     0.260551491    0
11680 11679 2positionBlocked 24     64      2both     0.260551491    0
      order
1     1second
2     0first
3     1second
4     0first
5     0first
6     1second
7     1second
8     1second
9     0first
10    0first
11    1second
12    1second
13    0first
14    1second
15    0first
16    1second
17    0first
18    1second
19    1second
20    1second
21    0first
22    0first
23    1second
24    0first
25    1second
26    0first
27    1second
28    0first
29    0first
30    0first
⋮     ⋮
11651 2third
11652 2third
11653 0first
11654 2third
11655 2third
11656 0first
11657 0first
11658 2third
11659 2third
11660 2third
11661 2third
11662 0first
11663 2third
11664 2third
11665 2third
11666 2third
11667 2third
11668 2third
11669 2third
11670 0first
11671 2third
11672 0first
11673 0first
11674 2third
11675 2third
11676 2third
11677 0first
11678 2third
11679 2third
11680 2third

In [4]:
# --------only the itemBlocked condition--------
acc_lmm_pd_cond = acc_lmm_pd[acc_lmm_pd$groupNo == '0interleaved', ]
acc_lmm_pd_cond

     X    groupNo         subjNo trialNo measNo   accuracy_change fullyCor
3681 3680 1contentBlocked 0       1      0content -0.35037594     0
3682 3681 1contentBlocked 0       3      0content -0.35037594     0
3683 3682 1contentBlocked 0       4      0content  0.08270677     0
3684 3683 1contentBlocked 0       5      0content  0.08270677     0
3685 3684 1contentBlocked 0       6      0content -0.35037594     0
3686 3685 1contentBlocked 0       8      0content  0.08270677     0
3687 3686 1contentBlocked 0       9      0content -0.13383459     0
3688 3687 1contentBlocked 0      10      0content -0.13383459     0
3689 3688 1contentBlocked 0      11      0content -0.35037594     0
3690 3689 1contentBlocked 0      14      0content  0.08270677     0
3691 3690 1contentBlocked 0      15      0content  0.08270677     0
3692 3691 1contentBlocked 0      16      0content  0.08270677     0
3693 3692 1contentBlocked 0      18      0content -0.56691729     0
3694 3693 1contentBlocked 0      19      0content  0.08270677     0
3695 3694 1contentBlocked 0      20      0content -0.56691729     0
3696 3695 1contentBlocked 0      22      0content  0.08270677     0
3697 3696 1contentBlocked 0      23      0content  0.08270677     0
3698 3697 1contentBlocked 0      24      0content  0.08270677     0
3699 3698 1contentBlocked 0      25      0content -0.56691729     0
3700 3699 1contentBlocked 0      26      0content  0.08270677     0
3701 3700 1contentBlocked 0      28      0content  0.08270677     0
3702 3701 1contentBlocked 0      30      0content -0.35037594     0
3703 3702 1contentBlocked 0      31      0content -0.35037594     0
3704 3703 1contentBlocked 0      32      0content  0.08270677     0
3705 3704 1contentBlocked 0      33      0content  0.08270677     0
3706 3705 1contentBlocked 0      34      0content -0.35037594     0
3707 3706 1contentBlocked 0      36      0content  0.08270677     0
3708 3707 1contentBlocked 0      38      0content -0.78345865     0
3709 3708 1contentBlocked 0      39      0content -0.13383459     0
3710 3709 1contentBlocked 0      40      0content  0.08270677     0
⋮    ⋮    ⋮               ⋮      ⋮       ⋮        ⋮               ⋮
7651 7650 1contentBlocked 24     35      2both     0.07281299     0
7652 7651 1contentBlocked 24     36      2both     0.34101624     0
7653 7652 1contentBlocked 24     37      2both     0.34101624     0
7654 7653 1contentBlocked 24     38      2both     0.34101624     0
7655 7654 1contentBlocked 24     39      2both     0.07281299     0
7656 7655 1contentBlocked 24     40      2both    -0.19539026     0
7657 7656 1contentBlocked 24     41      2both     0.34101624     0
7658 7657 1contentBlocked 24     42      2both     0.07281299     0
7659 7658 1contentBlocked 24     43      2both    -0.73179675     0
7660 7659 1contentBlocked 24     44      2both     0.07281299     0
7661 7660 1contentBlocked 24     45      2both     0.34101624     0
7662 7661 1contentBlocked 24     46      2both     0.34101624     0
7663 7662 1contentBlocked 24     47      2both     0.07281299     0
7664 7663 1contentBlocked 24     48      2both     0.34101624     0
7665 7664 1contentBlocked 24     49      2both    -0.46359350     0
7666 7665 1contentBlocked 24     50      2both     0.34101624     0
7667 7666 1contentBlocked 24     51      2both     0.34101624     0
7668 7667 1contentBlocked 24     52      2both     0.34101624     0
7669 7668 1contentBlocked 24     53      2both     0.34101624     0
7670 7669 1contentBlocked 24     54      2both     0.07281299     0
7671 7670 1contentBlocked 24     55      2both     0.34101624     0
7672 7671 1contentBlocked 24     56      2both    -0.19539026     0
7673 7672 1contentBlocked 24     57      2both    -0.46359350     0
7674 7673 1contentBlocked 24     58      2both     0.34101624     0
7675 7674 1contentBlocked 24     59      2both    -0.73179675     0
7676 7675 1contentBlocked 24     60      2both     0.34101624     0
7677 7676 1contentBlocked 24     61      2both    -0.19539026     0
7678 7677 1contentBlocked 24     62      2both     0.34101624     0
7679 7678 1contentBlocked 24     63      2both     0.07281299     0
7680 7679 1contentBlocked 24     64      2both     0.34101624     0
     order
3681 0first
3682 0first
3683 1second
3684 0first
3685 1second
3686 0first
3687 1second
3688 0first
3689 1second
3690 0first
3691 1second
3692 0first
3693 1second
3694 0first
3695 1second
3696 1second
3697 1second
3698 0first
3699 1second
3700 0first
3701 1second
3702 1second
3703 1second
3704 0first
3705 0first
3706 1second
3707 0first
3708 0first
3709 0first
3710 1second
⋮    ⋮
7651 2third
7652 2third
7653 2third
7654 2third
7655 2third
7656 2third
7657 2third
7658 2third
7659 2third
7660 0first
7661 2third
7662 2third
7663 2third
7664 0first
7665 2third
7666 2third
7667 2third
7668 0first
7669 2third
7670 0first
7671 2third
7672 2third
7673 2third
7674 2third
7675 2third
7676 0first
7677 2third
7678 0first
7679 2third
7680 2third

In [ ]:
# accModel_comp <- lmer(accuracy_change ~ groupNo + (1 | subjNo), data = acc_lmm_pd) # *measNo

In [5]:
accModel_comp <- lmer(accuracy_change ~ measNo + (1 | subjNo), data = acc_lmm_pd_cond) # *measNo

In [6]:
summary(accModel_comp)

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: accuracy_change ~ measNo + (1 | subjNo)
   Data: acc_lmm_pd_cond

REML criterion at convergence: 2898.4

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.5998 -0.5024  0.1569  0.6612  2.5689

Random effects:
 Groups   Name        Variance Std.Dev.
 subjNo   (Intercept) 0.06341  0.2518
 Residual             0.11707  0.3422
Number of obs: 4000, groups:  subjNo, 25

Fixed effects:
                  Estimate Std. Error         df t value Pr(>|t|)
(Intercept)       -0.04758    0.05132   25.29445  -0.927    0.363
measNo1position   -0.12733    0.01397 3973.00000  -9.116  < 2e-16 ***
measNo2both       -0.08931    0.01307 3973.00000  -6.835 9.44e-12 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) msN1ps
measNo1pstn -0.136
measNo2both -0.145  0.535

In [7]:
anova(accModel_comp, ddf='Satterthwaite')

       Sum Sq   Mean Sq  NumDF DenDF F value  Pr(>F)
measNo 10.35917 5.179583 2     3973  44.24361 9.910541e-20

In [9]:
emm_options(lmerTest.limit = 4000)
emm1 = emmeans(accModel_comp, specs = ~ measNo, lmer.df = "satterthwaite") # specs = ~ groupNo*measNo; same as: emmeans(choiceModel, ~ networkName) & emmeans(choiceModel, c("networkName"))
emm1

 measNo     emmean     SE   df lower.CL upper.CL
 0content  -0.0476 0.0513 25.3   -0.153   0.0581
 1position -0.1749 0.0513 25.3   -0.281  -0.0693
 2both     -0.1369 0.0511 24.8   -0.242  -0.0316

Degrees-of-freedom method: satterthwaite
Confidence level used: 0.95

In [10]:
emm_pairs <- pairs(emm1, simple = "measNo", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

 contrast             estimate     SE   df t.ratio p.value
 0content - 1position   0.1273 0.0140 3973   9.116  <.0001
 0content - 2both       0.0893 0.0131 3973   6.835  <.0001
 1position - 2both     -0.0380 0.0131 3973  -2.910  0.0109

Degrees-of-freedom method: satterthwaite
P value adjustment: bonferroni method for 3 tests

## Figure 2C: accuracy comparison across 3 measures (itemReport, posReport, reconsReport) between across-window and within-window analysis in Experiment 2

In [ ]:
path_or_buf  <- paste0(statSaveDir, 'acc_fullyCor_within_between_trials_YA_OA_group_exp2.csv' )
acc_glmm_pd <- read.csv(file = path_or_buf)
acc_glmm_pd

In [ ]:
# ------ Three reports within a trial ------
acc_glmm_pd_threeReports = acc_glmm_pd[acc_glmm_pd$groupNo == '0interleaved' & acc_glmm_pd$dataType == '0withinTrl', ]
acc_glmm_pd_threeReports

In [ ]:
# ------ Three reports: item and location within trials, reconstruction from the 1st report window (between trials) ------
# Subset for partial reports
acc_glmm_pd_partialReports <- acc_glmm_pd[
  acc_glmm_pd$groupNo == "0interleaved" &
  acc_glmm_pd$dataType == "0withinTrl" &
  (acc_glmm_pd$reportType == "0content" | acc_glmm_pd$reportType == "1position"),
]

# Subset for full reports (between trials)
acc_glmm_pd_fullReportsBetween <- acc_glmm_pd[
  acc_glmm_pd$groupNo == "0interleaved" &
  acc_glmm_pd$dataType == "1betweenTrl" &
  acc_glmm_pd$reportType == "2both",
]

# Combine them
acc_glmm_pd_threeReports <- rbind(
  acc_glmm_pd_partialReports,
  acc_glmm_pd_fullReportsBetween
)

In [ ]:
acc_glmm_pd_threeReports

In [ ]:
choiceModel <- mixed(fullyCor ~ ageNo*reportType + (1 | subjNo), data = acc_glmm_pd_threeReports, family = binomial, method="LRT")
choiceModel

In [ ]:
emm1 = emmeans(choiceModel, specs = ~ ageNo*reportType)
emm1

In [ ]:
emm_pairs <- pairs(emm1, simple = "reportType", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

# Exp1 and Exp2:  False alarm (FA), Transition accuracy and Binding related statistical tests

Extract the data based on experiments (Exp1 or Exp2) or data collapse (Exp1 + Exp2)

In [4]:
dataFlg <- 3

if (dataFlg == 1) {        # Experiment 1
  # ------ Figure 2D: FA of lure items ------
  FA_lure_name      <- 'Fig2D_FA_lure_overall_YAOA_stats_Exp1.csv'

  # ------ Figure 2E: Transition accuracy ------
  transAcc_name     <- 'Fig2E_transAcc_overall_group_stats_Exp1.csv'

  # ------ Figure 2G: Binding measures (conditional probability) ------
  bindsOverall_name <- 'Fig2G_binds_overall_group_stats_Exp1.csv'

  # ------ Figure 2HI: Binding-related measures ------
  bindsDiff_name    <- 'Fig2HI_binds_overall_diff_group_stats_Exp1.csv'

} else if (dataFlg == 2) { # Experiment 2
  FA_lure_name      <- 'Fig2D_FA_lure_overall_YAOA_stats_Exp2.csv'
  transAcc_name     <- 'Fig2E_transAcc_overall_group_stats_Exp2.csv'
  bindsOverall_name <- 'Fig2G_binds_overall_group_stats_Exp2.csv'
  bindsDiff_name    <- 'Fig2HI_binds_overall_diff_group_stats_Exp2.csv'

} else if (dataFlg == 3) { # Exp1 + Exp2
  FA_lure_name      <- 'Fig2D_FA_lure_overall_YAOA_stats_Exp12.csv'
  transAcc_name     <- 'Fig2E_transAcc_overall_group_stats_Exp12.csv'
  bindsOverall_name <- 'Fig2G_binds_overall_group_stats_Exp12.csv'
  bindsDiff_name    <- 'Fig2HI_binds_overall_diff_group_stats_Exp12.csv'
}

## Figure 2D: false alarm rate

In [7]:
path_or_buf  <- paste0(FBdata_folder, FA_lure_name)
FA_lmm_pd <- read.csv(file = path_or_buf)
FA_lmm_pd

    X   groupNo  subjNo reportType reportDim FArates
1    0  0younger  0     0marg      0Item     0.078125
2    1  0younger  1     0marg      0Item     0.015625
3    2  0younger  2     0marg      0Item     0.015625
4    3  0younger  3     0marg      0Item     0.000000
5    4  0younger  4     0marg      0Item     0.015625
6    5  0younger  5     0marg      0Item     0.000000
7    6  0younger  6     0marg      0Item     0.078125
8    7  0younger  7     0marg      0Item     0.015625
9    8  0younger  8     0marg      0Item     0.046875
10   9  0younger  9     0marg      0Item     0.015625
11  10  0younger 10     0marg      0Item     0.046875
12  11  0younger 11     0marg      0Item     0.375000
13  12  0younger 12     0marg      0Item     0.109375
14  13  0younger 13     0marg      0Item     0.031250
15  14  0younger 14     0marg      0Item     0.078125
16  15  0younger 15     0marg      0Item     0.078125
17  16  0younger 16     0marg      0Item     0.015625
18  17  0younger 17     0marg      0Item     0.031250
19  18  0younger 18     0marg      0Item     0.562500
20  19  0younger 19     0marg      0Item     0.125000
21  20  0younger 20     0marg      0Item     0.031250
22  21  0younger 21     0marg      0Item     0.015625
23  22  0younger 22     0marg      0Item     0.109375
24  23  0younger 23     0marg      0Item     0.031250
25  24  0younger 24     0marg      0Item     0.000000
26  25  0younger 25     0marg      0Item     0.015625
27  26  0younger 26     0marg      0Item     0.000000
28  27  0younger 27     0marg      0Item     0.000000
29  28  0younger 28     0marg      0Item     0.031250
30  29  0younger 29     0marg      0Item     0.171875
⋮   ⋮   ⋮        ⋮      ⋮          ⋮         ⋮
423 422 1older   20     1recons    1Pos      0.640625
424 423 1older   21     1recons    1Pos      0.531250
425 424 1older   22     1recons    1Pos      0.312500
426 425 1older   23     1recons    1Pos      0.546875
427 426 1older   24     1recons    1Pos      0.796875
428 427 1older   25     1recons    1Pos      0.484375
429 428 1older   26     1recons    1Pos      0.531250
430 429 1older   27     1recons    1Pos      0.187500
431 430 1older   28     1recons    1Pos      0.218750
432 431 1older   29     1recons    1Pos      0.156250
433 432 1older   30     1recons    1Pos      0.234375
434 433 1older   31     1recons    1Pos      0.453125
435 434 1older   32     1recons    1Pos      0.500000
436 435 1older   33     1recons    1Pos      0.250000
437 436 1older   34     1recons    1Pos      0.781250
438 437 1older   35     1recons    1Pos      0.500000
439 438 1older   36     1recons    1Pos      0.171875
440 439 1older   37     1recons    1Pos      0.093750
441 440 1older   38     1recons    1Pos      0.656250
442 441 1older   39     1recons    1Pos      0.656250
443 442 1older   40     1recons    1Pos      0.015625
444 443 1older   41     1recons    1Pos      0.156250
445 444 1older   42     1recons    1Pos      0.437500
446 445 1older   43     1recons    1Pos      0.406250
447 446 1older   44     1recons    1Pos      0.453125
448 447 1older   45     1recons    1Pos      0.781250
449 448 1older   46     1recons    1Pos      0.609375
450 449 1older   47     1recons    1Pos      0.031250
451 450 1older   48     1recons    1Pos      0.656250
452 451 1older   49     1recons    1Pos      0.578125

In [8]:
# column_name = {0: 'groupNo', 1: 'subjNo', 2: 'reportType', 3: 'reportDim', 4: 'FArates'} 
FA_model <- lmer(FArates ~ groupNo*reportType*reportDim + (1 | subjNo), data = FA_lmm_pd)

In [9]:
summary(FA_model)

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: FArates ~ groupNo * reportType * reportDim + (1 | subjNo)
   Data: FA_lmm_pd

REML criterion at convergence: -272.3

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.56518 -0.60411 -0.07041  0.46994  3.14113

Random effects:
 Groups   Name        Variance Std.Dev.
 subjNo   (Intercept) 0.01228  0.1108
 Residual             0.02383  0.1544
Number of obs: 452, groups:  subjNo, 63

Fixed effects:
                                                Estimate Std. Error         df
(Intercept)                                    7.961e-02  2.394e-02  2.452e+02
groupNo1older                                  1.254e-01  2.952e-02  3.833e+02
reportType1recons                              3.497e-02  2.750e-02  3.769e+02
reportDim1Pos                                  8.854e-02  2.750e-02  3.769e+02
groupNo1older:reportType1recons                7.589e-04  4.135e-02  3.769e+02
groupNo1older:reportDim1Pos                    1.927e-01  4.135e-02  3.769e+02
reportType1recons:reportDim1Pos               -2.480e-02  3.890e-02  3.769e+02
groupNo1older:reportType1recons:reportDim1Pos -1.832e-02  5.847e-02  3.769e+02
                                              t value Pr(>|t|)
(Intercept)                                     3.325  0.00102 **
groupNo1older                                   4.247 2.72e-05 ***
reportType1recons                               1.271  0.20435
reportDim1Pos                                   3.219  0.00140 **
groupNo1older:reportType1recons                 0.018  0.98537
groupNo1older:reportDim1Pos                     4.661 4.38e-06 ***
reportType1recons:reportDim1Pos                -0.638  0.52411
groupNo1older:reportType1recons:reportDim1Pos  -0.313  0.75418
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) grpN1l rprtT1 rprD1P grN1:T1 gN1:D1 rT1:D1
groupNo1ldr -0.535
rprtTyp1rcn -0.574  0.466
reportDm1Ps -0.574  0.466  0.500
grpN1ldr:T1  0.382 -0.700 -0.665 -0.333
grpN1ld:D1P  0.382 -0.700 -0.333 -0.665  0.500
rprtTy1:D1P  0.406 -0.329 -0.707 -0.707  0.470   0.470
grN1:T1:D1P -0.270  0.495  0.470  0.470 -0.707  -0.707 -0.665

In [10]:
anova(FA_model, ddf='Satterthwaite')

                             Sum Sq      Mean Sq     NumDF DenDF
groupNo                      4.896271050 4.896271050 1     400.2370
reportType                   0.037619972 0.037619972 1     376.8911
reportDim                    3.143886662 3.143886662 1     376.8911
groupNo:reportType           0.001968239 0.001968239 1     376.8911
groupNo:reportDim            0.939128296 0.939128296 1     376.8911
reportType:reportDim         0.032155237 0.032155237 1     376.8911
groupNo:reportType:reportDim 0.002339833 0.002339833 1     376.8911
                             F value      Pr(>F)
groupNo                      205.47331437 6.642251e-38
reportType                     1.57873212 2.097216e-01
reportDim                    131.93403834 2.182993e-26
groupNo:reportType             0.08259768 7.739655e-01
groupNo:reportDim             39.41076825 9.455053e-10
reportType:reportDim           1.34940304 2.461176e-01
groupNo:reportType:reportDim   0.09819171 7.541839e-01

In [11]:
#emm_options(lmerTest.limit = 4000)
emm1 = emmeans(FA_model, specs = ~ reportDim, lmer.df = "satterthwaite") # groupNo*reportType*bindConds
emm1

NOTE: Results may be misleading due to involvement in interactions

 reportDim emmean     SE   df lower.CL upper.CL
 0Item      0.160 0.0175 83.8    0.125    0.195
 1Pos       0.328 0.0175 83.8    0.293    0.363

Results are averaged over the levels of: groupNo, reportType
Degrees-of-freedom method: satterthwaite
Confidence level used: 0.95

In [12]:
emm_pairs <- pairs(emm1, simple = "reportDim", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

 contrast     estimate     SE  df t.ratio p.value
 0Item - 1Pos   -0.168 0.0146 377 -11.486  <.0001

Results are averaged over the levels of: groupNo, reportType
Degrees-of-freedom method: satterthwaite

## Figure 2E: transition accuracy

In [13]:
path_or_buf  <- paste0(FBdata_folder, transAcc_name)
transAcc_lmm_pd <- read.csv(file = path_or_buf)
transAcc_lmm_pd

    X   groupNo  subjNo reportType transDim transConds  transAcc
1    0  0younger  0     0marg      0Item    1PreCorrect 0.9798387
2    1  0younger  1     0marg      0Item    1PreCorrect 0.9960784
3    2  0younger  2     0marg      0Item    1PreCorrect 0.9841270
4    3  0younger  3     0marg      0Item    1PreCorrect 0.9838057
5    4  0younger  4     0marg      0Item    1PreCorrect 0.9840000
6    5  0younger  5     0marg      0Item    1PreCorrect 1.0000000
7    6  0younger  6     0marg      0Item    1PreCorrect 0.9750000
8    7  0younger  7     0marg      0Item    1PreCorrect 1.0000000
9    8  0younger  8     0marg      0Item    1PreCorrect 0.9751037
10   9  0younger  9     0marg      0Item    1PreCorrect 0.9880478
11  10  0younger 10     0marg      0Item    1PreCorrect 0.9330357
12  11  0younger 11     0marg      0Item    1PreCorrect 0.8435374
13  12  0younger 12     0marg      0Item    1PreCorrect 0.9298246
14  13  0younger 13     0marg      0Item    1PreCorrect 0.9839357
15  14  0younger 14     0marg      0Item    1PreCorrect 0.9586777
16  15  0younger 15     0marg      0Item    1PreCorrect 0.9791667
17  16  0younger 16     0marg      0Item    1PreCorrect 0.9656652
18  17  0younger 17     0marg      0Item    1PreCorrect 0.9708333
19  18  0younger 18     0marg      0Item    1PreCorrect 0.5737705
20  19  0younger 19     0marg      0Item    1PreCorrect 0.9493671
21  20  0younger 20     0marg      0Item    1PreCorrect 0.9535865
22  21  0younger 21     0marg      0Item    1PreCorrect 0.9960784
23  22  0younger 22     0marg      0Item    1PreCorrect 0.9539749
24  23  0younger 23     0marg      0Item    1PreCorrect 0.9666667
25  24  0younger 24     0marg      0Item    1PreCorrect 0.9960474
26  25  0younger 25     0marg      0Item    1PreCorrect 0.9920319
27  26  0younger 26     0marg      0Item    1PreCorrect 0.9839357
28  27  0younger 27     0marg      0Item    1PreCorrect 0.9960474
29  28  0younger 28     0marg      0Item    1PreCorrect 0.9613734
30  29  0younger 29     0marg      0Item    1PreCorrect 0.9300000
⋮   ⋮   ⋮        ⋮      ⋮          ⋮        ⋮           ⋮
875 874 1older   20     1recons    1Pos     0PreWrong   0.13679245
876 875 1older   21     1recons    1Pos     0PreWrong   0.14903846
877 876 1older   22     1recons    1Pos     0PreWrong   0.31764706
878 877 1older   23     1recons    1Pos     0PreWrong   0.25625000
879 878 1older   24     1recons    1Pos     0PreWrong   0.24698795
880 879 1older   25     1recons    1Pos     0PreWrong   0.23529412
881 880 1older   26     1recons    1Pos     0PreWrong   0.24647887
882 881 1older   27     1recons    1Pos     0PreWrong   0.01287554
883 882 1older   28     1recons    1Pos     0PreWrong   0.20430108
884 883 1older   29     1recons    1Pos     0PreWrong   0.38709677
885 884 1older   30     1recons    1Pos     0PreWrong   0.38709677
886 885 1older   31     1recons    1Pos     0PreWrong   0.31481481
887 886 1older   32     1recons    1Pos     0PreWrong   0.08292683
888 887 1older   33     1recons    1Pos     0PreWrong   0.43750000
889 888 1older   34     1recons    1Pos     0PreWrong   0.43511450
890 889 1older   35     1recons    1Pos     0PreWrong   0.25735294
891 890 1older   36     1recons    1Pos     0PreWrong   0.54761905
892 891 1older   37     1recons    1Pos     0PreWrong   0.34782609
893 892 1older   38     1recons    1Pos     0PreWrong   0.17391304
894 893 1older   39     1recons    1Pos     0PreWrong   0.21875000
895 894 1older   40     1recons    1Pos     0PreWrong   0.39285714
896 895 1older   41     1recons    1Pos     0PreWrong   0.25000000
897 896 1older   42     1recons    1Pos     0PreWrong   0.15346535
898 897 1older   43     1recons    1Pos     0PreWrong   0.40425532
899 898 1older   44     1recons    1Pos     0PreWrong   0.44210526
900 899 1older   45     1recons    1Pos     0PreWrong   0.38513514
901 900 1older   46     1recons    1Pos     0PreWrong   0.33526012
902 901 1older   47     1recons    1Pos     0PreWrong   0.42105263
903 902 1older   48     1recons    1Pos     0PreWrong   0.36477987
904 903 1older   49     1recons    1Pos     0PreWrong   0.24840764

In [14]:
trans_model <- lmer(transAcc ~ groupNo*transDim*transConds + (1 | subjNo), data = transAcc_lmm_pd)

In [15]:
summary(trans_model)

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: transAcc ~ groupNo * transDim * transConds + (1 | subjNo)
   Data: transAcc_lmm_pd

REML criterion at convergence: -600.6

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.5252 -0.5523  0.0341  0.5127  4.0236

Random effects:
 Groups   Name        Variance Std.Dev.
 subjNo   (Intercept) 0.004955 0.07039
 Residual             0.026144 0.16169
Number of obs: 899, groups:  subjNo, 63

Fixed effects:
                                                   Estimate Std. Error
(Intercept)                                        0.394391   0.017179
groupNo1older                                     -0.022987   0.022063
transDim1Pos                                       0.005087   0.020591
transConds1PreCorrect                              0.539410   0.020591
groupNo1older:transDim1Pos                        -0.057849   0.030771
groupNo1older:transConds1PreCorrect               -0.103864   0.030771
transDim1Pos:transConds1PreCorrect                -0.037943   0.028965
groupNo1older:transDim1Pos:transConds1PreCorrect  -0.078254   0.043414
                                                         df t value Pr(>|t|)
(Intercept)                                      361.930269  22.958  < 2e-16
groupNo1older                                    843.377085  -1.042 0.297752
transDim1Pos                                     827.129873   0.247 0.804910
transConds1PreCorrect                            827.129873  26.197  < 2e-16
groupNo1older:transDim1Pos                       826.791922  -1.880 0.060464
groupNo1older:transConds1PreCorrect              826.791922  -3.375 0.000772
transDim1Pos:transConds1PreCorrect               826.827195  -1.310 0.190569
groupNo1older:transDim1Pos:transConds1PreCorrect 826.655370  -1.803 0.071828

(Intercept)                                      ***
groupNo1older
transDim1Pos
transConds1PreCorrect                            ***
groupNo1older:transDim1Pos                       .
groupNo1older:transConds1PreCorrect              ***
transDim1Pos:transConds1PreCorrect
groupNo1older:transDim1Pos:transConds1PreCorrect .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) grpN1l trnD1P trC1PC grN1:D1P gN1:C1 tD1P:C
groupNo1ldr -0.572
transDim1Ps -0.612  0.477
trnsCnds1PC -0.612  0.477  0.511
grpN1ld:D1P  0.410 -0.704 -0.669 -0.342
grpN1l:C1PC  0.410 -0.704 -0.342 -0.669  0.505
trnD1P:C1PC  0.435 -0.339 -0.711 -0.711  0.476    0.476
gN1:D1P:C1P -0.290  0.499  0.474  0.474 -0.709   -0.709 -0.667

In [16]:
anova(trans_model, ddf='Satterthwaite')

                            Sum Sq      Mean Sq     NumDF DenDF    F value
groupNo                      3.15717591  3.15717591 1     875.6306  120.759253
transDim                     0.86342527  0.86342527 1     826.6554   33.025271
transConds                  44.73326234 44.73326234 1     826.6554 1711.008659
groupNo:transDim             0.52180834  0.52180834 1     826.6554   19.958718
groupNo:transConds           1.13449024  1.13449024 1     826.6554   43.393272
transDim:transConds          0.32957895  0.32957895 1     826.6554   12.606110
groupNo:transDim:transConds  0.08494507  0.08494507 1     826.6554    3.249075
                            Pr(>F)
groupNo                      2.090701e-26
transDim                     1.278904e-08
transConds                  1.558073e-203
groupNo:transDim             9.014335e-06
groupNo:transConds           7.961483e-11
transDim:transConds          4.062116e-04
groupNo:transDim:transConds  7.182789e-02

In [17]:
#emm_options(lmerTest.limit = 4000)
emm1 = emmeans(trans_model, specs = ~ transConds, lmer.df = "satterthwaite") # groupNo*reportType*bindConds
emm1

NOTE: Results may be misleading due to involvement in interactions

 transConds  emmean     SE   df lower.CL upper.CL
 0PreWrong    0.371 0.0118 95.3    0.348    0.394
 1PreCorrect  0.820 0.0118 94.6    0.796    0.843

Results are averaged over the levels of: groupNo, transDim
Degrees-of-freedom method: satterthwaite
Confidence level used: 0.95

In [18]:
emm_pairs <- pairs(emm1, simple = "transConds", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

 contrast                estimate     SE  df t.ratio p.value
 0PreWrong - 1PreCorrect   -0.449 0.0109 827 -41.364  <.0001

Results are averaged over the levels of: groupNo, transDim
Degrees-of-freedom method: satterthwaite

## Figure 2G & SFigure 4 (??): binding-related measures (conditional probability)

The binding score is calculated in the script: seqMemTask_v1_anal_summary.m

In [5]:
path_or_buf <- paste0(FBdata_folder, bindsOverall_name)
binds_lmm_pd <- read.csv(file = path_or_buf)
binds_lmm_pd

     X    groupNo  subjNo reportType bindDirec  bindConds bindScore   age
1     0   0younger  0     0marg      0ItemOnPos 1OtherR   0.9875000   22
2     1   0younger  1     0marg      0ItemOnPos 1OtherR   0.9960159   22
3     2   0younger  2     0marg      0ItemOnPos 1OtherR   0.9878049   22
4     3   0younger  3     0marg      0ItemOnPos 1OtherR   0.9811321   22
5     4   0younger  4     0marg      0ItemOnPos 1OtherR   0.9835391   21
6     5   0younger  5     0marg      0ItemOnPos 1OtherR   1.0000000   21
7     6   0younger  6     0marg      0ItemOnPos 1OtherR   0.9743590   21
8     7   0younger  7     0marg      0ItemOnPos 1OtherR   1.0000000   21
9     8   0younger  8     0marg      0ItemOnPos 1OtherR   0.9735683   25
10    9   0younger  9     0marg      0ItemOnPos 1OtherR   0.9879032   25
11   10   0younger 10     0marg      0ItemOnPos 1OtherR   0.9420290   25
12   11   0younger 11     0marg      0ItemOnPos 1OtherR   0.9357798   25
13   12   0younger 12     0marg      0ItemOnPos 1OtherR   0.9457014   21
14   13   0younger 13     0marg      0ItemOnPos 1OtherR   0.9838710   21
15   14   0younger 14     0marg      0ItemOnPos 1OtherR   0.9556962   21
16   15   0younger 15     0marg      0ItemOnPos 1OtherR   0.9770642   21
17   16   0younger 16     0marg      0ItemOnPos 1OtherR   0.9861111   23
18   17   0younger 17     0marg      0ItemOnPos 1OtherR   0.9777778   23
19   18   0younger 18     0marg      0ItemOnPos 1OtherR   0.5428571   23
20   19   0younger 19     0marg      0ItemOnPos 1OtherR   0.9525862   23
21   20   0younger 20     0marg      0ItemOnPos 1OtherR   0.9547511   20
22   21   0younger 21     0marg      0ItemOnPos 1OtherR   1.0000000   20
23   22   0younger 22     0marg      0ItemOnPos 1OtherR   0.9555556   20
24   23   0younger 23     0marg      0ItemOnPos 1OtherR   0.9809524   20
25   24   0younger 24     0marg      0ItemOnPos 1OtherR   0.9960159   23
26   25   0younger 25     0marg      0ItemOnPos 1OtherR   0.9917695   23
27   26   0younger 26     0marg      0ItemOnPos 1OtherR   0.9833333   23
28   27   0younger 27     0marg      0ItemOnPos 1OtherR   0.9959514   23
29   28   0younger 28     0marg      0ItemOnPos 1OtherR   0.9621622   23
30   29   0younger 29     0marg      0ItemOnPos 1OtherR   0.9580838   23
⋮    ⋮    ⋮        ⋮      ⋮          ⋮          ⋮         ⋮           ⋮
1779 1778 1older   20     1recons    1PosOnItem 0OtherW   0.114864865 67
1780 1779 1older   21     1recons    1PosOnItem 0OtherW   0.056179775 67
1781 1780 1older   22     1recons    1PosOnItem 0OtherW   0.125000000 65
1782 1781 1older   23     1recons    1PosOnItem 0OtherW   0.200000000 65
1783 1782 1older   24     1recons    1PosOnItem 0OtherW   0.144444444 65
1784 1783 1older   25     1recons    1PosOnItem 0OtherW   0.036036036 65
1785 1784 1older   26     1recons    1PosOnItem 0OtherW   0.170454545 68
1786 1785 1older   27     1recons    1PosOnItem 0OtherW   0.004405286 68
1787 1786 1older   28     1recons    1PosOnItem 0OtherW   0.066666667 68
1788 1787 1older   29     1recons    1PosOnItem 0OtherW   0.000000000 68
1789 1788 1older   30     1recons    1PosOnItem 0OtherW   0.266666667 70
1790 1789 1older   31     1recons    1PosOnItem 0OtherW   0.093750000 70
1791 1790 1older   32     1recons    1PosOnItem 0OtherW   0.068965517 70
1792 1791 1older   33     1recons    1PosOnItem 0OtherW   0.333333333 70
1793 1792 1older   34     1recons    1PosOnItem 0OtherW   0.250000000 72
1794 1793 1older   35     1recons    1PosOnItem 0OtherW   0.080459770 72
1795 1794 1older   36     1recons    1PosOnItem 0OtherW   0.066666667 72
1796 1795 1older   37     1recons    1PosOnItem 0OtherW   0.111111111 72
1797 1796 1older   38     1recons    1PosOnItem 0OtherW   0.094594595 65
1798 1797 1older   39     1recons    1PosOnItem 0OtherW   0.156250000 65
1799 1798 1older   40     1recons    1PosOnItem 0OtherW   0.000000000 65
1800 1799 1older   41     1recons    1PosOnItem 0OtherW   0.069767442 65
1801 1800 1older   42     1recons    1PosOnItem 0OtherW   0.049079755 67
1802 1801 1older   43     1recons    1PosOnItem 0OtherW   0.166666667 67
1803 1802 1older   44     1recons    1PosOnItem 0OtherW   0.086956522 67
1804 1803 1older   45     1recons    1PosOnItem 0OtherW   0.211267606 67
1805 1804 1older   46     1recons    1PosOnItem 0OtherW   0.227848101 67
1806 1805 1older   47     1recons    1PosOnItem 0OtherW   0.125000000 67
1807 1806 1older   48     1recons    1PosOnItem 0OtherW   0.157894737 67
1808 1807 1older   49     1recons    1PosOnItem 0OtherW   0.176470588 67

**Binary age group: YA vs. OA**

In [6]:
binds_model <- lmer(bindScore ~ groupNo*bindConds + (1 | subjNo), data = binds_lmm_pd)

**Age as continuous variable**

In [9]:
# binds_model <- lmer(bindScore ~ age*bindConds + (1 | subjNo), data = binds_lmm_pd)

In [7]:
summary(binds_model)

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: bindScore ~ groupNo * bindConds + (1 | subjNo)
   Data: binds_lmm_pd

REML criterion at convergence: 747.5

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.61159 -0.86375  0.02746  0.81086  2.00721

Random effects:
 Groups   Name        Variance Std.Dev.
 subjNo   (Intercept) 0.001634 0.04042
 Residual             0.087343 0.29554
Number of obs: 1748, groups:  subjNo, 63

Fixed effects:
                                 Estimate Std. Error         df t value
(Intercept)                       0.48496    0.01481  420.94462  32.750
groupNo1older                    -0.06511    0.02049 1743.98656  -3.177
bindConds1OtherR                  0.26004    0.01919 1686.68727  13.551
groupNo1older:bindConds1OtherR   -0.04404    0.02841 1682.94934  -1.550
                               Pr(>|t|)
(Intercept)                     < 2e-16 ***
groupNo1older                   0.00151 **
bindConds1OtherR                < 2e-16 ***
groupNo1older:bindConds1OtherR  0.12128
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) grpN1l bnC1OR
groupNo1ldr -0.638
bndCnds1OtR -0.680  0.492
grpN1l:C1OR  0.459 -0.711 -0.675

In [8]:
anova(binds_model, ddf='Satterthwaite')

                  Sum Sq     Mean Sq    NumDF DenDF    F value    Pr(>F)
groupNo            3.1945096  3.1945096 1     1698.796  36.574400 1.803127e-09
bindConds         24.5184405 24.5184405 1     1683.102 280.715159 2.156194e-58
groupNo:bindConds  0.2098983  0.2098983 1     1682.949   2.403156 1.212787e-01

In [9]:
#emm_options(lmerTest.limit = 4000)
emm1 = emmeans(binds_model, specs = ~ groupNo*bindConds, lmer.df = "satterthwaite") # groupNo*reportType*bindConds
emm1

 groupNo  bindConds emmean     SE  df lower.CL upper.CL
 0younger 0OtherW    0.485 0.0148 421    0.456    0.514
 1older   0OtherW    0.420 0.0159 425    0.389    0.451
 0younger 1OtherR    0.745 0.0142 371    0.717    0.773
 1older   1OtherR    0.636 0.0158 419    0.605    0.667

Degrees-of-freedom method: satterthwaite
Confidence level used: 0.95

In [10]:
emm_pairs <- pairs(emm1, simple = "bindConds", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

groupNo = 0younger:
 contrast          estimate     SE   df t.ratio p.value
 0OtherW - 1OtherR   -0.260 0.0192 1687 -13.551  <.0001

groupNo = 1older:
 contrast          estimate     SE   df t.ratio p.value
 0OtherW - 1OtherR   -0.216 0.0210 1680 -10.309  <.0001

Degrees-of-freedom method: satterthwaite

## Figure 2H and 2I: overall binding score difference in Experiment 1

The binding score is calculated in the script: seqMemTask_v1_anal_summary.m

In [11]:
path_or_buf  <- paste0(FBdata_folder, bindsDiff_name)
binds_lmm_pd <- read.csv(file = path_or_buf)
binds_lmm_pd

    X   groupNo  subjNo reportType bindDirec  bindConds bindScore    age
1    0  0younger  0     0marg      0ItemOnPos 0cost      0.237500000 22
2    1  0younger  1     0marg      0ItemOnPos 0cost     -0.003984064 22
3    2  0younger  2     0marg      0ItemOnPos 0cost      0.154471545 21
4    3  0younger  3     0marg      0ItemOnPos 0cost     -0.018867925 21
5    4  0younger  4     0marg      0ItemOnPos 0cost     -0.016460905 25
6    5  0younger  5     0marg      0ItemOnPos 0cost      0.000000000 25
7    6  0younger  6     0marg      0ItemOnPos 0cost     -0.003418803 21
8    7  0younger  7     0marg      0ItemOnPos 0cost      0.000000000 21
9    8  0younger  8     0marg      0ItemOnPos 0cost     -0.026431718 23
10   9  0younger  9     0marg      0ItemOnPos 0cost     -0.012096774 23
11  10  0younger 10     0marg      0ItemOnPos 0cost      0.118499574 20
12  11  0younger 11     0marg      0ItemOnPos 0cost      0.356832448 20
13  12  0younger 12     0marg      0ItemOnPos 0cost      0.517129929 23
14  13  0younger 13     0marg      0ItemOnPos 0cost     -0.016129032 23
15  14  0younger 14     0marg      0ItemOnPos 0cost     -0.008589512 23
16  15  0younger 15     0marg      0ItemOnPos 0cost     -0.022935780 23
17  16  0younger 16     0marg      0ItemOnPos 0cost      0.280228758 21
18  17  0younger 17     0marg      0ItemOnPos 0cost      0.111111111 21
19  18  0younger 18     0marg      0ItemOnPos 0cost     -0.072527473 29
20  19  0younger 19     0marg      0ItemOnPos 0cost      0.152586207 29
21  20  0younger 20     0marg      0ItemOnPos 0cost      0.017251131 20
22  21  0younger 21     0marg      0ItemOnPos 0cost      0.055555556 20
23  22  0younger 22     0marg      0ItemOnPos 0cost      0.006403013 20
24  23  0younger 23     0marg      0ItemOnPos 0cost      0.114285714 20
25  24  0younger 24     0marg      0ItemOnPos 0cost     -0.003984064 29
26  25  0younger 25     0marg      0ItemOnPos 0cost     -0.008230453 29
27  26  0younger 26     0marg      0ItemOnPos 0cost     -0.016666667 23
28  27  0younger 27     0marg      0ItemOnPos 0cost     -0.004048583 23
29  28  0younger 28     0marg      0ItemOnPos 0cost      0.003828829 23
30  29  0younger 29     0marg      0ItemOnPos 0cost      0.170205044 23
⋮   ⋮   ⋮        ⋮      ⋮          ⋮          ⋮         ⋮            ⋮
875 874 1older   20     1recons    1PosOnItem 1benefit  0.07263514   70
876 875 1older   21     1recons    1PosOnItem 1benefit  0.64382022   70
877 876 1older   22     1recons    1PosOnItem 1benefit  0.26844262   65
878 877 1older   23     1recons    1PosOnItem 1benefit  0.08571429   65
879 878 1older   24     1recons    1PosOnItem 1benefit  0.22397661   72
880 879 1older   25     1recons    1PosOnItem 1benefit  0.72586873   72
881 880 1older   26     1recons    1PosOnItem 1benefit  0.19991582   72
882 881 1older   27     1recons    1PosOnItem 1benefit  0.32892805   72
883 882 1older   28     1recons    1PosOnItem 1benefit  0.38787879   65
884 883 1older   29     1recons    1PosOnItem 1benefit  0.50000000   65
885 884 1older   30     1recons    1PosOnItem 1benefit  0.23333333   69
886 885 1older   31     1recons    1PosOnItem 1benefit  0.31414474   69
887 886 1older   32     1recons    1PosOnItem 1benefit  0.09232481   67
888 887 1older   33     1recons    1PosOnItem 1benefit  0.10928962   67
889 888 1older   34     1recons    1PosOnItem 1benefit  0.24494949   67
890 889 1older   35     1recons    1PosOnItem 1benefit  0.49096880   67
891 890 1older   36     1recons    1PosOnItem 1benefit  0.74814815   65
892 891 1older   37     1recons    1PosOnItem 1benefit  0.38888889   65
893 892 1older   38     1recons    1PosOnItem 1benefit  0.17103041   68
894 893 1older   39     1recons    1PosOnItem 1benefit  0.12500000   68
895 894 1older   40     1recons    1PosOnItem 1benefit  0.57894737   70
896 895 1older   41     1recons    1PosOnItem 1benefit  0.63611491   70
897 896 1older   42     1recons    1PosOnItem 1benefit  0.54066384   72
898 897 1older   43     1recons    1PosOnItem 1benefit  0.27235772   72
899 898 1older   44     1recons    1PosOnItem 1benefit  0.46859903   65
900 899 1older   45     1recons    1PosOnItem 1benefit  0.33418694   65
901 900 1older   46     1recons    1PosOnItem 1benefit  0.19768381   67
902 901 1older   47     1recons    1PosOnItem 1benefit  0.51136364   67
903 902 1older   48     1recons    1PosOnItem 1benefit  0.32249742   67
904 903 1older   49     1recons    1PosOnItem 1benefit  0.08067227   67

In [12]:
binds_model <- lmer(bindScore ~ groupNo*reportType*bindConds + (1 | subjNo), data = binds_lmm_pd)

In [13]:
summary(binds_model)

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: bindScore ~ groupNo * reportType * bindConds + (1 | subjNo)
   Data: binds_lmm_pd

REML criterion at convergence: 7.1

Scaled residuals:
    Min      1Q  Median      3Q     Max
-4.2780 -0.6462 -0.1094  0.5493  3.5833

Random effects:
 Groups   Name        Variance Std.Dev.
 subjNo   (Intercept) 0.007806 0.08835
 Residual             0.052134 0.22833
Number of obs: 849, groups:  subjNo, 63

Fixed effects:
                                                   Estimate Std. Error
(Intercept)                                         0.09608    0.02357
groupNo1older                                       0.02676    0.03114
reportType1recons                                   0.25778    0.02908
bindConds1benefit                                   0.06219    0.03234
groupNo1older:reportType1recons                    -0.11447    0.04345
groupNo1older:bindConds1benefit                    -0.03891    0.04596
reportType1recons:bindConds1benefit                 0.04763    0.04353
groupNo1older:reportType1recons:bindConds1benefit  -0.01511    0.06328
                                                         df t value Pr(>|t|)
(Intercept)                                       408.99328   4.076  5.5e-05
groupNo1older                                     796.94188   0.859   0.3904
reportType1recons                                 778.89373   8.865  < 2e-16
bindConds1benefit                                 790.75519   1.923   0.0548
groupNo1older:reportType1recons                   778.40742  -2.634   0.0086
groupNo1older:bindConds1benefit                   785.30586  -0.847   0.3975
reportType1recons:bindConds1benefit               784.06366   1.094   0.2742
groupNo1older:reportType1recons:bindConds1benefit 781.29050  -0.239   0.8114

(Intercept)                                       ***
groupNo1older
reportType1recons                                 ***
bindConds1benefit                                 .
groupNo1older:reportType1recons                   **
groupNo1older:bindConds1benefit
reportType1recons:bindConds1benefit
groupNo1older:reportType1recons:bindConds1benefit
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) grpN1l rprtT1 bndCn1 grN1:T1 gN1:C1 rT1:C1
groupNo1ldr -0.589
rprtTyp1rcn -0.630  0.478
bndCnds1bnf -0.564  0.423  0.457
grpN1ldr:T1  0.421 -0.705 -0.669 -0.306
grpN1ldr:C1  0.397 -0.662 -0.322 -0.704  0.477
rprtTyp1:C1  0.419 -0.315 -0.667 -0.741  0.446   0.521
grpN1:T1:C1 -0.289  0.482  0.459  0.510 -0.686  -0.725 -0.688

In [14]:
anova(binds_model, ddf='Satterthwaite')

                             Sum Sq       Mean Sq      NumDF DenDF
groupNo                       0.557741837  0.557741837 1     835.8139
reportType                   10.116828073 10.116828073 1     782.9389
bindConds                     0.818864311  0.818864311 1     783.4465
groupNo:reportType            0.774654332  0.774654332 1     782.0560
groupNo:bindConds             0.112144399  0.112144399 1     783.5563
reportType:bindConds          0.083647117  0.083647117 1     781.4647
groupNo:reportType:bindConds  0.002970533  0.002970533 1     781.2905
                             F value      Pr(>F)
groupNo                       10.69828001 1.116269e-03
reportType                   194.05512070 1.440239e-39
bindConds                     15.70697965 8.070535e-05
groupNo:reportType            14.85896952 1.253676e-04
groupNo:bindConds              2.15108874 1.428700e-01
reportType:bindConds           1.60447043 2.056482e-01
groupNo:reportType:bindConds   0.05697903 8.113986e-01

In [29]:
#emm_options(lmerTest.limit = 4000)
emm1 = emmeans(binds_model, specs = ~ bindConds, lmer.df = "satterthwaite") # groupNo*reportType*bindConds
emm1

NOTE: Results may be misleading due to involvement in interactions

 bindConds emmean     SE  df lower.CL upper.CL
 0cost      0.210 0.0157 100    0.179    0.241
 1benefit   0.273 0.0161 111    0.241    0.304

Results are averaged over the levels of: groupNo, reportType
Degrees-of-freedom method: satterthwaite
Confidence level used: 0.95

In [30]:
emm_pairs <- pairs(emm1, simple = "bindConds", adjust = "bonferroni") # adjust = "bonferroni", "tukey"
emm_pairs

 contrast         estimate     SE  df t.ratio p.value
 0cost - 1benefit  -0.0628 0.0158 783  -3.963  0.0001

Results are averaged over the levels of: groupNo, reportType
Degrees-of-freedom method: satterthwaite